### ISSUE TITLE
#3506: interactive event translations for the new wording are missing

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1005]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/interactiveevents/interaktive-veranstaltung-13/
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Comment/Question: 
This is what we've decided for mB.
"@fredewe @lthueer and I agreed to call the categories here "Zugehörigkeit" which translates to "affiliation" (@phillimorland does that sound good to you?). This need to be changed for filter when entering the questions and in dashboard."

new wording would be:
navigation:
Zugehörigkeit /affiliation

form:
Zugehörigkeiten bearbeiten / edit affiliations

helptext:
Hier können Sie Zugehörigkeiten vorgeben. Nutzer*innen müssen Fragen entsprechend einordnen. Die Fragen können nach Zugehörigkeiten gefiltert und in der Statistik ausgewertet werden.
Here you can specify affiliations. Users must classify questions accordingly. The questions can be filtered by affiliation and evaluated in the statistics.

**Comment by Rineee** [comment]
@lthueer The translations are on transifex, but didnt pull them yet, because I am still waiting for the dutch translations, so we can get them from transifex altogether. But the English wording is right everywhere, so its just the German translations this issue is about?

**Comment by lthueer** [comment]
@Rineee exactly! Then I will close this issue :)

**Comment by phillimorland** [comment]
@lthueer affiliation sounds good, very neutral! :)
