### ISSUE TITLE
#3506 interactive event entering questions issue

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1008]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/interactiveevents/interaktive-veranstaltung-13/
**user:** all
**expected behaviour:** entering questions is possible
**behaviour:** entering questions not possible
**important screensize:**
**device & browser:** all
**Comment/Question:** If I want to add a question to the interactive event and send it, no question is shown in the list below

Screenshot?

**Comment by Rineee** [comment]
Oh no, thats bad. It works locally.. any idea @fuzzylogic2000 @rmader ?

**Comment by Rineee** [comment]
Its a 500, but I dont get why

**Comment by rmader** [comment]
So turns out this is a postgres speciality around autoincrement. So the easiest solution I could find would be to manually run the following commands once deployed (as root in the container):

```
psql -U django
SELECT setval(pg_get_serial_sequence('"a4_candy_interactive_events_livequestion"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "a4_candy_interactive_events_livequestion";
SELECT setval(pg_get_serial_sequence('"a4_candy_interactive_events_like"','id'), coalesce(max("id"), 1), max("id") IS NOT null) FROM "a4_candy_interactive_events_like";
```
