### ISSUE TITLE
stage: interactive event statistics issue

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1023]
**URL:** https://aplus-stage.liqd.net/liqd/interactiveevents/interactive-event/
**user:** initiator/admin/moderator
**expected behaviour:** the question goes back to unanswered 
**behaviour:** by clicking on the check mark in the statistics, nothing happens and the questions disappear.
**important screensize:**
**device & browser:** 
**Comment/Question:** I am unsure what was pokered here. An alternative would be that nothing happens and the answered questions remain as they're

![Bildschirmfoto 2020-12-10 um 14 12 28](https://user-images.githubusercontent.com/36957474/101777372-ad5d4680-3af2-11eb-8c03-fbdb30c223a2.png)

**Comment by Rineee** [comment]
By clicking the checkmark, you unclick the answered state, so it goes back to not answered (if you reload page and go back to questions tab it reappears there). But that everythings disappears after unclicking a question is a bug that we should fix. Will look into it!

**Comment by lthueer** [comment]
@Rineee that's what I thought, thank you!
