### ISSUE TITLE
stage: interactive event "live now" label issue?

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1024]
**URL:** https://aplus-stage.liqd.net/liqd/interactiveevents/interactive-event/
**user:** all
**expected behaviour:** the label, titel and description of the interactive event are centered
**behaviour:** currently they're left justified
**important screensize:**
**device & browser:** 
**Comment/Question:** Depending on how the design was, is this the way as it's supposed to be? Should it be more centered @mcastro-lqd ?

![Bildschirmfoto 2020-12-10 um 13 38 56](https://user-images.githubusercontent.com/36957474/101777836-5015c500-3af3-11eb-9166-dd9a1cdf7c6d.png)

**Comment by mcastro-lqd** [comment]
This adapted version is still centred https://zpl.io/aNrGZon

**Comment by phillimorland** [comment]
@mcastro-lqd my zeplin app says it's fully up to date and i've never seen those designs before, is there any reason you know that zeplin app doesn't update?

**Comment by mcastro-lqd** [comment]
@phillimorland  I never had that. 🤔 Zeplin doesn't work like Nextcloud, so independent from the version you have you should be able to see the last uploaded version.
