### ISSUE TITLE
a+ interactive event: Lack of feedback while entering questions

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1025]
**URL:** https://aplus-stage.liqd.net/a-workshop/interactiveevents/interaktive-veranstaltung-3/
**user:** registered/unregistered user
**expected behaviour:** when entering a question i would like to have some kind of feedback that my question was send.
**behaviour:** when entering a question by clicking the "add question" button there is no direct feedback that my question has been submitted. Due to the little lack between sending and displaying the added question i am not sure if my question was send.
**important screensize:**-
**device & browser:** macOS 11.0.1, Safari 14.0.1, Chrome 87.0.4280.88 (Offizieller Build) (arm64)
**Comment/Question:** 
Not sure if that needs to be fixed somehow. For the future we could think about a solution and maybe @mcastro-lqd has ideas for that?
Screenshot?

**Comment by phillimorland** [comment]
@fredewe right now if there is a long list the page scrolls down to where the question will appear (the timing is still a little slow unfortunately) this doesn't happen when there is no questions or it's short list.

**Comment by fredewe** [comment]
@phillimorland thanks! It is ok like that even though the jump could be a little more on the latest added question i would say. But we can think about that later. :)

**Comment by phillimorland** [comment]
@fredewe that should be a bit better now

**Comment by fuzzylogic2000** [comment]
That means we take this out of the milestone for this release? And add it to the one for the next release?

**Comment by phillimorland** [comment]
i'm taking it out

**Comment by mcastro-lqd** [comment]
@fredewe I mentioned that for meinBerlin and we thought about this "anchor link" (idk if that the proper dev term to say haha) that takes you to your question already displayed.

**Comment by fuzzylogic2000** [comment]
What's the status here? Is it already fixed enough to be closed?
Or should the improvements from mB also be added to a+ at some point? Then it's probably a good idea to add this to the mB-story to look out for? @lthueer @fredewe

**Comment by phillimorland** [comment]
both project have an anchor tag that has been repositioned to ensure the new question is clearly on the screen
