### ISSUE TITLE
interactive event missing translation

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1055]
**URL:** https://adhocracy.plus/test/dashboard/projects/testprojekt-bremen/blueprints/
**user:** all
**expected behaviour:** The translations should be adjusted as follows
**behaviour:** Currently it says still "Merkmal" in the module description when adding a module
**important screensize:**
**device & browser:** 
**Comment/Question:** 

"Sie als Moderation können die Fragen anhand von Unterstützung und Zugehörigkeiten sortieren."

"You as the moderator can sort the questions by support or affiliation."

"U als moderator kunt de vragen sorteren op ondersteuning of groeperingen."

![Bildschirmfoto 2021-01-06 um 16 57 01](https://user-images.githubusercontent.com/36957474/103789766-ab7a9a80-5040-11eb-9900-679835bbeca4.png)

**Comment by fuzzylogic2000** [comment]
@lthueer Could you give us the English text to change? After that is changed, the translations need to be changed in transifex.

**Comment by lthueer** [comment]
Yes, of course. Here is the text:

Now:
"The participants of an event can ask their questions online. Other participants can support the question. You as the moderator can sort the questions by support or characteristic."

How it should be:
"The participants of an event can ask their questions online. Other participants can support the question. You as the moderator can sort the questions by support or affiliation."

**Comment by lthueer** [comment]
@Rineee @phillimorland could you also please update this wording in Transifex for the next release? That would be great! As far as I can see it it's still "characteristic" and not "affiliation" :)
