### ISSUE TITLE
Organisation dashboard: moderators are not copied over when project is

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#1063]
**URL:** aplus-dev.liqd.net/liqd-orga/dashboard/organisations/projects/
**user:** 
**expected behaviour:** If I copy a project, the moderators should also be copied to avoid having no moderators
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by mhagwitjes** [comment]
How is copying a project to another organisation possible by the way? Can't seem to find it. I want to have a testproject in 51 different organisations, so if I could copy it that would save a lot of work :)

**Comment by mhagwitjes** [comment]
Never mind :) I now know you can duplicate the project from the dashboard and then in the back-end change the organisation.

**Comment by fuzzylogic2000** [comment]
> Never mind :) I now know you can duplicate the project from the dashboard and then in the back-end change the organisation.

@mhagwitjes Yes, that's a good idea! I can't think of a better way to do it. (Using the django shell might be another way, but that's most likely harder when you also have to make sure you copy the module and phases and everything..)
