### ISSUE TITLE
count downvotes in order of ideas in prio

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#107]
https://adhocracy.plus/musterorganisation/projects/unser-leitbild/?initialSlide=3&ordering=-positive_rating_count

expected: If I set filter on "am beliebtesten" I expect the negativ ratings to be counted as well. 
behavior: an idea with no upvotes and two downvotes is before an idea with no upvotes and only one downvote.

Comment: I know we can get very complicated here. Would it be an idea to count the upvotes first and the downvotes second?

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer Is this a wording issue? Maybe the order that we have now should be called 'Number of likes' and the other one with the dislikes/downvotes included would be 'most reactions'?

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN sounds good. In German maybe: "meiste positive Bewertungen" and "meist bewertet" (most ratings - a comment is also a reaction)? Although if I have most likes I also expect to be able to order according to most dislikes.

**Comment by fuzzylogic2000** [comment]
@lthueer @fredewe Can you tell us what the wording should be and where to add it? Do we just need to change the wording or also the behaviour of a filter?

**Comment by lthueer** [comment]
@fuzzylogic2000 we can keep the wording how it is, because we couldn't find a better (concise) wording solution!
