### ISSUE TITLE
sorting of projects on organisation landing page is not right / when is a project active?

### ISSUE THREAD

**Issue by Rineee** [liqd/adhocracy-plus#1074]
**URL:** 
**user:** 
**expected behaviour:** First active projects are shown, then future projects, then past projects 
**behaviour:** The sorting is not right, see comment
**important screensize:**
**device & browser:** 
**Comment/Question:** 
We group projects by active, future, past and list them in this order on the organisation landing page.
For grouping, we are considering the minimum start (min_start) date of (all phases) of all modules of the project and the respective maximum end date (say max_end). Then a project is considered 

- active if min_start <= now < max_end
- future if now < min start
- past max_end < now

see [here](https://github.com/liqd/adhocracy-plus/blob/c797bf6e6ddb0b2cc00ef0d70d5c5922a39a0bdf/apps/organisations/models.py#L175)
But this means e.g. that a project with one past module and one future module will be considered active.  

Also, single module projects that have several phases, say one over, one future, are considered active. 

I think we have to rethink/define:

- when is a module active?
- when is a (multi module) project active?

and then do the grouping accordingly.

Connected to https://github.com/liqd/adhocracy-plus/issues/1076

Screenshot?

**Comment by Rineee** [comment]
See also discussion here: https://taiga.liqd.net/project/mkay-kosmo/us/7

**Comment by lthueer** [comment]
added to taiga story

**Comment by Rineee** [comment]
@lthueer @fredewe Because it now also came up in the app.. Should we work on this and https://github.com/liqd/adhocracy-plus/issues/1076 soon? Maybe you could link the story?
