### ISSUE TITLE
use same end date for sorting of projects and indication on project tile

### ISSUE THREAD

**Issue by Rineee** [liqd/adhocracy-plus#1076]
**URL:** 
**user:** 
**expected behaviour:** The sorting of projects is consistent with what is written on project tile. 
**behaviour:** The projects are sorted according to end_date of last ending module (see [this issue](https://github.com/liqd/adhocracy-plus/issues/1074)), but for the text on project tile, we use project.module_running_time_left which is time left of currently active module that ends next.
This means that if we have a project with 2 active modules, one ending in 1 day and the other in 2 years, it will appear at the very back of the list of active projects, but with '1 day remaining' written on it.
**important screensize:**
**device & browser:** 
**Comment/Question:** Connected to https://github.com/liqd/adhocracy-plus/issues/1074

Screenshot?

**Comment by fuzzylogic2000** [comment]
@fredewe @lthueer here, we need a concept! Maybe in a workshop? Or just a story (even if it is only to save our thoughts somewhere) about project sorting and status bar? As it currently is, it doesn't feel consistent. Should be done together with #1047

**Comment by fredewe** [comment]
@fuzzylogic2000 we will write a story for that and maybe invite for a concept meeting. Will close this issue now.
