### ISSUE TITLE
labels displayed confusingly when adding new topic in priorisation module 

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#108]
URL: https://adhocracy.plus/test/dashboard/topics/2019-308/update/
user: initiator / moderator 
expected behavior: when adding a new topic, I can decide on a label that are displayed symmetrically 
behavior: labels are displayed very close to each other and in two lines 
screensize: any - except mobile 
device & browser: macbook air, firefox
![Bildschirmfoto 2019-11-22 um 14 51 30](https://user-images.githubusercontent.com/57798416/69431283-b3da1e00-0d37-11ea-889d-608eb60ce92d.png)

**Comment by phillimorland** [comment]
NOTE: adhocracy classname problem
