### ISSUE TITLE
Unnecessary to put in time of event - not displayed in user view 

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#109]
URL: https://adhocracy.plus/test/dashboard/offlineevents/projects/party-cipation/
user: moderator / initiator 
expected behavior: since initiator is asked to insert time of offline event, the time will also be shown to regular users in the timeline 
behavior: initiator can set a time but that in the timeline view of the project, only the day is shown. 
screensize: any 
device & browser: macbook air, firefox

**Comment by MagdaN** [comment]
@Amelie-liqd good catch! This is also an issue for meinberlin then. @CarolingerSeilchenspringer @rittermo what do you think?

**Comment by CarolingerSeilchenspringer** [comment]
@Amelie-liqd thanks, Amelie!! @MagdaN @rittermo I would display both date and time below the title of the event as the additional time would be too much info for the timeline. So (apart from the timeline) the user sees the most important facts (title, date, time) at first view, followed by additional info.

<img width="737" alt="Bildschirmfoto 2019-12-17 um 16 38 53" src="https://user-images.githubusercontent.com/35491681/71010241-d4ee1e80-20eb-11ea-8bfb-04551371d311.png">

**Comment by rittermo** [comment]
Thanks for the issue! I would like to hand my input over to @fredewe
