### ISSUE TITLE
interactive event: "nothing selected" info message

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1092]
**URL:** https://adhocracy.plus/model-organization/interactiveevents/interactive-event/
**user:** all
**expected behaviour:** When I don't select an affiliation, question or check the checkbox, I get a messsage in English that I have to fill it out. Additionally, the message does stay in the same position when you scroll down or up the page and highlights the missing field.
**behaviour:** I do get a message for the unselected affiliation, question or checkbox, but it is in German when another language is selected. (Only in Firefox) the message does not stay in the same place when you scroll up or down, but accompanies you.
**important screensize:** /
**device & browser:** Mac Os, all
**Comment/Question:** An English translation would help here.

![Bildschirmfoto 2021-02-04 um 11 16 29](https://user-images.githubusercontent.com/36957474/106879755-d7d71480-66db-11eb-9443-9990f6e8ca19.png)

![Bildschirmfoto 2021-02-04 um 11 17 24](https://user-images.githubusercontent.com/36957474/106879762-d9084180-66db-11eb-9080-495c91b72834.png)

This is when you scroll down and the message moves to another place than expected.
![Bildschirmfoto 2021-02-04 um 11 17 46](https://user-images.githubusercontent.com/36957474/106879764-d9a0d800-66db-11eb-8850-86e1c8349ec0.png)

**Comment by phillimorland** [comment]
@lthueer this is a browser error message created by the required html field (same as when you miss a check box at registraion or something) we do not style or write it or control the scroll behaviour and the language should be displayed based on your browser language, is it possible its in english?

**Comment by lthueer** [comment]
@phillimorland it changes the language when I change the browser language  I will close the issue now!
