### ISSUE TITLE
new moderators cannot edit after accepting invitation 

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#110]
URL: https://adhocracy.plus/test/projects/agenda-punkte-brainstormen/
user: moderators
expected behavior: after accepting the invitation to be moderator in a project, the new moderator can edit the project in the dashboard. 
behavior: when accepting the invitation, the 'edit' button appears. But when pressing the 'edit' button, error message 403 appears.
device & browser: macbook air, firefox

comment: this was tested in the priorisation and brainstorming module.

**Comment by MagdaN** [comment]
@rittermo @fredewe should moderators be allowed to edit the project?

**Comment by rittermo** [comment]
@MagdaN I don’t think so. But the edit button should not be displayed for moderators. @Amelie-liqd were you still logged in with an initiator account, when you clicked the link in the invitation email?

**Comment by Amelie-liqd** [comment]
@rittermo No the edit button is always there when I log in as a moderator.

**Comment by CarolingerSeilchenspringer** [comment]
@rittermo we should consider the same problematic we have on meinberlin and the reason for implementing groups, that is: external offices cannot make projects on behalf of e.g. a municipality. I would suggest implementing groups on a+ and then restrict moderators rights. during launch I already got a question relating this issue.

**Comment by MagdaN** [comment]
@CarolingerSeilchenspringer I added this as a feature idea here: https://adhocracy.plus/feedback/ideas/2019-00410/

So this issue will just be about removing the edit button for moderators.
