### ISSUE TITLE
Embed: Registration and login fails in embedded projects

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1105]
**URL:** https://www.futuresday.org/participate
**user:** user
**expected behaviour:** *as a user i would expect to be able to log in via the button in the iframe*
**behaviour:** *the log in window disappears after clicking the button and a log in is not possible*
**important screensize:** 
**device & browser:** *macOS 11.2, Safari, Chrome, Firefox*
**Comment/Question:**

**Comment by fredewe** [comment]
already tested the fix on dev. Works perfectly fine now.

**Comment by fuzzylogic2000** [comment]
Ok, we are done here, I will close! It will be in the next release (which you'll have to schedule :)).
