### ISSUE TITLE
some english emails have spelling mistakes 

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#111]
user: user/moderator/initiator
expected behavior: emails sent automatically are correct in terms of spelling and grammar 
behavior: email to moderator when a comment is added has a mistake ("checkout" and Comment capitalised), invitation email to user for a private project inserts "HAHA" in the topic line and "accept" is misspelled. 
![Bildschirmfoto 2019-11-22 um 16 38 42](https://user-images.githubusercontent.com/57798416/69439100-8d6faf00-0d46-11ea-9da9-9e7e0c5a2bb1.png)

**Comment by fuzzylogic2000** [comment]
This is already fixed on dev. Could you check it out there?
