### ISSUE TITLE
is the two-column block meant to look like that?

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#1145]
**URL:** https://aplus-dev.liqd.net/
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** I just saw it on the landing page on aplus-dev and would think, that images and heading should be above the text? @phillimorland ?

Screenshot?
![Screenshot from 2021-03-05 09-16-51](https://user-images.githubusercontent.com/8178179/110087185-a06b8e80-7d93-11eb-96bc-af50c35535c4.png)

**Comment by phillimorland** [comment]
they should! thinks its a leak from that weird 2col list with image block we have

**Comment by fuzzylogic2000** [comment]
Cool! Then, probably it's just the wrong image to use here. :)

**Comment by phillimorland** [comment]
I would leave this open as a 2 col cta should be able to have images too, the leaked style from the other block type is an issue

**Comment by fuzzylogic2000** [comment]
Ah, now I got it! :)

**Comment by fuzzylogic2000** [comment]
@phillimorland Let's also look at this when we do #494 !
