### ISSUE TITLE
Date still English when kyrgyz selected

### ISSUE THREAD

**Issue by philli-m** [liqd/adhocracy-plus#1161]
**behaviour:** should look normal  
**device & browser:** mobile firefox

Screen shots

- [x] 1. language menu moves down when opned and back up when cloed

![Screenshot from 2021-03-11 15-14-43](https://user-images.githubusercontent.com/5871230/110801088-29476600-827d-11eb-84d7-5e0284f4a846.png)

- [x] 2. project ended too much padding 

![image](https://user-images.githubusercontent.com/5871230/110803088-20f02a80-827f-11eb-8a8b-0b4a9b707ec5.png)

- [ ] 3. Month not translated, can we fix that?

![image](https://user-images.githubusercontent.com/5871230/110803499-8cd29300-827f-11eb-9ca8-e01f8606ee49.png)

- [x] 4. small screens project list btn group wrong 

![image](https://user-images.githubusercontent.com/5871230/110803654-b4c1f680-827f-11eb-9ddb-78a9b65fc38f.png)
![image](https://user-images.githubusercontent.com/5871230/110803774-d6bb7900-827f-11eb-9a93-f41032a2e3b6.png)

**Comment by lthueer** [comment]
@phillimorland with regards to point 3., the same is true when the date is displayed within the project. There seem to be differences between Russian and Kyrgyz, for Russian apparently the month is translated, not for Kyrgyz though

Kyrgyz selected:
![Bildschirmfoto 2021-03-12 um 10 32 31](https://user-images.githubusercontent.com/36957474/110921427-d2926880-831e-11eb-9074-ce6948328d80.png)

**Comment by fredewe** [comment]
For 3: The calendar is also not translated into German and Dutch, so it is always English. We don't have to change that in my opinion.

**Comment by phillimorland** [comment]
@lthueer in this case we get the date from a django library, i'm not sure how we can update a default library, @fuzzylogic2000 @Rineee any ideas?

**Comment by fuzzylogic2000** [comment]
For the list display we use a weird template tag from mB: https://github.com/liqd/adhocracy-plus/blob/17e07f0305d9cb415bfdfc661ea65aea029009b2/apps/contrib/templatetags/contrib_tags.py#L44
If we use the normal django date format instead, it should be properly localised, I hope.
Or did you mean the calendar in the dahboard?

**Comment by phillimorland** [comment]
Ahh awesome! and no I figured out the calendar is becasue we don't include the package path in our make po command, I might see how it is if I add it there as it's a bit uncool, not sure it'll be that simple but if it is then yey

**Comment by Rineee** [comment]
Reopen this because of date issue

**Comment by phillimorland** [comment]
@lthueer @fredewe The date translation seems to be unviable, i've tried various overwrites none of which have worked. I'm not sure what else to try, I believe part of the issue will be solved when we next update django as Kyrgyz has been added to the most recent django release but we only update it when it's a stable version so might be a while, also the day name translations come from a seperate library through python so i'm not sure on that one. My only suggestion would be to change the format of dates we use to numerical or leave it and hope the libraries are updated, what should we do?

**Comment by lthueer** [comment]
@phillimorland @fredewe If we're unsure about whether it will change correctly after the libraries are updated, I would go for the change to the numerical format then. Also the Russian dates seem a bit odd to me. One thing we should keep in mind is that the dates in the timeline change as well, but I think that should be okay. What do you think @fredewe ?

**Comment by fredewe** [comment]
I would wait if it can be solved with the Django update. Otherwise i would change it to the numerical format in the next release.

**Comment by phillimorland** [comment]
ok will remove from this release milestone then

**Comment by lthueer** [comment]
This issue is done already, except from my first comment and the python update for Kyrgyz date/time. If it's not in the next update in Wagtail, please remove from milestone. Thanks!

**Comment by fuzzylogic2000** [comment]
@lthueer @phillimorland Did I get it right, that this issue is not about the styling anymore - that is done, right? 
This is now about the date that is not translated. I will change the title! If I got it wrong, change it back and comment!

**Comment by khamui** [comment]
okay after reading through this conversation, i think i got what the current status is.
For the comment (async) date we are currently using a helper function on the frontend and not the django date.
Actually i don't really know where to start to make use of the django date. I missed this conversation and started
to search for a frontend solution (see below). What shall we do now? Try to use django date and see if Kyrgyz works? Or using the frontend solution below, which I would need to work on a little bit and for now it is only for comments.

I think this is more a dev discussion, so tagging @phillimorland @fuzzylogic2000 @Rineee

Frontend solution in a4 (currently only affecting dates of comments):
https://github.com/liqd/adhocracy4/pull/993#issue-1147097410
