### ISSUE TITLE
Text on invitation page for private projects not understandable 

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#117]
**URL:** in English and German email
**user:** user who is invited to a private project
**expected behaviour:** 

- German Text: 'Einladung zur Teilnahme am Projekt "Projektname".

- English Text: ''Invitation to participate in the project "projectname".

**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by MagdaN** [comment]
@fredewe 

I changed it to the following german version, what do you think:

![Bildschirmfoto 2019-11-27 um 13 47 29](https://user-images.githubusercontent.com/2905743/69724696-b2846900-111c-11ea-9c47-b9bce178c2b4.png)

**Comment by fredewe** [comment]
@MagdaN: I like the new version!
