### ISSUE TITLE
Language setting for invitation mails

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#120]
**URL:** http://aplus-dev.liqd.net (German language activated)
**user:** admin 
**expected behaviour:** As a german speaking user i would expect to get an invitation for a+ in german.
**behaviour:** The invitation is in english
**important screensize:**
**device & browser:** macOS 10.11.6, Safari 11.1.2 (Language DE)
**Comment/Question:** 

Screenshot?

**Comment by MagdaN** [comment]
@fredewe I tested this, if the email address the the invite is sent to belongs to a registered user and this user has his preferred language set to german then the email will be sent in German. If the email address does not belong to a user yet, the email is sent in the default user language and this is english.

**Comment by MagdaN** [comment]
@fredewe I added an idea to our idea backlog: https://adhocracy.plus/feedback/ideas/2019-00409/

**Comment by fredewe** [comment]
Cool. Thank you!

**Comment by lthueer** [comment]
@fuzzylogic2000 @fredewe didn't we solve this with the standard language for emails which is implemented? If you read this and agree, please close the issue!

**Comment by fuzzylogic2000** [comment]
@lthueer Totally! Nice!
