### ISSUE TITLE
Captcha a11y issues

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#1215]
Captcha label not tabbable so can only change mode and enter an answer, not have question read out, also issue in mB

Also in new safari entire captcha is not in tabbing order for some reason?! - check original directory incase they have implemented a fix.

**Comment by sabinammm** [comment]
I retested this:
On Windows it works on edge, firefox, chrome, opera (but just ignores the minus symbol), safari (5.1) on windows can't open the page, and there's no captcha on explorer. 
On the Mac on Safari 14.1 the captcha is read, but everything else is in chaos unless selected individually.
@phillimorland do you think we can close this?

**Comment by phillimorland** [comment]
maybe but we'll just have to open a new one for the minus symbol so I think just update this one?

**Comment by fuzzylogic2000** [comment]
@phillimorland We will work on the captcha at some point? Should this be kept open as reminder or can we close it?

**Comment by phillimorland** [comment]
we can close, when we work on the capcha we'll has to do a a11y check of it again anyway
