### ISSUE TITLE
 Browser says I haven´t sent information

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#1226]
**URL:** https://kosmo-dev.liqd.net/liqd/subjects/2021-00017/
**user:** admin
**expected behaviour:** I reported a comment and then just go via the "back" button back to the discussion
**behaviour:** My browser warns me that I haven´t sent the information that I put in - but I did!
**important screensize:** Desktop
**device & browser:** MacBook, Mozilla
**Comment/Question:** Is this something in our hands or is it something with the Browser I use?

<img width="935" alt="Bildschirmfoto 2021-04-26 um 11 30 02" src="https://user-images.githubusercontent.com/30862422/116061378-12b96a80-a683-11eb-99e2-64248c54b7ec.png">

**Comment by fuzzylogic2000** [comment]
I think for mB, we disabled it site-wide and only use the alert in the dashboard. To check if need to do same here!
