### ISSUE TITLE
"Open link in new window"-feature in editor tool seem to be broken

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#123]
**URL:** https://adhocracy.plus/musterorganisation/dashboard/projects/stellen-sie-ihre-fragen-an-die-abgeordnete-aus-mus/information/
**user:** admin/initiator
**expected behaviour:** when a link is posted in the project information with the target "new window, i expect that to happen when the link gets clicked 
**behaviour:** the link opens in the same page
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fredewe** [comment]
![Bildschirmfoto 2019-11-28 um 15 31 46](https://user-images.githubusercontent.com/5470479/69814577-c69b9980-11f4-11ea-87c1-d501faab2481.png)

**Comment by CarolingerSeilchenspringer** [comment]
please note that we have the same issue in meinBerlin: https://github.com/liqd/a4-meinberlin/issues/1591

**Comment by MagdaN** [comment]
This comes from an external library which we can't control.

**Comment by CarolingerSeilchenspringer** [comment]
@MagdaN is the library open source? Can we somehow influence them to change it? or in general think about a different library here? I don't find it very user friendly.
