### ISSUE TITLE
Newsletter function does not work 

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#124]
**URL:** https://adhocracy.plus/test/dashboard/newsletters/create/
**user:** initiator 
**expected behaviour:** I can send a newsletter via the newsletter function in the dashboard to all users following that module. 
**behaviour:** Newsletter does not send: after clicking 'send' I still view the same email draft, subscribers to the module do not receive an email

**Comment by phillimorland** [comment]
duplicate issue to #297 so closing
