### ISSUE TITLE
'phases' section is confusing 

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#125]
**URL:** https://adhocracy.plus/test/dashboard/modules/priorisierung-2/phases/
**user:** Initiator 
**expected behaviour:** I know what is meant by phases and it is clear to me what those dates are for. 
**behaviour:** the form generally is confusing in all modules except idea collection - the subheading "Prioritize phase" for example is unclear. 
**Comment/Question:** Maybe instead of phase we could call it 'Beteiligungszeitraum' / 'Participation period'... seems like we need a concept for this, maybe it's a story?

![Bildschirmfoto 2019-11-28 um 15 46 28](https://user-images.githubusercontent.com/57798416/69815260-3f4f2580-11f6-11ea-99e6-a3b8a8707e5b.png)

**Comment by MagdaN** [comment]
@Amelie-liqd, thanks, I also think this should be changed. To change this we would need the new wording in english and german.

**Comment by fuzzylogic2000** [comment]
@lthueer We can only fix stuff that has a concept and wording! So, we need that before we can fix it later. :)

**Comment by lthueer** [comment]
Transcribed into a story as the wording of the general phase description was needed.
