### ISSUE TITLE
a+ Prioritization: Missing translation

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1255]
**URL:** https://adhocracy.plus/musterorganisation/dashboard/topics/2020-556/update/
**user:** Initiatior
**expected behaviour:** When a+ is set to german and i write a new topic, the title of the field descriptions says "Beschreibung"
**behaviour:** instead it says "descrition"
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2021-05-06 um 17 11 47](https://user-images.githubusercontent.com/5470479/117322279-26887c00-ae8e-11eb-9bfd-69b29d12c3c2.png)

**Comment by fuzzylogic2000** [comment]
@fredewe You should be able to translate it yourself on transifex!

**Comment by fuzzylogic2000** [comment]
Sorry, no! The string wasn't translatable yet. Will fix it!
