### ISSUE TITLE
[a+] #4129 manual testing: Interactive Event adapting design of module detail view

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1263]
**URL:** https://aplus-dev.liqd.net/frede-test/projects/test-projekt-4129/
**user:** -
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** tested on a mac with safari and chrome+ iPhone with safari
**Comment/Question:** 

1. Text lengths: On the detail page there are two text: The first one is the short description from the basic settings and is shown in full length. The second one is the description from the phases and it is shorter then the first one but gets shortened. Is this how it was meant? @mcastro-lqd 
![Bildschirmfoto 2021-05-09 um 22 53 30](https://user-images.githubusercontent.com/5470479/117586725-3916e580-b11a-11eb-94f1-cece45d73fb7.png)

2. The "live"-tag was missing, when the event was in the active phase.

3. The event-image was not visible / broken:
![Bildschirmfoto 2021-05-09 um 23 12 40](https://user-images.githubusercontent.com/5470479/117587017-0f5ebe00-b11c-11eb-949f-838a8a3408a7.png)

**Comment by fredewe** [comment]
Hi, that was all i could find so far. I hope it works for you like that. Please ask me, if you have any questions about it. Thanks!

**Comment by khamui** [comment]
Thanks for testing!

Just figured out that in case of multiple **active** modules, the `carousel` on top of the detail content is shown (see screenshot below). So i guess we remove that "doubled" content along with the buttons `next >` on the upper right corner? What do you think about it @mcastro-lqd  @fredewe?

<img width="891" alt="Bildschirmfoto 2021-05-10 um 09 34 44" src="https://user-images.githubusercontent.com/52801593/117633635-24683b00-b176-11eb-88c1-b0c9deb7f197.png">

**Comment by fuzzylogic2000** [comment]
Yes, we should remove the upper content (And I hope that's not too hard)! But we shouldn't (and probably can't without a lot of hassle) remove the "Next" as this module is like all the other modules and the list for the next/other modules is made in a4.

**Comment by khamui** [comment]
Thanks @fuzzylogic2000 for the feedback. Will mark that issue as 4.)
So I will take care of 3.) and 4.) for now and wait for FB regarding 1.) and 2.).

**Comment by fredewe** [comment]
> @fredewe Thanks for testing!
> Concerning point 2: the 'live now' tag is only there if its in the active phase and there is a live stream. So we change it to always show it during active phase independent from live stream?

@Rineee Thanks for your reply! I think we should change it to always show the tag during the active phase independently from stream.
