### ISSUE TITLE
#2494: Some scaling adaptions

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#127]
**URL:** https://aplus-dev.liqd.net
**user:** participant/ CMS editor
**expected behaviour:**
- the subtitle should be about as large as an h3; see productive platform
- the whole header area should be vertically higher on larger screens (ca. 1280px upwards), so that not too much of the image is overlayed by text and shadow and that more of the image is visible (see productive)

**behaviour:** 
- see above
**important screensize:** from 1280px upwards
**device & browser:** Safari 12.1.1
**Comment/Question:**

**Comment by phillimorland** [comment]
subtitle is a text block so you can choose the size, have updated dev
