### ISSUE TITLE
#2494: slight changes of info button

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#128]
**URL:** https://aplus-dev.liqd.net
**user:** participant/editor
**expected behaviour:** 
- the button should not draw too much attention, so we should make it non-filled with a white border and white „i“ inside
- the text inside the popover should be easily readable, so we should make it a 20%  wider

**behaviour:** 

see above

**important screensize:** all screensizes

**device & browser:** MacOS X, Safari 12.1.1.

**Comment/Question:**

**Comment by phillimorland** [comment]
@rittermo with 20% wider do you mean make the font 20% larger or add a margin so the tool tip is just bigger?
