### ISSUE TITLE
#4131 interactive event design of tabs: statistics button outline issue 

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1281]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/interactiveevents/interaktive-veranstaltung-13/
**user:** all
**expected behaviour:** The statistics button is not outlined in blue when going back from "Statistics" to the questions and only remains blue as long as you see the statistics
**behaviour:** Apparently, the outline of the button remains blue when clicking on the "cross"in the statistics and you get back to the questions
**important screensize:** 
**device & browser:** all
**Comment/Question:** Is the cross really necessary? Intuitively speaking I would rather click on the statistics button again if I want to get back to the questions. If it's not possible to change the outline this could be an option maybe.

![Bildschirmfoto 2021-05-11 um 10 51 24](https://user-images.githubusercontent.com/36957474/117795102-27365f00-b24e-11eb-821a-fca4c4e0ec89.png)
![Bildschirmfoto 2021-05-11 um 10 51 33](https://user-images.githubusercontent.com/36957474/117795107-27cef580-b24e-11eb-987b-4c27e9ebb19f.png)

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd I think, you need to tell us what the best way would be?

**Comment by phillimorland** [comment]
@lthueer as mentioned in the story, this is a interim solution, designs can be seen here https://app.zeplin.io/project/5b051f895f8bcd4920567e89/screen/6092bec83555340c3d987325 I can take out the close as maybe easier then fixing the active behaviour but I would go with whatever @mcastro-lqd suggests

**Comment by lthueer** [comment]
@phillimorland Alright, that makes sense, I didn't see that before! As long as the blue outline behaviour is working, I am fine with any (interim) solution. Thank you!

**Comment by mcastro-lqd** [comment]
I just thought that the statistic should be more like the same style as the info button, cause it adds some more info to the event, that's why I tried to make them having kind of the same behaviour. Considering the button, it should go back to black once it's out of the statistic part.
