### ISSUE TITLE
Custom URLs

### ISSUE THREAD

**Issue by rmader** [liqd/adhocracy-plus#130]
Todo:
- [x] search engine integration
  - [x] robots.txt
  - [x] sitemaps
  - [x] register on google / bing
- [x] general check if any URLs were forgotten
- [x] comment share link
- [x] error pages
- [x] social logins...
- [x] mails
  - [x] registration mails
  - [x] moderator invites
  - [x] participant invites
  - [x] welcome to private project email
  - [ ] reports
  - [x] notifications 
  - [x] newsletter
  - [x] other?

**Comment by fuzzylogic2000** [comment]
@goapunk This was for the redirects. Maybe we can have a look together what already works and what doesn't?

**Comment by goapunk** [comment]
@fuzzylogic2000 yes, sure!

**Comment by goapunk** [comment]
This is about the urls for orgs with an own domain, right ? e.g. in case of the sitemaps: https://beteiligung.arnsberg.de/sitemap.xml ?

**Comment by goapunk** [comment]
so sitemaps and robots work, about the reports I don't know how to trigger them, maybe we'll check that out together

**Comment by phillimorland** [comment]
@fuzzylogic2000 is this all good now?

**Comment by fuzzylogic2000** [comment]
@phillimorland I think so, but will assign myself and check the reports and for other emails and will then close!

**Comment by fuzzylogic2000** [comment]
Ok, the report is really still missing. So, needs more investigation also for other e-mails.
