### ISSUE TITLE
Map predefined area in Dashboard is new & incomplete

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1305]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/dashboard/modules/ideenwettbewerb-mit-karte-6/area_settings/
**user:** initiators
**expected behaviour:** more than one area is suggested or the customization is disabled.
**behaviour:** only Bayern is displayed
**important screensize:**
**device & browser:** 
**Comment/Question:** Why does it show this? This haven't been there before, right?

![Bildschirmfoto 2021-05-18 um 14 59 56](https://user-images.githubusercontent.com/36957474/118655948-53238880-b7ea-11eb-9e4b-a5f8b7650c82.png)

**Comment by fuzzylogic2000** [comment]
You can change or add that in the django-admin: https://aplus-dev.liqd.net/django-admin/a4_candy_maps/

**Comment by fuzzylogic2000** [comment]
If you want to do that, it would be good to quickly talk, though. The category shouldn't also be Bayern, but rather "Bundesland" and then, we probably also need countries?!

**Comment by lthueer** [comment]
@fuzzylogic2000 alright, thank you! I was just wondering because I never saw this feature before, on productive it's disabled in the django, so everything is fine. We don't need this currently, but it's good to know that it exists, if needed in the future.
