### ISSUE TITLE
#4129 [a+] interactive event: adapting design of module detail view UI/UX

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#1306]
**URL:** https://aplus-dev.liqd.net/teststadt/interactiveevents/interaktive-veranstaltung-7/
**important screensize:** *Both*
**device & browser:** *Safari Version 14.0.3 (16610.4.3.1.7)*
**Comment/Question:** *Thanks for implementing it, I've added some notes in the pdf as usual. Probably some of them will be done in the next a+ sprint* 

Mobile:
[210511-m-interactive-event.pdf](https://github.com/liqd/adhocracy-plus/files/6501902/210511-m-interactive-event.pdf)

Desktop:
[210511-d-interactive-event.pdf](https://github.com/liqd/adhocracy-plus/files/6501901/210511-d-interactive-event.pdf)

**Comment by fuzzylogic2000** [comment]
Thank you! Could you say which of the points are important to fix before the release and/or to close the story?
I will add an extra issue for the footer to check if it looks like that everywhere and make sure, we don't release sth. that was better looking before.
