### ISSUE TITLE
mobile organisation footer looks off

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#1307]
**URL:** https://aplus-dev.liqd.net/liqd-tests/
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd It is the same on prod: https://adhocracy.plus/liqd/ (so maybe not for the next release). But the one after?! What should we do to make it look less off?

**Comment by fredewe** [comment]
@fuzzylogic2000 could you please add a screenshot?

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 Yeah, I already mentioned before actually, on zeplin's screens they are correct https://zpl.io/a8rQGPX

**Comment by fuzzylogic2000** [comment]
@fredewe I got it out from this issue https://github.com/liqd/adhocracy-plus/issues/1306. There is a screenshot, but I put it in an extra issue because the footer is everywhere and not only in the interactive event.
