### ISSUE TITLE
Progress Circle - Symbol 

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#134]
**URL:** https://adhocracy.plus/test/dashboard/modules/priorisierung-3/phases/
**user:** initiator 
**expected behaviour:** The symbol remains the same when I zoom in or out 
**behaviour:** The progress circle becomes two overlapping circles when I zoom in and out. 
**important screensize:** any 
**device & browser:** mac devices & safari
**Comment/Question:** does not happen in chrome or firefox 
![Bildschirmfoto 2019-12-05 um 14 11 26](https://user-images.githubusercontent.com/57798416/70242558-500d1780-1771-11ea-9e27-5c1c2907a931.png)

![Bildschirmfoto 2019-12-05 um 13 41 19](https://user-images.githubusercontent.com/57798416/70242546-484d7300-1771-11ea-9d29-d6430ad38330.png)

**Comment by fuzzylogic2000** [comment]
This will be gone with the change to the multi dashboard, so I will add low prio.
