### ISSUE TITLE
multi-module projects: project header image issues

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1374]
**URL:** https://adhocracy.plus/stadt-arnsberg/projects/smart-city-arnsberg-2030-nachhaltige-stadt-der-z-2/
**user:** all
**expected behaviour:** project header image remains the same for project page and module detail page
**behaviour:** the header image varies in height (see screenshots below)
**important screensize:**
**device & browser:** 
**Comment/Question:** I also checked it on other projects/organisations, and there it's the same, for e.g. here: https://adhocracy.plus/gemeinde-panketal/projects/neue-grundschule-elbestrasse/
Apparently, this occurs only in multi-module projects.

1) project page
![Bildschirmfoto 2021-07-26 um 13 51 22](https://user-images.githubusercontent.com/36957474/126984392-c745aac8-03a5-4c3e-a9a0-145d33beb458.png)

2) module detail view
![Bildschirmfoto 2021-07-26 um 13 51 32](https://user-images.githubusercontent.com/36957474/126984436-ab6fe087-7334-48f9-b094-3ee06e21c25e.png)

**Comment by sabinammm** [comment]
Just FYI: I haven't been able to reproduce this locally or on dev. And need admin rights on stage, so I can check it out there

**Comment by phillimorland** [comment]
already fixed with the BS update
