### ISSUE TITLE
adding modules to project and publish project: button not active after adding modules

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1425]
**URL:** https://aplus-dev.liqd.net/frede-test/dashboard/modules/brainstorming-50/phases/
**user:** initiator
**expected behaviour:** i would expect to be able to publish projects after adding a module and filling out everything
**behaviour:** the "publish" button is not active after adding a module. When i reload the page the module is not added anymore.
**important screensize:** all sizes
**device & browser:** macOS 11.4, Safari 14.1.1, Chrome Version 92.0.4515.159
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2021-09-07 um 15 15 40](https://user-images.githubusercontent.com/5470479/132351447-48ca291f-9f5b-4637-900f-fe0dfc6fe68e.png)

**Comment by phillimorland** [comment]
NOTE: safari issue, not replicable on FF or Chrome
