### ISSUE TITLE
#4687 new poll open question/other answer: long answer issue

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1447]
**URL:** https://aplus-dev.liqd.net/liqd-tests/projects/test-new-poll/
**user:** 
**expected behaviour:** a long answer can be read in full
**behaviour:** only parts of the answer can be read, the rest is cut off
**important screensize:** all
**device & browser:** all
**Comment/Question:** Maybe we can reduce the limit? (currently it's 750 characters). But apparently the issue occurs also with 500 characters (see screenshot below) and on mobile as well.
I checked it on mB and there it's working with 750 (https://meinberlin-dev.liqd.net/projekte/poll-umfrage/)

more than 700
![Bildschirmfoto 2021-09-22 um 16 33 09](https://user-images.githubusercontent.com/36957474/134364099-78b8551c-719a-4d9c-bf24-1ea862d4423d.png)

500 characters
![Bildschirmfoto 2021-09-22 um 16 36 29](https://user-images.githubusercontent.com/36957474/134364489-f55958cc-237c-47a0-976e-33e312b0934b.png)

"Other" answer
![Bildschirmfoto 2021-09-22 um 16 48 09](https://user-images.githubusercontent.com/36957474/134366492-cf90bd85-33fe-4024-8282-df8f33a5e856.png)

**Comment by phillimorland** [comment]
@lthueer we would expect normal user behaviour that the max length of a word would be less then 40charecturs, when testing strings longer then that this error is expected, if we add code that will break words at line end then we might end up breaking words unnecessarily, my preference is to not prioritise users who neglect the space-bar but, what are your thoughts?

**Comment by lthueer** [comment]
@phillimorland alright! there might be some extra long German words. Joking! I should have tested it with lorem ipsum and spaces though. Looks good then, closing this issue now.

**Comment by fuzzylogic2000** [comment]
For future reference: these are the longest German words: https://www.duden.de/sprachwissen/sprachratgeber/Die-langsten-Worter-im-Dudenkorpus
It's very unlikely that real people will use "Rinderkennzeichnungsfleischetikettierungsüberwachungsaufgabenübertragungsgesetz", though. And with the tenth longest word "Wochenstundenentlastungsbereinigungsverordnung" with 46 characters, I think we should already be fine!

**Comment by fuzzylogic2000** [comment]
Oh, I had to look up "Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch". That's in Wales. :)

**Comment by lthueer** [comment]
Wow, I didn't even know that words existed. Crazy Germans!
