### ISSUE TITLE
ap text review: Saved document still not finished after saving

### ISSUE THREAD

**Issue by sabinammm** [liqd/adhocracy-plus#1455]
**URL:** https://aplus-dev.liqd.net/frede-test/dashboard/modules/text-review-4/document/
**user:** *initiator*
**expected behaviour:** *When I save my document I expect the red sign in the sidebar to disappear*
**behaviour:** *When I save my document I have to manually reload the page to see that I filled out everything*
**important screensize:** *mobile? desktop?*
**device & browser:** *chrome*
**Comment/Question:** *This is exactly the same as issue https://github.com/liqd/adhocracy-plus/issues/1437 except with a different module* 

Screenshot?
![Reload_Issue](https://user-images.githubusercontent.com/17978375/134858366-a1689bcb-589c-4ab4-9965-fc66a837bd7a.png)

**Comment by sabinammm** [comment]
@fredewe do you want to put this into the Next release '21 milestone as well?

**Comment by fuzzylogic2000** [comment]
#1453 should have fixed this as well. Can you try again when the merge is deployed @sabinammm ?

**Comment by sabinammm** [comment]
Yes! It works now:)
