### ISSUE TITLE
JS import refactor

### ISSUE THREAD

**Issue by philli-m** [liqd/adhocracy-plus#1457]
Some JS packages have moved fully ESM and we need to refactor our imports for these packages.
Question is should we do this for all our packages?

see https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by fuzzylogic2000** [comment]
We changed quite a few things here already, right? Is this still an issue?

**Comment by philli-m** [comment]
Think we are good here now, it's possible there is still maybe some bits in a4 but can take a look and create separate issue if so
