### ISSUE TITLE
a+ Interactive event: Voting not working in safari 15.0

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1507]
**URL:** https://aplus-dev.liqd.net/frede-test/interactiveevents/interaktive-veranstaltung-23/
**user:** user
**expected behaviour:** voting works
**behaviour:** the voting is not working
**important screensize:**
**device & browser:** macOS Big Sur (11.6), Safari 15.0
**Comment/Question:** 
It works with older safari versions
Screenshot
![Bildschirmfoto 2021-10-14 um 16 55 10](https://user-images.githubusercontent.com/5470479/137343287-88c069e8-37f7-44ed-9f23-abde79dacecb.png)
?

**Comment by khamui** [comment]
@fredewe i checked with the same setup and can't replicate the issue.
As not-logged in visitor or Non-Admin and Non-Initiator i can vote in Safari 15.
As Admin/Initiator i cannot vote. This is the expected behavior right?

Maybe we can have a call to clarify/doublecheck?
