### ISSUE TITLE
a+: archiving projects not possible but filtering is

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1508]
**URL:** adhocracy.plus
**user:** initiator
**expected behaviour:** as it is possible in the dashboard to filter projects (archived or not) there should be a way to archive projects.
**behaviour:** There is just the filter but no way to archive projects on a+ like it is possible in mB.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot
![Bildschirmfoto 2021-10-14 um 17 01 02](https://user-images.githubusercontent.com/5470479/137344229-1af3fb70-05ff-4d11-9428-8aaa00f2013c.png)
?

**Comment by fuzzylogic2000** [comment]
Yes! Could you please write a story and close this issue? And please also put in it, that we 
1. then not show the archived projects on the organisation page by default
2. need to add a filter to the organisation page so that the archived projects can be found

**Comment by fuzzylogic2000** [comment]
Well, it is archivable: https://aplus-dev.liqd.net/liqd-tests/dashboard/projects/poll-test-finished/basic/ (last checkbox at the end of form)
It only appears after the project is finished. In the organisation project overview it vanishes from the list when archived. (You could add a story for a filter there is needed.)

**Comment by fredewe** [comment]
Thanks, @fuzzylogic2000 and sorry for confusion!
