### ISSUE TITLE
map file upload bug 

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1542]
**URL:** https://adhocracy.plus/test/dashboard/modules/brainstorming-mit-karte-107/area_settings/
**user:** initiators/admins
**expected behaviour:** upload is possible 
**behaviour:** it is not possible to upload any polygon files (.geojson / .zip)
**important screensize:** all
**device & browser:** all
**Comment/Question:** bug also occurs on dev

file upload not working with the correct file format
![Bildschirmfoto 2021-10-27 um 13 55 00](https://user-images.githubusercontent.com/36957474/139060875-67f61273-8b4b-4117-a002-72f9f744538d.png)

**Comment by phillimorland** [comment]
`Import error:  TypeError: t(...).modal is not a function
    at e._addToMap (map_choose_polygon_with_preset.js:169)
    at FileReader.s.onload (map_choose_polygon_with_preset.js:156)
map_choose_polygon_with_preset.js:132` 
`Uncaught TypeError: (0 , a.shp) is not a function
    at FileReader.n.onload (map_choose_polygon_with_preset.js:132)`

**Comment by lthueer** [comment]
@CarolingerSeilchenspringer  I tested this on mB dev and there .geojson works but .zip doesnot. Maybe you can write it on your list and/or test it again?

**Comment by CarolingerSeilchenspringer** [comment]
@lthueer thanks, will add this to mB issue/ test again.

**Comment by phillimorland** [comment]
@lthueer do you know when this broke? i've set it up so it's using same code as mB but it's still broken so it's likely an update which would be easier to check if we had rough time scale?

**Comment by lthueer** [comment]
@phillimorland I think I discovered it on 25th October if that helps. But it could have been there longer. We had one release the week after and then another one on 16th November.

**Comment by phillimorland** [comment]
cool, updates before October then, easy ;) cheers!

**Comment by fuzzylogic2000** [comment]
@phillimorland What did we do about that on mB? Did we do sth. about it?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 here is the closed issue from mB: https://github.com/liqd/a4-meinberlin/issues/3970

**Comment by phillimorland** [comment]
git bisect suggesting it was most likely bootstrap update, although difficult to test as the commits just after it don't work as it needed a few commits before everything was working but here is findings: 
good commit: 17/08 chore(deps): update dependency @babel/runtime to v7.15.3
bad commit: 02/09 replace l-* with cols
