### ISSUE TITLE
media embed URL not working (interactive event, info & result tab)

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1546]
**URL:** https://aplus-dev.liqd.net/testnewdjango/dashboard/modules/interaktive-veranstaltung-24/media/
**user:** initiators/admins
**expected behaviour:** url embed works
**behaviour:** error message
**important screensize:** 
**device & browser:** safari 15.0, Firefox 93.0, Chrome
**Comment/Question:** for vimeo and youtube

![Bildschirmfoto 2021-10-28 um 13 52 55](https://user-images.githubusercontent.com/36957474/139250547-db991106-7026-424c-9b67-50e6d0ad373c.png)

**Comment by fuzzylogic2000** [comment]
So, this is only on dev, right? (That means we can fix it later. :))

**Comment by lthueer** [comment]
@fuzzylogic2000 yes, exactly!

**Comment by phillimorland** [comment]
@lthueer can you take a look at this and try retesting? https://github.com/liqd/a4-meinberlin/issues/4071#issuecomment-998099983

**Comment by fuzzylogic2000** [comment]
No, not yet working.

**Comment by fuzzylogic2000** [comment]
Done!
