### ISSUE TITLE
map area can be moved (also by user)

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1548]
**URL:** https://aplus-dev.liqd.net/testnewdjango/budgeting/create/module/burgerhaushalt-3/
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** issue also on prod

![Bildschirmfoto 2021-10-28 um 15 09 00](https://user-images.githubusercontent.com/36957474/139261903-b600149a-7c00-4adc-be7a-989c355076c9.png)

**Comment by fuzzylogic2000** [comment]
@phillimorland This was fixed by #1563, right?
Do we also need #1565 ?
