### ISSUE TITLE
map zooming in on project page not working 

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1552]
**URL:** https://adhocracy.plus/werder-havel/projects/zukunftshaushalt/
**user:** 
**expected behaviour:** zooming in works
**behaviour:** zooming in is not working
**important screensize:**
**device & browser:** 
**Comment/Question:** 
on prod, stage, dev

Apparently, when you add an idea, the zooming works fine

**Comment by lthueer** [comment]
This issue is still there, zooming in only works if you click on the ideas on the map

**Comment by fuzzylogic2000** [comment]
Where is the issue? On dev? Or on stage? We did already try to fix it on dev, but it is not yet on stage or prod...

**Comment by lthueer** [comment]
@fuzzylogic2000 you're right, sorry! It's fixed on dev. My bad!
