### ISSUE TITLE
Brainstorming + map filter categories issue

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1553]
**URL:** https://adhocracy.plus/test/projects/module/brainstorming-mit-karte-107/?ordering=-created&category=1660
**user:** 
**expected behaviour:** filter is shown correctly
**behaviour:** when category filter is selected the filter design breaks
**important screensize:** all
**device & browser:** all
**Comment/Question:** for normal Brainstorming it works | on prod, stage, dev

![Bildschirmfoto 2021-11-01 um 17 50 10](https://user-images.githubusercontent.com/36957474/139709571-eecffaf7-64ee-4d2a-b2d5-278909bdbf26.png)

**Comment by phillimorland** [comment]
@lthueer seems to be issue with select image, I can't remember if we had it in there before?! would you be ok with implementation from mB, image is shown in options but not once selected or do you want to always see image?
https://meinberlin-dev.liqd.net/projekte/map-test/?ordering=-created&category=247

**Comment by lthueer** [comment]
@phillimorland yes, that would work. Thank you!
