### ISSUE TITLE
a+ three dot menu for proposals has layering issue 

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1554]
**URL:** https://aplus-stage.liqd.net/fredetest/budgeting/2021-00350/
**user:** Initiator
**expected behaviour:** Menu is at the right place and not overlapped by buttons
**behaviour:** menu looks a bit off
**important screensize:**
**device & browser:** MacOS 11.6, Safari and Chrome (newest versions)
**Comment/Question:** 

Screenshot
![Bildschirmfoto 2021-11-01 um 17 50 46](https://user-images.githubusercontent.com/5470479/139709802-235a7659-7df5-4559-b1be-21eec6aa6c99.png)
?

**Comment by fuzzylogic2000** [comment]
@fredewe Is that also the case on dev?

**Comment by fredewe** [comment]
Yes, it is also on Dev: https://aplus-dev.liqd.net/frede-test/budgeting/2022-00490/

**Comment by phillimorland** [comment]
@fredewe is this still broken for you? I cannot reproduce

**Comment by lthueer** [comment]
@phillimorland for me the issue is still there (tested in ff). When you click the three dots and scroll down to the edge of the opened menu it changes the layout. When the dots are at the bottom of a page, they open in a strange way

**Comment by fredewe** [comment]
Yes. It is still there. Still in Chrome and Safari.

**Comment by lthueer** [comment]
@phillimorland For me in ff it's the same on dev. If you click the three dots when they are located at the bottom of the page, the layout breaks.
https://aplus-dev.liqd.net/teststadt-luca/mapideas/2022-00502/
