### ISSUE TITLE
a+ map module: sometimes polygon is saved at a wrong place

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1556]
**URL:** Stage, Prod, Dev
**user:** initiator
**expected behaviour:** the polygon is saved where i draw it in the map
**behaviour:** the polygon sometimes jumps somewhere else when i save it
**important screensize:**
**device & browser:** all
**Comment/Question:** 
Maybe this happens if I move the map beforehand and then draw in the polygon
Screenshot?

Before saving:
![Bildschirmfoto 2021-11-01 um 20 14 21](https://user-images.githubusercontent.com/5470479/139728559-548c3d0b-9666-4e74-b9f3-e023b16ebd47.png)

After saving:
![Bildschirmfoto 2021-11-01 um 20 14 28](https://user-images.githubusercontent.com/5470479/139728562-f7af894a-9c69-4b03-8001-f4272952275c.png)

**Comment by phillimorland** [comment]
@fredewe I cannot reproduce this error, i've tried moving map before saving, moving map after saving, different zooms, on idea and brainstorm, polygone and rechtangle, i'm not sure what else to try, is this a consistent issue for you? @lthueer have you ever experienced this issue?

**Comment by fredewe** [comment]
Would close the issue. I think it was fixed with the last map fixes.
