### ISSUE TITLE
Dashboard – Organization's Projects View

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#1582]
**URL:** https://adhocracy.plus/liqd/dashboard/organisations/projects/
**user:** *Initiator*
**important screensize:** *Desktop*
**device & browser:** *Version 15.0 (16612.1.29.41.4, 16612)*
**Comment/Question:** *I always see this when I open aplus but we have never had a sprint that had anything to do with this part of the platform, so I never mentioned about that here before. 

Whenever a project has a very long title, the buttons for View and Edit end up at the bottom. Is there any way to fix this? I think placing a limit on the column like this red line and placing the tags underneath the title would fix it.* 

![Screenshot 2021-11-16 at 13 20 29](https://user-images.githubusercontent.com/59610786/141985514-6db565bf-268a-41b2-9b7f-d79f86e51998.png)

**Comment by fuzzylogic2000** [comment]
Yeah, hmm, I think that is hard when the text on the buttons is long, because we don't know how many columns we'll need then. And then if the title of the project also gets the longest it can, it can look really really bad. But maybe @phillimorland knows some wizardry!

**Comment by phillimorland** [comment]
ooo right, for the other languages, hmmm should be able to do something with flexbox to solve it, will take a look
