### ISSUE TITLE
a+ voting arrows on Windows 10 broken?

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1584]
**URL:** https://adhocracy.plus/obenandervolme/topicprio/2021-06548/
**user:** user
**expected behaviour:** voting arrows look normal
**behaviour:** voting arrows look a bit broken
**important screensize:**-
**device & browser:** Windows 10 Home, Firefox 94.0.1 (64-Bit)
**Comment/Question:** 
This bug was reported from a user. I could not reproduce it on my computer. Any ideas?

Screenshot from User (actually not a real screenshot):
![20211117_102841](https://user-images.githubusercontent.com/5470479/142206962-7b210c93-6e41-4864-843f-977d7d1bd349.jpg)

**Comment by phillimorland** [comment]
might be

**Comment by fredewe** [comment]
@phillimorland can we close this one as it is not our bug?

**Comment by goapunk** [comment]
@phillimorland we have a test computer, yes

**Comment by fuzzylogic2000** [comment]
@philli-m @goapunk Did we test this?
@lthueer Do you know if this happened again?

**Comment by goapunk** [comment]
no idea, however testing should be easy enough with browserstack?

**Comment by lthueer** [comment]
@fuzzylogic2000 @goapunk @philli-m I can't reproduce this problem even with Browserstack. Seems to work with all browsers on Windows 10, so close this issue
