### ISSUE TITLE
iframe jumping issue

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1594]
**URL:** https://aplus-dev.liqd.net/info/use-cases/entwickelt-euer-leitbild-zusammen/
**user:** 
**expected behaviour:** it doesnot jump to the iframe but starts from top of the page
**behaviour:** focus jumps to the iframe when page is opened
**important screensize:**
**device & browser:** firefox/chrome
**Comment/Question:** this issue apparently is not there in safari

**Comment by fuzzylogic2000** [comment]
This is an example and like that on all sites using the embed.

Decision: we will only fix it if it is a fast fix.

**Comment by phillimorland** [comment]
@fuzzylogic2000 @lthueer is it ok to close this? I haven't figured out why its doing it and it looks like it'll be gone soon anyway?
