### ISSUE TITLE
Missing error messages for missing title in create & edit idea forms

### ISSUE THREAD

**Issue by sabinammm** [liqd/adhocracy-plus#1596]
**URL:** https://aplus-dev.liqd.net/sabina-test/mapideas/create/module/brainstorming-mit-karte-15/
**user:** any user who wants to create or edit an **idea** or a **map idea**
**expected behaviour:** If I forget to add a title or delete it when editing my idea, I get an error message
**behaviour:** The form doesn't save if I forget or delete the title and also jumps back up to the missing field value. But there is no error message explaining the problem.
**important screensize:** any
**device & browser:** ubuntu, chrome, there is a (browser) error message for firefox, but it's not consistent with the other error messages.
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
Like mB: let's close for now and come back to it if it ever becomes important!
