### ISSUE TITLE
Missing error messages at the top of the page for missing description in create & edit idea forms

### ISSUE THREAD

**Issue by sabinammm** [liqd/adhocracy-plus#1597]
**URL:** https://aplus-dev.liqd.net/sabina-test/mapideas/create/module/brainstorming-mit-karte-15/
**user:** any user who creates or edits and idea and leaves the description field empty or empties it when editing.
**expected behaviour:** I get an error message on the top of the page calling attention to an error actually occurring lower on the page
**behaviour:** There is only an error message at the bottom of the page.
**important screensize:** any
**device & browser:** ubuntu chrome
**Comment/Question:** @fredewe  should this be the same as in other forms with an additional error message at the top?

Screenshot?
**How it is:**
![image](https://user-images.githubusercontent.com/17978375/143579295-1c32d843-8fc8-4f76-886e-5baa75b6ef8a.png)

**Should it be like this?**
![image](https://user-images.githubusercontent.com/17978375/143579343-845661ab-6703-4554-acc6-a3ce87a1cadc.png)

**Comment by fuzzylogic2000** [comment]
In a+ we only have them in the dashboard. But as @sabinammm just added them to the dashboard and the idea forms in mB, she knows how to do that. :) So, would you like to also have them in the idea forms @fredewe @lthueer ?

**Comment by fredewe** [comment]
That would be really nice but it has no high priority for me! How elaborate would the implementation be? What do you think @lthueer ?

**Comment by lthueer** [comment]
I agree! It would be nice to have

**Comment by fuzzylogic2000** [comment]
@sabinammm So, I think, it would be great if you could also add it here!

**Comment by sabinammm** [comment]
@fuzzylogic2000 I will also add this for the budget proposal module forms and the topic priorisation (admin dashboard entry and edit form)
