### ISSUE TITLE
SAML login can't be aborted if final registration step is not completed

### ISSUE THREAD

**Issue by goapunk** [liqd/adhocracy-plus#1610]
**URL:** diid-dev 
**user:** saml test user 
**expected behaviour:** If final registration step was skipped (e.g. by closing the browser window, or going back to the main site), the user is shown as logged in and clicking on logout will actually log them out
**behaviour:** Pressing logout won't log the user out and they have to complete the registration. Logging in with another account is impossible without clearing the browser cache if registration is not completed.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
I guess that is something we should fix for the DIID release! Will add a milestone!

**Comment by fuzzylogic2000** [comment]
moved to diid-repo: https://github.com/liqd/diid_adplus/issues/6 as problem specifix to saml-overwrite
