### ISSUE TITLE
footer link issue in Kyrgyz and Russian

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1611]
**URL:** https://adhocracy.plus/
**user:** all
**expected behaviour:** on mobile & web all footer links are visible and can be clicked in all languages. The cookie banner doesnot hide them.
**behaviour:** on mobile & desktop (for Russian and Kyrgyz only) the last link(s) disappear behind the donations banner and can't be clicked.
**important screensize:**
**device & browser:** mobile + desktop
**Comment/Question:* 
- Is it possible to change the styling that there are two footer lines? Changing the wording of the donation banner probably is not enough as words in Kyrgyz and Russian are verryyyyyyyy loooooong
- Other option: make wording for cookie banner (when RU, KY selected) english so that it's shorter?

![Bildschirmfoto 2021-12-20 um 14 24 07](https://user-images.githubusercontent.com/36957474/146775136-e9e10cab-d9aa-4fc0-9927-038aa51db01c.png)

<img width="1412" alt="Bildschirmfoto 2021-12-22 um 09 32 54" src="https://user-images.githubusercontent.com/36957474/147061645-831138d3-6a1a-4b5d-b2d2-349bb5f94c29.png">

**Comment by fuzzylogic2000** [comment]
I think this is an annoying one! We cannot do a lot about it as the stuff below the donation banner cannot know how the size of the donation banner changes.
So yes, maybe the English-option is good?! (You'd have to change that in transifex.) Or we don't disable the donation banner for the russion and kyrgyz orgas? But that only works on the pages of that org. 
Or @phillimorland has a good idea?

**Comment by phillimorland** [comment]
@fuzzylogic2000 @lthueer we can just increase the existing spacing for when banner is there, just checking it quickly in browser it shouldn't make other languages look weird, will just have little more space, what you think?

**Comment by fuzzylogic2000** [comment]
> @fuzzylogic2000 @lthueer we can just increase the existing spacing for when banner is there, just checking it quickly in browser it shouldn't make other languages look weird, will just have little more space, what you think?

@phillimorland Ah, yes! Cool!

**Comment by lthueer** [comment]
@phillimorland sounds good to me! As long as all of the links in the footer are clickable , I'm fine.
