### ISSUE TITLE
debate list: list tile is clicked when dropdown ordeing filter clicked

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#1622]
**URL:** https://aplus-dev.liqd.net/liqd-tests/projects/test-the-debate/
**user:** 
**expected behaviour:** 
**behaviour:** When I try to order by "most comments", instead of choosing the filter in the dropdown, the debate subject tile is clicked and I am taken to the detail page.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by Rineee** [comment]
Also on the subject detail page the filter is broken https://aplus-dev.liqd.net/liqd-tests/subjects/2022-00487/
