### ISSUE TITLE
user dropdown too small for longer orgas

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#1642]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

![Screenshot from 2022-01-12 07-54-21](https://user-images.githubusercontent.com/8178179/149078707-1c7d82cc-aa12-4563-a241-02d5f25fad5b.png)

**Comment by phillimorland** [comment]
@fuzzylogic2000 is this new since BS update?

**Comment by fuzzylogic2000** [comment]
@phillimorland It might be even newer, I have never noticed before this morning. And it is still fine on stage.
