### ISSUE TITLE
Social login: Twitter not working

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1654]
https://aplus-dev.liqd.net/accounts/twitter/login/?process=login&next=%2F

<img width="845" alt="Bildschirmfoto 2022-01-17 um 14 30 36" src="https://user-images.githubusercontent.com/36957474/149777915-0a6f7ffd-d78a-43a7-a6ae-c20f8d65f214.png">

Note: also not for redirects. If this has something to do with (missing) social login settings on dev, please close this issue.

**Comment by fuzzylogic2000** [comment]
For github, it works on dev, but not the redirect hafencity-dev.

**Comment by phillimorland** [comment]
@fredewe should all be good on dev and prod, note that social logins are not all set up on stage sites though.
