### ISSUE TITLE
Django admin: Not possible to create about page via django admin 

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1656]
**URL:** https://aplus-dev.liqd.net/django-admin/a4_candy_organisations/organisation/add/
**user:** initiator
**expected behaviour:** it is possible to create an about page via django admin
**behaviour:** the text field for about page is not active
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2022-01-17 um 10 53 29](https://user-images.githubusercontent.com/5470479/149748017-71a3ae93-48af-42d7-b2f1-a3ffa87ea86b.png)

**Comment by fuzzylogic2000** [comment]
This is also a problem for the other CK editor fields where we have the collapsible thingy. So, also for projects or interactive events.
We will add a down-sized version of the CK editor here, without our own video or collapsible fields.
