### ISSUE TITLE
Brainstorming (+map) Filter missing string for translations (all languages)

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1659]
https://aplus-dev.liqd.net/hafencity-hamburg-gmbh/projects/module/ideenwettbewerb-mit-karte-8/?mode=list&ordering=-positive_rating_count&category=161

Missing: Ordering

![Bildschirmfoto 2022-01-17 um 17 39 38](https://user-images.githubusercontent.com/36957474/149808403-5c6d3cba-f688-4de4-aeaa-c45fdc22b391.png)

**Comment by fuzzylogic2000** [comment]
This is a mystery. It comes from a4 (https://github.com/liqd/adhocracy4/blob/803c4c3b0ae83007cdc7c1971348e78abe92a3d1/adhocracy4/filters/widgets.py#L66), it works in mB, it is in the translation files and is translated (https://github.com/liqd/adhocracy-plus/blob/7da29d1add77faaca33504bae451cd5e3c50a1f0/locale-source/locale/de/LC_MESSAGES/django.po#L709) and overwriting the widget just with the label works.
