### ISSUE TITLE
debate module: filter styling issue

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1665]
**URL:** https://aplus-dev.liqd.net/hafencity-hamburg-gmbh/subjects/2022-00516/
**user:** all
**expected behaviour:** filter elements are aligned
**behaviour:** filter looks off
**important screensize:**
**device & browser:** Mac OS Monterey: Firefox 96.0.1; Chrom 97.0.4692.71; Safari 15.2
**Comment/Question:

<img width="1129" alt="Bildschirmfoto 2022-01-18 um 11 57 53" src="https://user-images.githubusercontent.com/36957474/149924655-b0d6437f-d431-4d7e-b9e2-3e0ac0b6a7e3.png">

**Comment by phillimorland** [comment]
@lthueer can't replicate, can you check all browsers and add problem ones to issue please, same goes for any styling issue, browsers and OS's differer alot with processing of some css so it's useful to know where I have to look. Cheers!

**Comment by lthueer** [comment]
@phillimorland they are in the description now! To me it happens on all browsers I have on my computer

**Comment by phillimorland** [comment]
@lthueer thank you! :)
