### ISSUE TITLE
a+ text commenting: text moves out of frame when no blank spaces

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1669]
**URL:** https://aplus-dev.liqd.net/test-january-22/projects/module/text-diskutieren-4/
**user:** 
**expected behaviour:** the text stays in frame
**behaviour:** text without spaces moves out of frame
**important screensize:**
**device & browser:** 
**Comment/Question:** 
Don't know if this is an old one or if it is relevant at all.

Screenshot?
![Bildschirmfoto 2022-01-18 um 20 40 16](https://user-images.githubusercontent.com/5470479/150007462-0f24f710-8077-4630-98ec-3be995fb636f.png)

**Comment by phillimorland** [comment]
it's old and an edge case give that users should really be using spaces so will remove from milestone

**Comment by fredewe** [comment]
Fine for me! :)
