### ISSUE TITLE
ck editor image upload still possible

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#1717]
**URL:** https://aplus-stage.liqd.net/liqd/dashboard/projects/sadf-2/information/
**user:** initiator/admin
**expected behaviour:** external image server url cannot be embedded
**behaviour:** external image can be embedde by using the media embed in ck editor
**important screensize:**
**device & browser:** 
**Comment/Question:** 

see information tab, where an image by vodafone was embedded succesfully. For uploading images from liqd servers (e.g. liqd.net) is also still possible

**Comment by fuzzylogic2000** [comment]
But the videos will always be external, so there is no way to forbid external content here, I think? Unless @phillimorland or @goapunk have an idea on how to do that and only allow youtube and vimeo external embed urls (or are there more?).

**Comment by phillimorland** [comment]
@fuzzylogic2000 @lthueer we already do only allow it on mB (https://github.com/liqd/admin/blob/50d7d125b3910e225357c65e4b652eda9600791c/pillar/servers/berlin-adhocracy4-prod.sls#L41) as part of CSP but I don't think we actually implemeneted that on aplus yet as we wanted to do the image stuff first, theres nothing we can do about this untill we implement it I don't think

**Comment by lthueer** [comment]
@phillimorland @fuzzylogic2000 alright, then let's do it later when we implement the CSP. Closing this issue and taking it to the a+ backlog

**Comment by phillimorland** [comment]
@lthueer it'll happen automatically, no link will be save from a different url, however we should maybe look to adding an error message, that could go in the backlog?

**Comment by lthueer** [comment]
@phillimorland cool, I've added it to the backlog
