### ISSUE TITLE
make project slug editable in django-admin

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#1726]
We made the project slug editable in a4. (That is the string with small small letters and dashes that is in the url. Like `public-poll` for https://aplus-dev.liqd.net/liqd-tests/projects/public-poll/). 
Should we also make that editable in a+? @lthueer @fredewe 
(That would mean that the slug is still automatically filled when a project is added in the dashboard. But that is sometimes weird. For example if you copy a project the old slug just gets a -2 at the end. If we would make it editable in the django-admin you could change that yourself @lthueer @fredewe )

**Comment by fredewe** [comment]
I think it would be nice to have it editable in a+.
