### ISSUE TITLE
Use Weblate for translations

### ISSUE THREAD

**Issue by comradekingu** [liqd/adhocracy-plus#1742]
In the interest of "digital democracy easy for everyone", the non-free and privacy-invasive Transifex is a bad tool best avoided.
It requires contributors be 18 or above to accept its egregious terms, and spies on the user.

**URL:** https://hosted.weblate.org/hosting/
**user:** All translators
Unfortunately the good options are summed up in one, but that makes Weblate an easy choice.
There are plenty of instances, like https://weblate.bubu1.eu/

**Comment by fuzzylogic2000** [comment]
Thanks for your suggestion! As our translators are currently all on Transifex, we will stay with that, though. We will consider weblate if we start another project that needs translations.
