### ISSUE TITLE
Home page background colour inconsistent and odd padding

### ISSUE THREAD

**Issue by philli-m** [liqd/adhocracy-plus#1760]
**URL:** https://aplus-dev.liqd.net/ https://adhocracy.plus/
**expected behaviour:** there is consistent design concerning the background colour 
**behaviour:** background colour is sometimes grey and sometimes white, depending on the blocks however due to spacing and padding it looks like broken design

@mcastro-lqd do you a preference here? would it make sense to just have 1 background colour, either the white or the light grey?

Screenshot?

**Comment by philli-m** [comment]
@mcastro-lqd @lthueer this is kind of a design question, we built the homepage to work with a specific content block order which used to work with the different background colours but as we don't use all those blocks and have changed the order it no longer looks consistent but i'm not sure on what the fix should be?

**Comment by mcastro-lqd** [comment]
To be honest I don't see that as too bad, Id just avoid divisions like that, but I think it's fine to have a white background element and a light grey one. 

<img width="979" alt="Screenshot 2023-07-20 at 16 50 56" src="https://github.com/liqd/adhocracy-plus/assets/59610786/3c69b9af-ffc5-46fd-a322-cfd17627910f">
