### ISSUE TITLE
project tile: indicate private projects for users

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#178]
**URL:** any organisation page, e.g. https://adhocracy.plus/liqd/
**user:** user logged in and taking part in private project
**expected behaviour:** on the project list on organisation page I can see which of the projects is private and which isn't
**behaviour:** private project is shown but not displayed as such, eg. with a little symbol
**important screensize:**
**device & browser:** mac, safari
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
@phillimorland @hmkay @fredewe So, this issue is already here! To fix it would also greatly help to test the organisation members. Could we please do it? Maybe first just like in mB and then @mcastro-lqd can say if that's fine?!

**Comment by hmkay** [comment]
@fuzzylogic2000 @phillimorland Let´s do it!
Well, you probably already do it...
