### ISSUE TITLE
Idea remark broken

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#1843]
https://aplus-dev.liqd.net/phillitopictest-org/ideas/2022-00604/
~~idea remark will not save~~
**behaviour:** moderator remark appears not to save when clicking save, box does not close, green tick does not appear, user must refresh the page in order to check if it is saved and see the green tick
**expected behaviour:** on clicking save the moderator remark box closes and a green tick appears on the button, no page refresh needed 

Screenshot?

**Comment by fredewe** [comment]
@phillimorland do you mean the moderator note?

**Comment by phillimorland** [comment]
@fredewe not sure what the moderator not is, I thought we only have moderator feedback and idea or moderator remark? this is what is called the moderator remark: 
and it does save apparently but we need to do a page refresh which shouldn't happen, also remark box should close on clicking save, will update issue.
![screenshot(30)](https://user-images.githubusercontent.com/5871230/172832793-7c43eae1-747f-482e-a118-ad6e8d6af488.png)

**Comment by fredewe** [comment]
Thanks @phillimorland - that is what i meant with moderator note. I add this issue to the milestone!
