### ISSUE TITLE
#6011 adapt wording in notification of user in case of blocked comment

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#1863]
**URL:** Email
**Comment/Question:**Maybe you have already discussed that with Mkay or Ricardo.

Maybe the comment is being taken from when the comment is not expanded, but since users won't be able to see their comment in the discussion, in case of longer comments, wouldn't it make more sense to leave the whole comment instead of just a small part of it? 
If that's a technical thing, please just ignore this issue. Thanks!** 
![Screenshot-2022-05-24-at-08 40 05](https://user-images.githubusercontent.com/59610786/169966815-7f8309d1-e16a-43ce-a099-56fa8ad2e9e8.jpg)

**Comment by Rineee** [comment]
Moved this to KOSMO https://github.com/liqd/a4-kosmo/issues/339
