### ISSUE TITLE
a+ | revoking terms of use in Django admin: not possible to search users (Safari)

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1878]
**URL:** https://aplus-dev.liqd.net/django-admin/a4_candy_organisations/organisationtermsofuse/
**user:** admin
**expected behaviour:** as an admin i would like to have an overview of all initiators of the organisation and select the one i want to revoke the terms of use
**behaviour:** only one of many initiators is preselected. It is not possible to easily change the user because the search does not work (Safari).
**important screensize:**
**device & browser:** MacOS 12.3, Safari 15.4
**Comment/Question:** 

Screenshot?

![Bildschirmfoto 2022-05-31 um 08 46 53](https://user-images.githubusercontent.com/5470479/171113424-434a90da-aa55-4aef-aae2-4bf43fa50a00.png)

![Bildschirmfoto 2022-05-31 um 08 47 07](https://user-images.githubusercontent.com/5470479/171113444-f7b56530-469d-429e-ae3d-e1509b82c21f.png)

**Comment by Rineee** [comment]
I am not quite sure if I got that @fredewe :) So the [organisation terms of use entries]( https://aplus-dev.liqd.net/django-admin/a4_candy_organisations/organisationtermsofuse/) list pairs of organisation/user, if you click on it, you can revoke that particular agreement of that user to the organistaion by unchecking the 'has agreed'.

Do you maybe want a filter for organisations like it is for [projects](https://aplus-dev.liqd.net/django-admin/a4projects/project)?
