### ISSUE TITLE
Moderators are not allowed to set comment to recommended

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#188]
**URL:** 
**user:** Moderator
**expected behaviour:** In an debate of an debate module when I click the button recommend and post the form the comment is marked recommended afterwards
**behaviour:** In an debate of an debate module when I click the button recommend and post the form the comment is not marked recommended afterwards (in the developer console I can see that the post returned a not allowed error)
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
We don't have recommended currently so closing
