### ISSUE TITLE
Admin can begin participation before start date

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#190]
**URL:** https://aplus-dev.liqd.net/phillitopictest-org/projects/end-soon/
**user:** admin
**expected behaviour:** no one should be able to participate before the start date 
**behaviour:** as an admin i can articipate before project begins
**important screensize:** all
**device & browser:** all
**Comment/Question:** for users its fine but you can see the admin participation and can comment

Screenshot?

**Comment by fuzzylogic2000** [comment]
This is the expected behaviour. Admins are allowed to do anything anytime. All other users in all other roles (also initiators) are not allowed to do this. But maybe we hid the button to participate in the versions before? Let's check (on stage)!

**Comment by fuzzylogic2000** [comment]
Yes, it's meant and should be like that!
