### ISSUE TITLE
Comments in poll styling

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#191]
**URL:** https://aplus-dev.liqd.net/teststadt/projects/test-ending-soon/
**user:** all
**expected behaviour:** comments can be easily identified, buttons have same/similar styling
**behaviour:** comments have blue background, don't seem very clear, rating btns are transparent and other btns are white
**important screensize:** all
**device & browser:** all
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
changing comments anyway?

**Comment by fuzzylogic2000** [comment]
@phillimorland Can we close this? Looks fine to me with the changed comments!
