### ISSUE TITLE
a+ | #5990 [a+] Contribute to Organisations: user account settings: accepting behaviour

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1927]
**URL:** https://aplus-dev.liqd.net/buro-fur-vielfalt/projects/umfrage-3/
**user:** registered user
**expected behaviour:** when i revoke and reaccept the terms of use in my account settings i can comment the poll and it stays like that. When i revoked it is not possible to create content, also not in older tabs.
**behaviour:** when i revoke and reaccept the terms of use in my account settings i can comment the poll and after my comment i have to accept the terms of use again for writing a new comment even though my account settings say that i accepted the terms of use. After reload it works again. Also when i have two tabs open, one with the account settings and one with the poll, i can revoke the terms of use and still comment in the other open tab without getting rejected.
**important screensize:**
**device & browser:** MacOS 12.3, Safari 15.4
**Comment/Question:** 
I tried to record it so you can better understand what i mean.
Screenshot?

https://user-images.githubusercontent.com/5470479/174111286-68496c26-6cf6-42a7-8ee4-95d093f1ec53.mov

**Comment by phillimorland** [comment]
should be fixed with https://github.com/liqd/adhocracy4/pull/1119

**Comment by fuzzylogic2000** [comment]
yes, was fixed in a4
