### ISSUE TITLE
a+ Contribute to organisations (react) #5988: Missing translation

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#1940]
**URL:** https://aplus-dev.liqd.net/frede-test/ideas/create/module/brainstorming-68/
**user:** 
**expected behaviour:** 
**behaviour:** There is a translation missing for the Checkbox. 
**important screensize:**
**device & browser:** 
**Comment/Question:** 
If you need a translation, let me know!
Screenshot?
![Bildschirmfoto 2022-06-23 um 17 55 11](https://user-images.githubusercontent.com/5470479/175342971-f0cd0de2-14a8-462f-825f-42f7fbd23994.png)

**Comment by fuzzylogic2000** [comment]
Translations are done in transifex, not during story.
