### ISSUE TITLE
Sorting in Brainstorming wider than page

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#1981]
**URL:** https://adhocracy.plus/musterorganisation/projects/module/brainstorming-31/
**user:** any
**expected behaviour:** 
**behaviour:** the filter/sorting are wider than the page
**important screensize:** below 500 width
**device & browser:** seen on iphone 12, not tested other
**Comment/Question:** 

Screenshot?
![Unser Großevent (Brainstorming, Priorisierung) — adhocracy+Musterorganisation](https://user-images.githubusercontent.com/35491681/161011952-92496bbe-a917-4d11-86a3-ded850085c88.jpeg)

**Comment by lthueer** [comment]
It's working!
