### ISSUE TITLE
a+logo not well visible in night modus

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#202]
**URL:** mail notification
**user:** anyone receiving mail notifications
**expected behaviour:** logo is well visible
**behaviour:** logo is black on dark grey
**important screensize:**
**device & browser:** iphone 7, Safari, night modus
**Comment/Question:** 

Screenshot? 
![Beteiligung endet bald für Test1](https://user-images.githubusercontent.com/35491681/71809608-b89d2c00-3070-11ea-99ee-e33f0c4ddef7.png)

**Comment by fuzzylogic2000** [comment]
We could put in a logo with a white background for the emails, that would work in both cases?!

**Comment by CarolingerSeilchenspringer** [comment]
yes, I guess that would be the best solution.

**Comment by phillimorland** [comment]
@fuzzylogic2000 there's also this, might not need it this time but good to keep in mind for other projects https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
