### ISSUE TITLE
#2399 timeline cuts off too early

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#21]
The timeline inside the embedded iframe cuts off relatively far from the iframe boundaries. This might be an issue with the normal layout at around 600px screen width too. 

![Bildschirmfoto 2019-11-04 um 18 56 39](https://user-images.githubusercontent.com/15341015/68145310-ced62100-ff35-11e9-9dd3-9e855590ddfe.png)

**Comment by fuzzylogic2000** [comment]
The timeline cuts off at the container width on all sizes. This is not an embed problem. We don't know how to quickly change that. How important is it?

**Comment by rittermo** [comment]
Yes, I know that it is normally also cut off. It seems then that the container is too small on certain screen sizes. This is not very important to fix but I would add it to a milestone before launch

**Comment by fuzzylogic2000** [comment]
What do we do about this? As @phillimorland said there seems to be no easy fix as this is a bootstrap-thing.

**Comment by rittermo** [comment]
We wanted to postpone this for a future improvement / issue fixing.
