### ISSUE TITLE
#2504: title, content image and excerpt not displayed on twitter

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#210]
**URL:** https://aplus-dev.liqd.net/info/use-cases/l%C3%A4rmaktionsplan/
**user:** all
**expected behaviour:** preview is enabled
**behaviour:** only the link is displayed; counts also for other links from a+ dev
**important screensize:** all
**device & browser:** all
**Comment/Question:** 

Screenshot?
<img width="1276" alt="Bildschirmfoto 2020-01-13 um 13 40 47" src="https://user-images.githubusercontent.com/36957474/72257962-2d420e80-360d-11ea-8c6a-0b4f7e45585e.png">

**Comment by MagdaN** [comment]
@rmader I just tested this, I think this does not work because of the robot.txt on the dev server. I checked with the twitter documentation and this should work.

**Comment by rmader** [comment]
Yep that would make sense. But why would we *ever* want to post something from our dev server on twitter?

**Comment by rmader** [comment]
Ah right, lets deploy it on prod.
