### ISSUE TITLE
styling issues from updates

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#2103]
~~- [ ] "Save"-button in dashboard is not wide enough~~ (same on stage)
~~- [ ] blue of dashboard publish progress line seems to be wrong~~ (same on stage)
- [x] donation banner on LIQD (wagtail)-pages does not have background colour and disappers from time to time (depending on background of pages)
- [x] jsx errorlist text black not white
- [x] text commenting (documents) chapter btns wrong
- [x] text commenting (documents) structure wrong (nested rows?)

_Originally posted by @fuzzylogic2000 in https://github.com/liqd/adhocracy-plus/pull/2099#pullrequestreview-1195683160_

**Comment by lthueer** [comment]
Hi @phillimorland I had a quick look and noticed the following:
- wagtail buttons have only white fonts (before it was white + black depending on background)
- language dropdown grey not black
- create new project white background
- white font on buttons in dashboard
- selecting date, missing black font + time boxes look off
- add module has blue font (not black)
- image upload symbol background not there (or maybe that's new?)
- light blue in background colour seems to be different
- turquoise seems to be slightly different? (user profile dropdown)
- save button blue outline missing + when selected turn dark blue
- donation banner has turquoise background
- finished project in dashboard project overview has wrong turquoise & private/semi-public has black colour on black background
- background grey copyright for images darker than on prod
- in general there seem to be a problem with black and white font (e.g. project header, category labels
- send comment (idea detail page) or idea button no background colour

**Comment by jostertag** [comment]
- [ ] calender symbol/button in phases (dashboard) with white font instead of black
- [ ] add category, add label and export excel buttons in dashboard all have blue font (not black)
- [ ] You cannot see the card anymore (its just grey) --> I don't know if its related to styling issues
- [ ] labels (as merkmale, category, budget) in proposals/ideas with black font (should be white font)

**Comment by lthueer** [comment]
@phillimorland I noticed the following two points while testing:
- [x] font colour a+ startpage, font colour doesnot adapt to background: https://aplus-dev.liqd.net/
- [ ] dashboard light blue looks different

**Comment by phillimorland** [comment]
@jostertag what do you mean by card?

**Comment by jostertag** [comment]
@phillimorland I meant map! When I tested I couldn't see it anymore, but this is no issue anymore, so I deleted it. Sorry for the confusion.

**Comment by phillimorland** [comment]
these all seem to be done
