### ISSUE TITLE
Accessibility "Information" and "Ergebnis" of a project

### ISSUE THREAD

**Issue by jostertag** [liqd/adhocracy-plus#2133]
**URL:** e.g. https://aplus-dev.liqd.net/liqd-tests/projects/text-commenting/
**user:** any
**expected behaviour:** As a user I want to go to results and information of a project by using the tab-function (keyboard)
**behaviour:** As a user I cannot access the results or information about a project by using the tab-function (keyboard)
**important screensize:** - 
**device & browser:** mac, firefox
**Comment/Question:** -

Screenshot?

**Comment by phillimorland** [comment]
NOTE: does work with arrow keys, tab keys work in dashboard tabs but not in project tabs

**Comment by phillimorland** [comment]
@jostertag so looking at best practices it seems that arrow keys are the norm for navigating between tabs so will close this but open another one for the dashboard tabs 
https://www.w3.org/WAI/ARIA/apg/example-index/tabs/tabs-manual
