### ISSUE TITLE
release styling issues

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2141]
- [x] 1 font colour a+ startpage, font colour doesnot adapt to background for two columns block with dark blue background & quote element with dark blue background: https://aplus-dev.liqd.net/info/best-practics/
![Bildschirm­foto 2022-12-13 um 09 09 07](https://user-images.githubusercontent.com/36957474/207261971-7c5356e1-2c6a-4a12-8a99-744bd8613965.png)
- [x] 2 dashboard light blue looks different, same on project tiles (background colour)
- [x] 3 poll button colour (description) has different blue
![Bildschirm­foto 2022-12-12 um 15 48 34](https://user-images.githubusercontent.com/36957474/207083428-42d2391f-c04a-4c96-bd79-f89842fad0ed.png)
- [x] 4 poll view: background colours of open answers not there anymore
- [x] 5 poll view: for multiple choice answers (results) background colour not there, only for most rated answer
![Bildschirm­foto 2022-12-12 um 15 51 09](https://user-images.githubusercontent.com/36957474/207083804-d9036d88-658d-4ea8-aee1-d2213769e1bd.png)
- [x] 6 idea tile view: yellow "under consideration" feedback-status with white font (on prod it has a black font in order to have a strong contrast) 
<img width="1440" alt="Bildschirmfoto 2022-12-13 um 14 43 00" src="https://user-images.githubusercontent.com/113608720/207342022-87b4f591-94d7-4ffa-95fb-99c9fdcb9fb4.png">
- [ ] 7 mobile device different button shape for "save-button" when creating a new idea/proposal or editing it.
<img width="572" alt="Bildschirmfoto 2022-12-13 um 16 48 40" src="https://user-images.githubusercontent.com/113608720/207381125-5cb95ae5-87ff-450c-a090-27d3f5bf1c26.png">

- [ ] 8 Font of Follow-Button has no contrast when there is a "darker" picture added to the organization site. 
<img width="1381" alt="Bildschirmfoto 2023-01-03 um 10 02 12" src="https://user-images.githubusercontent.com/113608720/210329066-608d4d8f-baa2-4717-be6d-15c4461da0b4.png">

**Comment by phillimorland** [comment]
@lthueer what mobile device for the last one, I can't replicate

**Comment by lthueer** [comment]
@phillimorland this one was added by @jostertag. Do you remember which device it was? To me it looks like one of the newer iphones.

**Comment by phillimorland** [comment]
PR was only partial fix

**Comment by jostertag** [comment]
@lthueer @phillimorland Sorry, that I didn't mention it. It was on an Iphone on chrome and on safari.

**Comment by phillimorland** [comment]
@khamui can you take a look at number 7, I still can't replicate on my chrome

**Comment by khamui** [comment]
should fix it:
https://github.com/liqd/adhocracy-plus/pull/2183

**Comment by phillimorland** [comment]
PR for this was merged so closing
