### ISSUE TITLE
#6751: multi-module says "xxx D" left

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2151]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/projects/testprojekt-1222/
**expected behaviour:** abbreviation of days adapts to language
**behaviour:** currently only in English (strings not on Transifex either)

**Comment by Rineee** [comment]
@fuzzylogic2000 This is just a translation issue, right?

**Comment by fuzzylogic2000** [comment]
@Rineee Yes, I did add wrong quotation marks. https://github.com/liqd/adhocracy4/pull/1297 should fix it.

**Comment by fuzzylogic2000** [comment]
check string is there after translations are pushed.
Also check: https://github.com/liqd/adhocracy-plus/issues/2154
