### ISSUE TITLE
#6750: translation string missing

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2154]
"To view content changes, click refresh" not translated and not on Transifex

**Comment by Rineee** [comment]
@lthueer We will push all the strings once the story is completely finished, ok?

**Comment by lthueer** [comment]
@Rineee totally fine! Just wanted to add it so we won't forget

**Comment by fuzzylogic2000** [comment]
closing in favour of https://github.com/liqd/adhocracy-plus/issues/2151

**Comment by fuzzylogic2000** [comment]
@lthueer Where is that string? Is it still there or is there a nother string now? I pushed the new strings and couldn't find it on transifex, but I suspect that we just changed the original string.

**Comment by fuzzylogic2000** [comment]
Ha, no, did find it! It is missing!
