### ISSUE TITLE
#6750: position of logo & Text different than design

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2167]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/dashboard/communication/content/create/testprojekt-1222/format/1/
**user:** all
**expected behaviour:** logo's position is according to the design. Text position is according to the design.
**behaviour:** logo position looks a bit off and too centered, in the design it looks a bit more in the corner of the image (1). The text can be moved up a bit in all sharepic formats (2)
**important screensize:**
**device & browser:** 
**Comment/Question:** 
- for all 4 formats
- tested with different image sizes

1)
![Bildschirm­foto 2022-12-20 um 15 00 56](https://user-images.githubusercontent.com/36957474/208684844-befcd649-5cca-4ff1-8172-2cb9d324f7da.png)

2)
![Bildschirm­foto 2022-12-20 um 15 21 21](https://user-images.githubusercontent.com/36957474/208689411-3dd8fe30-92b4-40c4-a23c-3c492c5d441d.png)
![sharepic](https://user-images.githubusercontent.com/36957474/208689427-e7ed2c88-b9e5-4a60-b024-90425ea00684.png)

**Comment by phillimorland** [comment]
@mcastro-lqd so we are using the co-ordinates from the designs but maybe they are a bit off?
Insta: X:160 Y: 160
Story: X:160 Y: 1117 px
Linkedin: X:160 Y: 160
Twitter: X:160 Y: 160

**Comment by mcastro-lqd** [comment]
@phillimorland Hey @phillimorland, its strange cause that's the info I get from Illustrator, maybe we can try using 80? I would have to check the Stories again
<img width="768" alt="Screenshot 2022-12-22 at 12 13 57" src="https://user-images.githubusercontent.com/59610786/209099988-005fd79d-3c82-493a-bdac-80a26b1d49b3.png">
