### ISSUE TITLE
Embedding issues

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#217]
There are some issues with embedding, please check out the issues on meinBerlin:

- https://github.com/liqd/a4-meinberlin/issues/2780

- https://github.com/liqd/a4-meinberlin/issues/2779

- https://github.com/liqd/a4-meinberlin/issues/2781

**Comment by fuzzylogic2000** [comment]
@rmader Did you fix all three issues for a+?

**Comment by phillimorland** [comment]
fixed
