### ISSUE TITLE
can't enlarge field for comments

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#219]
**URL:** https://adhocracy.plus/liqd/ideas/2020-00444/
**user:** tested both as admin and user
**expected behaviour:** I can enlarge my comment field if I write a long comment
**behaviour:** it does not work
**important screensize:**
**device & browser:** Mac both chrome and firefox
**Comment/Question:** 

Screenshot?
<img width="897" alt="Bildschirmfoto 2020-01-16 um 09 26 41" src="https://user-images.githubusercontent.com/35491681/72506883-1b49b100-3843-11ea-9760-a912ea06eec2.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer huh that's actually pretty weird! but as we are hoping to move over to the new comments in next sprint or 2 I would be inclined to not fix this, @fredewe is that ok for you?
