### ISSUE TITLE
Multi-modul does not show project information

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#222]
**URL:** https://adhocracy.plus/liqd/projects/module/ideensammlung-mit-kartenfunktion-2/
**user:** admin
**expected behaviour:** If I am in a multi-module, i can still see the project title as well as the short description of the project
**behaviour:** I do not see the project title nor the picture
**important screensize:** mobile and desktop
**device & browser:** macOS MOjave, 72.0.1 (64-Bit)
**Comment/Question:** In mein.berlin.de it works, not sure if it is ought to work in adhocracy as well..?

**Comment by phillimorland** [comment]
@hmkay this is the design and it does the same in mB, in both the breadcrumb states the name of the project and the header image is not shown, unless i have misunderstood?

**Comment by hmkay** [comment]
@phillimorland ah, I thought we saw it and thought it was missing information about the project, such as the picture or the description

**Comment by phillimorland** [comment]
as this is part of the design I am closing
