### ISSUE TITLE
multi-module-tile: days, months etc. underlined

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2222]
**URL:** https://aplus-stage.liqd.net/testorga-luca/projects/testprojekt-2/
**user:** 
**expected behaviour:** not underlined
**behaviour:** abbreviations are all underlined
**important screensize:**
**device & browser:** 
**Comment/Question:** 
dev & stage

<img width="284" alt="Bildschirm­foto 2023-01-11 um 15 39 30" src="https://user-images.githubusercontent.com/36957474/211834549-5ef22c6d-5308-4d06-98b1-5bb6ac9daf91.png">

**Comment by fuzzylogic2000** [comment]
That's not because of our styling, but because we added it as abbreviation html tag for a11y. I don't know if we can or should change that. What do you think @philli-m ?

**Comment by philli-m** [comment]
After doing some digging it looks like removing it isn't a big issue so will fix it
