### ISSUE TITLE
stage: social logins not working

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2223]
**URL:** https://aplus-stage.liqd.net/accounts/login/?next=/testorga-luca/dashboard/organisations/projects/
**user:** 
**expected behaviour:** social logins are working
**behaviour:** 500 error
**important screensize:**
**device & browser:** 
**Comment/Question:** 
- github, twitter, google
- also on redirects
- login and registration not working
- working on dev

<img width="529" alt="Bildschirm­foto 2023-01-11 um 16 29 46" src="https://user-images.githubusercontent.com/36957474/211847377-5ce4357b-4971-4af1-b5c5-5ae49e5e78f7.png">

**Comment by goapunk** [comment]
I fixed the logins for google and github (I didn't setup twitter but it is working on dev and prod)
