### ISSUE TITLE
#6749 Colour Poll-results

### ISSUE THREAD

**Issue by jostertag** [liqd/adhocracy-plus#2226]
**URL:** https://aplus-stage.liqd.net/jonathans-testorga/projects/testumfrage/
**user:** registered user
**expected behaviour:** the colouring of the poll-results should be consistent.
**behaviour:** on prod the poll-result shows the best (most voted) answer in a different blue than on stage. On stage there is no colour difference between the best answer and the others.
**important screensize:** - 
**device & browser:** mac & firefox
**Comment/Question:** First screenshot shows prod, second shows stage.
Was the different colouring intentionally (@mcastro-lqd)? If so, you can close the issue

Screenshot?
![Bildschirm­foto 2023-01-12 um 14 36 27](https://user-images.githubusercontent.com/113608720/212081072-81cc5214-3375-4303-a225-e168d414cd58.png)
![Bildschirm­foto 2023-01-12 um 14 36 44](https://user-images.githubusercontent.com/113608720/212081077-a7dd67f2-9575-40c0-8056-0fe9c5626f38.png)

**Comment by lthueer** [comment]
@phillimorland wasn't something changed about the colours on a+? I think the old result view was more clearer from a user perspective about which option was answered the most. Is there any chance to use another colour for the first most voted answer, maybe the darker blue if not too dark? i think this would be nice to have. What do you think @mcastro-lqd ?
