### ISSUE TITLE
Problems with selecting/deselecting answers and changing my answers in poll

### ISSUE THREAD

**Issue by SandisStudi** [liqd/adhocracy-plus#2239]
**URL:** https://aplus-dev.liqd.net/sandis/projects/umfrage-4/?initialSlide=1
https://aplus-stage.liqd.net/hafencity-hamburg-gmbh/projects/umfrage-3/
https://aplus-dev.liqd.net/sandis/projects/umfrage-4/?initialSlide=0

but also redirect
**user:** reg.User, Initiator, Admin
**expected behaviour:** 
When taking part in a poll, i want to be able to easy deselect the answer possibilieties or change my answer if i change my mind or want to withdraw my participation at all and to be sure that answer changes have been accpeted by the software - also i dont want to be able to submit answers if i havent choosed any answers 

**behaviour:** 
**Multiple-choice** When taking part in a multi-choice poll with the option to choose multiple answers, i am able to select the answers i wish. But if i change my mind and try to deselect some answers by clicking on the answers again - its not possible to remove the blue hook so that i am sure, that the answers are deselect. 
However if i have tried to deselect answers by clicking on them again (but nothing happend for me visually because the blue hook is still there) and then klick to "submit answers" my poll result shows that i succesfully had deselected the unwanted answers and it only counted those answers that i havent tried to deselect. 
https://aplus-stage.liqd.net/hafencity-hamburg-gmbh/projects/umfrage-3/
Furthermore, if i try to deselect all the answers i have choosed, nothing happends visually for me because the blue hooks infront of the formally choosen answers are still there - so there are choosen answers an i am able to click on "submit answers" - but my poll results shows that i havent choosed any answer at all and i am able to take part at the poll again. (I dont want to be able to "submit answers" if i havent choosed any answers)

**Poll when only one answer allowed**
When taking part in a poll with only one answer allowed, i am not able to deselect my selected answer. The only possibility if changing my mind is to choose one of the other answer. 
Furthermore if i submit my answer and click then on "change answers" for change my answers or withdraw my participation and answers at all (by deselecting my choosen answer)
**IF** there are only two possibilities of answer: i try to deselect my choosen answer and the website shows me that this kind of change is not allowed because my answer is "empty or not allowed", the only possibility is to choose the other answer
https://aplus-dev.liqd.net/sandis/projects/umfrage-4/
Screenshot: 
![Bildschirm­foto 2023-01-16 um 14 15 53 (2)](https://user-images.githubusercontent.com/113611764/212691839-2adadd7d-eb03-4514-a1e4-7d59a0de39d0.png)

**IF** there are at least three answer possibilities: I can only choose another answer but not deselect my answer to withdraw my participation at all
https://aplus-dev.liqd.net/sandis/projects/umfrage-4/?initialSlide=0

**important screensize:** no
**device & browser:** Mac (Firefox, Chrome, Safari) 
**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
@lthueer @SandisStudi @mcastro-lqd 
'Poll when only one answer allowed': This behavior is the default over all systems for radio buttons, I am not sure that changing familiar behavior is the correct way to go although that is maybe more of a question for @mcastro-lqd ? our other options are: 
- we make it a checkbox with explanation that only 1 can be selected (would probably be a small US)
- we keep the radios and add another option 'none of the above' however this would be annoying for people wanting to withdraw all their answers unless we record that input as not giving an answer but again might be confusing (could be done as an issue though)
- we change the default behavior of the radios

**Comment by lthueer** [comment]
@phillimorland i think for the radio buttons it's fine that you have to choose the other answer option (with only two options). From my view for a user it's more important being able to change an answer and not revoke the answer to "no answer". And that's possible with the radio button. This is how it's now on a+ prod and hasn't led to confusion yet. What do you think @mcastro-lqd ?

**Comment by mcastro-lqd** [comment]
@phillimorland @lthueer @SandisStudi I think the current Radio Button vs Checkbox situation is understandable, it just need to be able to revoke the answer, right?
