### ISSUE TITLE
problematic line break 

### ISSUE THREAD

**Issue by SandisStudi** [liqd/adhocracy-plus#2240]
**URL:** https://aplus-stage.liqd.net/profile/SandisregUser/
**user:** reg. user
**expected behaviour:** a long user name is still displayed in one line or the line break is suitably
**behaviour:** the line break dispolays an username with 13 charakters with a linebreak of 12 charakters in one line and 1 charakter in the second line 
**important screensize:**
2560 × 1600
1920 × 1200
**device & browser:** Mac and Firefox
**Comment/Question:** 
Screenshot?
<img width="1440" alt="Bildschirm­foto 2023-01-16 um 14 48 03" src="https://user-images.githubusercontent.com/113611764/212693974-59a73e6b-594f-4c9c-b948-c894f573fbb8.png">

**Comment by fuzzylogic2000** [comment]
We did update the styling of the profile. Looks differently now and is not breaking weirdly in tis case
