### ISSUE TITLE
unintuitive automatic text in module Text-Commenting 

### ISSUE THREAD

**Issue by SandisStudi** [liqd/adhocracy-plus#2241]
**URL:** https://aplus-stage.liqd.net/hafencity-hamburg-gmbh/dashboard/modules/text-diskutieren-10/document/
**user:** Initiator,Admin
**expected behaviour:** When creating module commentig, i want the automatic preformulated text for the names of chapters to intuitiv and helpful
**behaviour:** The name of the first Chapter is "first chapter" if i add a new chapter, its name is "new chapter" and not "second chapter" "third chapter"... as expected 
**important screensize:**no
**device & browser:** no 
**Comment/Question:** 

Screenshot?
<img width="1440" alt="Bildschirm­foto 2023-01-16 um 15 08 14" src="https://user-images.githubusercontent.com/113611764/212698176-c5ed2527-9954-4430-a22d-8f887611034e.png">

**Comment by lthueer** [comment]
@fuzzylogic2000 Since this is a minor wording issue, I would agree with you and stick with the current solution, even if it is not ideal!
