### ISSUE TITLE
Horizontal tile styling broken

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#2251]
**URL:** https://aplus-dev.liqd.net/phillitopictest-org/ will also be visible on user profile if only 1 project is participated in
**user:** all
**expected behaviour:** the styling of the horizontal tile is not broken
**behaviour:** it looks very broke
**important screensize:** from 768px up
**device & browser:** all

**Comment by phillimorland** [comment]
@lthueer I added this to the milestone as feel it's quite vital

**Comment by lthueer** [comment]
@phillimorland oh yes, good that you've catched it. Thank you!
