### ISSUE TITLE
project tile not fully clickable

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2261]
**URL:** https://adhocracy.plus/werder-havel/
**user:** 
**expected behaviour:** whole tile can be clicked and has a shadow
**behaviour:** only the title and description text part is clickable
**important screensize:**
**device & browser:** all
**Comment/Question:** 

- same for project tile in user profile (followed projects) 
- same for moderation dashboard projects (moderation & user overview)

<img width="970" alt="Bildschirm­foto 2023-01-31 um 14 30 52" src="https://user-images.githubusercontent.com/36957474/215773997-e508e3eb-7bc2-49f1-b962-065f44d2e894.png">

**Comment by lthueer** [comment]
@khamui @fuzzylogic2000 reopening this as the issue is still there on dev for the project tiles in the moderation dashboard. The tiles for multi-modul projects can not be clicked anymore and the shadow effect disappeared (which was working before): https://aplus-dev.liqd.net/teststadt/projects/res/

**Comment by lthueer** [comment]
oh, you're right! That's why I thought I've noticed the issue before. :D Thank you!

**Comment by philli-m** [comment]
@lthueer this should now be fixed
