### ISSUE TITLE
Excel export polling broken

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#230]
**URL:** https://adhocracy.plus/liqd/dashboard/modules/umfrage/poll/export/
**user:** admin
**expected behaviour:** Excel export shows numbers/data
**behaviour:** There is no data in the excel export
**important screensize:** desktop
**device & browser:** macOS Version 10.14.6 (18G1012) , Firefox 72.0.2 (64-Bit)
**Comment/Question:**

**Comment by fuzzylogic2000** [comment]
It only exports comments. So, it's empty when there are none.
