### ISSUE TITLE
Debate template not translated in template overview modal

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#232]
**URL:** https://adhocracy.plus/workshop/dashboard/organisations/blueprints/
**user:** initiator
**expected behaviour:** language according to my setting
**behaviour:** the debate module is not translated into german in the template choose modal
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
Well, as we didn't get the final wording in English or German, we can't fix that. I will close it as it's still a task for @fredewe or @hmkay on taiga.
