### ISSUE TITLE
order of fields in organisation edit

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#233]
**URL:** https://adhocracy.plus/workshop/settings/
**user:** initiator
**expected behaviour:** logical order of fields to guide me through the form, e.g. picture uploads not separated
**behaviour:** seems that the order is rather randomly
**important screensize:**
**device & browser:** 
**Comment/Question:** I think the following order would be clearer:

- Titel Ihrer Plattform
- Slogan
- kurze Beschreibung Ihrer Organisation
- ausführliche Beschreibung Ihrer Organisation
- Impressum
- Logo
- Headerbild + Copyright

**Comment by fuzzylogic2000** [comment]
We are currently working on the form anyway, so that's good timing! @fredewe should we change it to the order proposed by @CarolingerSeilchenspringer ? Maybe we need to make clear, that "ausführliche Beschreibung" appears in the "about"-tab yet (if that doesn't happen anyway). @hmkay

**Comment by hmkay** [comment]
@fuzzylogic2000 : I think that would be a great new order! And for making it clear that "ausführliche Informationen" appears in the other tab, we use the helptext, right?
