### ISSUE TITLE
Wrong invitation link

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#236]
**URL:** adhocracy.plus
**user:** invited user
**expected behaviour:** as invited user i would expect to get a funcional invite link
**behaviour:** the invite link misses the part "adhocracy.plus/" and does not work
**important screensize:**-
**device & browser:** -
**Comment/Question:** Example link: 
<img width="629" alt="Bildschirmfoto 2020-01-24 um 17 17 38" src="https://user-images.githubusercontent.com/5470479/73084606-8a6f7700-3ecd-11ea-86f2-c166504c9f3e.png">
https://fredetest/projects/participant-invites/d5a59c25-24a2-498c-844e-df728e9d5001/

Screenshot?

**Comment by phillimorland** [comment]
@rmader @fuzzylogic2000 this seems to be fixed so will close but just tagging incase you need to add anything?!
