### ISSUE TITLE
Twitter Social Login not working

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#2363]
- not working on prod, stage
- works on dev

![Bildschirmfoto 2023-04-20 um 09 36 43](https://user-images.githubusercontent.com/36957474/233294290-1497f9fe-9be2-4e37-aa37-3d19a5c9eb58.png)

**Comment by lthueer** [comment]
@goapunk the login is working on dev but no on the other platforms. Will this problem then be fixed in the next version?

**Comment by goapunk** [comment]
@lthueer we'll need to see how to make it work again. They changed their api quota after musk took over

**Comment by Rineee** [comment]
@lthueer What would you like us to do here? If I understood @goapunk right, we could try to create a new login app on twitter, and see if they block that again, but in the worst case we might get blocked completely. Should we try it anyway?

**Comment by lthueer** [comment]
@Rineee @goapunk I think it would be great if you could try to get it to work, because I think it's a nice feature that we offer, that people can sign in with their Twitter account. At the moment it doesn't work on prod and for the redirects, so we have nothing to loose I would say :D

**Comment by goapunk** [comment]
@lthueer the login is working again on https://adhocracy.plus but not for the custom domains. The reason twitter blocked our login is that they now want us to pay 100$/month if we want to have the login for more than 10 urls (which we already have). So we need to decide what to do here:
* only have it on https://adhocracy.plus
* have it on https://adhocracy.plus + 9 other custom domains
* pay for more
* remove the twitter login completely

**Comment by lthueer** [comment]
@goapunk thank you for making it work again! I would say that we don't pay for more than 10 as it's not used a lot compared to login with email or google. I would say we keep it for a+ and 9 other custom domains and remove it for all the other subdomains (and future subdomains). Would it be possible to not show the twitter login button for the subdomains where it's not working?

**Comment by goapunk** [comment]
@lthueer sounds good to me. And yes, we can hide the button for the urls where we don't want it.

**Comment by lthueer** [comment]
@goapunk cool, let's do it then :) And If twitter becomes even more annoying in the future, we'll just remove the login I would say

**Comment by goapunk** [comment]
reopening as twitter is still having issues

**Comment by fuzzylogic2000** [comment]
@goapunk @lthueer What's the status? Can we do sth. about it? Or should we add the `not our bug` label?

**Comment by goapunk** [comment]
I think we decided to remove twitter as it still doesn't work

**Comment by lthueer** [comment]
@fuzzylogic2000 @goapunk yes, I agree. If it's not working we should remove it with the next release

**Comment by goapunk** [comment]
cool, so things to resolve this issue then would be:
* remove twitter related styling
* remove twitter social app from django admin
