### ISSUE TITLE
#7208 feedback icon in activities is bigger than the others

### ISSUE THREAD

**Issue by jostertag** [liqd/adhocracy-plus#2379]
**URL:** https://aplus-dev.liqd.net/userdashboard/overview/activities/
**user:** any
**expected behaviour:** icons in activities should have the same size
**behaviour:** feedback icon is bigger than the other icons
**important screensize:** any
**device & browser:** mac (firefox)
**Comment/Question:** is this maybe on purpose @lthueer ?

Screenshot?
<img width="1332" alt="Bildschirm­foto 2023-04-25 um 15 31 02" src="https://user-images.githubusercontent.com/113608720/234294197-f4d2e4a6-2bda-4b34-9751-2ca850127b59.png">

**Comment by lthueer** [comment]
@jostertag yes, that's an issue! I'll add it to the milestone

**Comment by lthueer** [comment]
@jostertag closing as issue has already been opened #2358
