### ISSUE TITLE
project page: module tiles look slightly off

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#25]
The module tiles for parallel modules look slightly off. The font size for the title is too large (the h4 size would be much better) and the border should be 2px thick.

![Bildschirmfoto 2019-10-23 um 17 07 32](https://user-images.githubusercontent.com/15341015/67407688-2bd9ea80-f5b8-11e9-9e35-ca88ad2d196a.png)

https://product-dev.liqd.net/eine-organisation/projects/speak-up-und-ideensammlung-nacheinander/

**Comment by phillimorland** [comment]
closed in favor of #61
