### ISSUE TITLE
Counting Comments (2 issues - similar problem in mB)

### ISSUE THREAD

**Issue by jostertag** [liqd/adhocracy-plus#2509]
**URL:** https://aplus-dev.liqd.net/testorga/topicprio/2023-00821/
**user:** any 
**expected behaviour:** the counting of comments should be consistent behaviour
**behaviour:** 

1. The number of comments in the detail idea view is not the same anymore as the number in the idea overview (list & map). This is because the detail ide view now counts as well child comments while the idea overview doesn't. (see screenshot 1 vs. 2)      

2. The counting in the detail view stops at **20** seperate comments (different to mB). If there are child comments, it adds to counting of 100. The number is then also different to the idea overview. If I scroll down, then new comments are loaded and the counting number on top changes. This can be very confusing. (see screenshot 1, 2 & 3)

**important screensize:** any
**device & browser:** mac ff
**Comment/Question:** look at https://github.com/liqd/a4-meinberlin/issues/5220

Screenshot?

**Comment by philli-m** [comment]
fixed with this PR https://github.com/liqd/adhocracy-plus/pull/2511
