### ISSUE TITLE
Font different when there is no header picture

### ISSUE THREAD

**Issue by jostertag** [liqd/adhocracy-plus#2517]
**URL:** https://aplus-dev.liqd.net/liqd-tests/projects/test-the-debate/
**user:** any
**expected behaviour:** font should be black
**behaviour:** font is shiny and therefore blurred
**important screensize:** -
**device & browser:** mac (ff)
**Comment/Question:** 

Screenshot?
<img width="1119" alt="Bildschirm­foto 2023-08-09 um 13 49 41" src="https://github.com/liqd/adhocracy-plus/assets/113608720/f63bf1dd-33d8-47b6-980e-f1d206878875">

**Comment by goapunk** [comment]
should be fixed by https://github.com/liqd/adhocracy-plus/pull/2514
