### ISSUE TITLE
datepicker: the end date should be automatically set to at least the start date

### ISSUE THREAD

**Issue by hklarner** [liqd/adhocracy-plus#2530]
**URL:** /my_organisation/dashboard/modules/my-spatial-brainstorming/phases/

**user:** initiator, logged in

**behaviour / steps to reproduce:** Today is 2023-09-01. I have just set the start date of my brainstorming phase to be 2023-10-01 and want to now set the end date. The current value of the end date is still in the past at 2023-09-01. 

**expected behaviour:** The current end date is adjusted to at least the current start date (2023-10-01) so that I don't have to scroll again to where my phase has to start.

**device & browser:** all

**Comment by philli-m** [comment]
story in backlog
