### ISSUE TITLE
Basic questions about the README

### ISSUE THREAD

**Issue by erelsgl** [liqd/adhocracy-plus#2539]
1. The readme says to run `make watch` to run a local server, but does not say how to access this server. I would add after `make watch`:

"wait until you see:
```
System check identified no issues (0 silenced).
...
Django version ... using settings 'adhocracy-plus.config.settings'
Starting development server at http://127.0.0.1:8004/
```
Then open `http://127.0.0.1:8004/` in your browser. 
"

2. After I open the link in my browser, it is not clear what to do next. I would move the sentence `Go to http://localhost:8004/ and login with [admin@liqd.net](mailto:admin@liqd.net) | password` here.

3. The next heading says 'Use PostgreSQL for testing', but is not clear what exactly PostgreSQL is used for: is it necessary for testing? Or only for some of the functionality? Should it be done before or after the `make watch`?

**Comment by goapunk** [comment]
Hi @erelsgl ,
thanks for the suggestions, I agree some parts are not very clear. We'll look into improving it and making it easier to follow.
Regarding 3: this is purely optional  and not required for testing most of the time. Regarding whether it should be run before or after `make watch` the text already states: `to start the test server with postgresql, run:` followed by the commands you need to run, ending in `make watch` :).
