### ISSUE TITLE
Using / for division outside of calc() is deprecated

### ISSUE THREAD

**Issue by erelsgl** [liqd/adhocracy-plus#2541]
This line:

https://github.com/liqd/adhocracy-plus/blob/d5e16921e084a1fb7e6942f566906892ac26de5d/adhocracy-plus/assets/scss/_base.scss#L169

causes a warning during npm run build:

"Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.".

Solution: Add 'calc'; Replcae the line with:

```
    margin-bottom: calc($spacer / 2);
```

There are similar warnings in _accordion.scss and _action.scss and _project_header.scss

**Comment by philli-m** [comment]
Thank you for your comment, the current version of Dart SASS is 1.69.5, we address deprecation warnings when carrying out the relevant updates.
