### ISSUE TITLE
save and load data

### ISSUE THREAD

**Issue by oriyalperin** [liqd/adhocracy-plus#2549]
Hi,
I'm looking for the best way to save the current data and later load it for testing and simulations.
I attempted to use `dumpdata` and `loaddata`, but I'm encountering several errors like 'duplicate entry'.
Can you provide guidance on a recommended approach/command? Thanks!

**Comment by goapunk** [comment]
@oriyalperin sorry for the late reply! Not sure what's the best approach here, you could try to dump only the data/models you need and not the whole database and then create some fixtures from it which you can load into a fresh database when required, similar like we did it here: https://github.com/liqd/a4-meinberlin/tree/main/meinberlin/fixtures
