### ISSUE TITLE
Comment answering comments behaviour 

### ISSUE THREAD

**Issue by philli-m** [liqd/adhocracy-plus#2550]
**URL:** https://aplus-dev.liqd.net/liqd-tests/ideas/2024-00902/
**error:** 
* when trying to edit the child comment it triggers 'Only invited users can actively participate.' however editing parent comments works 

Screenshot?
![screenshot(39)](https://github.com/liqd/adhocracy-plus/assets/5871230/c5c392e4-8f52-4f89-9c09-6cb36639062e)

**Comment by TeaJayyy** [comment]
fixed
