### ISSUE TITLE
#7637 [a+] big django & wagtail update: Inconsistency in "Text Discussion" chapter overview

### ISSUE THREAD

**Issue by sblindow** [liqd/adhocracy-plus#2585]
**URL:**
https://aplus-dev.liqd.net/permanent-test-project/projects/text-diskutieren-einzelmodul/

**user:**
Any

**expected behaviour:**
When navigating through the chapters using the table of contents menu, I expect the state of the menu (collapsed or opened) to remain the same, when switching to another chapter.

**behaviour:**
When navigating to the first chapter, the menu always opens. When navigating to any subsequent chapter, the menu is collapsed by default. Wether or not I collapse or open the menu by myself before switching, doesn't influence the bahaviour of the menu.

**important screensize:**
Any

**device & browser:**
Current MacOS, Firefox 124.0.2

**Comment by goapunk** [comment]
also exists on stage, so I guess it always has been like this
