### ISSUE TITLE
#8102 [Z:T] Enable more SSOs on a+: Issue with Duplicate Registration Email and Confirmation Handling

### ISSUE THREAD

**Issue by sblindow** [liqd/adhocracy-plus#2606]
**Expected Behavior:** 
When a user attempts to register with an email address already associated with an existing account (either social or normal email account), they should:

1. Receive an email reminding them of their existing account and providing instructions for password reset.
2. See the standard "we have sent you a confirmation link" message on the website to prevent unauthorized users from determining if an email is registered.

**Current Behavior:**
When registering with a social account, email confirmation is not mandatory. This can cause confusion if the user forgets they used social login and tries to register again using the same email, resulting in an error and preventing successful registration/ handling of the duplicate accounts.

**Steps to Reproduce**
1. Register on the website using a social account (e.g., Google, Facebook) without confirming the email.
3. Log out.
4. Attempt to register again using the same email address (either through a social account or normal email registration).

**Screenshots**
Error message after attempting to register with an e-mail adress that is already linked to a social account but hasn't been confirmed in that account.
<img width="2031" alt="Bildschirmfoto 2024-05-15 um 09 44 36" src="https://github.com/liqd/adhocracy-plus/assets/144320958/bc020889-ebcb-4c85-b17d-2e090e216f24">

**Comment by m4ra** [comment]
@TeaJayyy I guess this should go to the release milestone too

**Comment by m4ra** [comment]
To clarify here, social accounts shouldn't include email verification, as they are verified by the social provider already, and if they had to verify again, it would defeat the purpose of registering with a social account. So we are removing the unique email constrain, as this is also not standard practice for django. And social accounts registration can be linked to existing accounts if emails are same. @TeaJayyy @sblindow
