### ISSUE TITLE
#8104 [Z:T] Enable account deletion for users on a+

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#2609]
**URL:** https://aplus-dev.liqd.net/account/account_deletion/
**important screensize:** *Mobile*
**device & browser:** *Safari*

The Mobile version is a bit different, could we maybe change the buttons at least? 

![Screenshot-2024-05-22-at-12 04 12](https://github.com/liqd/adhocracy-plus/assets/59610786/e0f88b03-1ab9-46c5-8662-5c312ed4deea)

**Comment by m4ra** [comment]
@TeaJayyy do we add this to the release milestone?

**Comment by goapunk** [comment]
@mcastro-lqd the color comes from the danger button (https://app.zeplin.io/project/5b051f895f8bcd4920567e89/screen/628c9016d5f942bb2aef2c86), should we do a new button style especially for this?

**Comment by mcastro-lqd** [comment]
@goapunk no, you can leave the danger one. I don't know why I have this red

**Comment by goapunk** [comment]
@mcastro-lqd too late, i already used yours now :see_no_evil: I can undo it if you prefer
