### ISSUE TITLE
inactive questions debate asks for participation

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#267]
**URL:** https://aplus-dev.liqd.net/teststadt/projects/this-is-a-debate-module/
**user:** logged-in user
**expected behaviour:** The questions/statements of the module indicate that participation was possible and that I can have a look at it (e.g. "Diskussion")
**behaviour:** The questions/statements still indicate "jetzt mitmachen", but I cannot take part. 
**important screensize:** mobile and desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** 

![Uploading Bildschirmfoto 2020-02-03 um 18.26.51.png…]()

**Comment by fuzzylogic2000** [comment]
What should it say instead?

**Comment by fuzzylogic2000** [comment]
We will have the same for future modules. What should happen there?

**Comment by hmkay** [comment]
I´d say for finished ones: "Debatte lesen" / "Read debate". What do you think?

For the upcoming it would be cool to have something like "Take part in x days". Is that possible, @fuzzylogic2000 ?

**Comment by fuzzylogic2000** [comment]
This nearly works. We can put: Take part from ....
Or just "Take part soon", I think that's accurate enough?!

**Comment by hmkay** [comment]
hmm, depends if it is starting soon or just in a year ;)
Maybe "participation starting on..." is also a possibility?

**Comment by hmkay** [comment]
Does this also work for the project tiles? Currently, upcoming projects are not indicated by days. Or is that anotehr bug?

![Bildschirmfoto 2020-02-04 um 19 44 30](https://user-images.githubusercontent.com/30862422/73775849-fcc24000-4786-11ea-9ab7-8aa7662e1f83.png)

**Comment by fuzzylogic2000** [comment]
Yes, that's another issue #252 , but there (should be) a date shown. So, that would be a solution here as well. Maybe I also use the same wording (because it's not much longer than the other wording. So, that would be "Beteiligung: ab <date>"/"Participation: from <date>"

**Comment by fuzzylogic2000** [comment]
Oh my, I totally run off in the wrong direction here.
On the level of questions/ideas/topics we only know if the user is allowed to do sth. (and that depends on the phase). So, to solve this here, we can write "discuss with us" or whatever we want to put there (like keep "jetzt mitmachen") when the user is allowed to discuss or would be allowed if logged in. And we could just display "read more" when debating isn't allowed (which would be before and after the debating phase). That would also mean, that admins always see the "jetzt mitmachen".
