### ISSUE TITLE
"Siezen" in error message

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#269]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/
**user:** logged-in user
**expected behaviour:** I am "gesiezt" everywhere on the platform
**behaviour:** error writes "du"
**important screensize:** mobile and desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** 

![Bildschirmfoto 2020-02-03 um 18 34 48](https://user-images.githubusercontent.com/30862422/73676043-e8f9d980-46b3-11ea-89d3-e2131bc9dd4b.png)

**Comment by fuzzylogic2000** [comment]
Ok, this is from another library. We have to find how we did it in mB (and what else we overwrote there).

**Comment by phillimorland** [comment]
@hmkay @fuzzylogic2000 what should this say instead?

**Comment by hmkay** [comment]
@phillimorland : "Stellen Sie sicher, dass dieses Feld nicht mehr als 4000 Zeichen lang ist."
