### ISSUE TITLE
Colouring of categories in debate module

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#270]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/
**user:** logged-in user
**expected behaviour:** beautiful colours of the categories that are in order with the CI of the page
**behaviour:** colours are different to design
**important screensize:** mobile and desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** Is the design in Zeplin the right colours, @phillimorland 

Screenshot?
![Bildschirmfoto 2020-02-03 um 18 38 19](https://user-images.githubusercontent.com/30862422/73676419-9f5dbe80-46b4-11ea-9aa4-b98458c9918d.png)

**Comment by mcastro-lqd** [comment]
Here you can find some options:
https://app.zeplin.io/project/5b051f895f8bcd4920567e89/dashboard?seid=5e32f3d360b0a55446a0e6a6

01 - Using our CI Colours
02 - Using lighter shades of our CI Colours 
03 - Inserting new colors
04 - Using lighter shades of the new colors

**Comment by phillimorland** [comment]
@hmkay which are we do we use?

**Comment by hmkay** [comment]
@phillimorland : see Zeplin
