### ISSUE TITLE
Spelling mistake in moderation dashboard

### ISSUE THREAD

**Issue by janeklqd** [liqd/adhocracy-plus#2703]
**URL:** https://aplus-dev.liqd.net/userdashboard/moderation/
**user:** moderator/any 
**behaviour:** No space between "von" and "permanent"; mistakenly displayed as "Vonpermanent" and not correctly as "Von permanent"
**important screensize:** *any*
**device & browser:** *any*

If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.
<img width="1493" alt="grafik" src="https://github.com/liqd/adhocracy-plus/assets/170422918/a7d9fea9-12a2-4f0c-8a9e-e482fb224c2a">

**Comment by goapunk** [comment]
This is an old error (in the translation, it also exists on prod). I include it in the fix for the feedback button
