### ISSUE TITLE
display of wording

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#271]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/
**user:** logged-in user
**expected behaviour:** "weniger anzeigen" is written next to another, less white space
**behaviour:** 
**important screensize:** mobile and desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** This is just in a very specific size - so I am not sure how important that is

![Bildschirmfoto 2020-02-03 um 18 46 11](https://user-images.githubusercontent.com/30862422/73677140-e8624280-46b5-11ea-9045-3f9c84097d13.png)

**Comment by mcastro-lqd** [comment]
That should be like the image below, right? 

![Screenshot 2020-02-04 at 15 55 26](https://user-images.githubusercontent.com/59610786/73755749-cbd21300-4766-11ea-9b36-323a6a1bbeec.png)

**Comment by hmkay** [comment]
@mcastro-lqd Ah, no, I referred to comments that are too long and shortend down. Then, "Mehr anzeigen" appears. After that, you can shorten the comment again via "weniger anzeigen". And that was a little weird in the picture

**Comment by mcastro-lqd** [comment]
@hmkay Ah, true! Sorry! I would do more or less how it is, but align to the left and display all in one line. 

![Screenshot 2020-02-04 at 16 28 25](https://user-images.githubusercontent.com/59610786/73758831-692f4600-476b-11ea-9fdc-15e3eb62778c.png)

**Comment by hmkay** [comment]
Sounds good, @mcastro-lqd ! Then this would also first go to Zeplin, right?
