### ISSUE TITLE
Editing a sub post is not possible 

### ISSUE THREAD

**Issue by MarleyMi** [liqd/adhocracy-plus#2716]
**URL:** https://aplus-dev.liqd.net/permanent-test-project/ideas/2024-00966/ **but also on stage & prod**
**user:** any
**expected behaviour:** Users should be able to edit their sub posts in the same way they can edit the original post.
**behaviour:** An error message appears: "Nur eingeladene Nutzer*innen können sich beteiligen," and the sub post cannot be edited.
**important screensize:** any
**device & browser:** Mac Pro 14, Firefox 
**Comment/Question:** When attempting to edit a sub post, the system displays an error message stating "Nur eingeladene Nutzer*innen können sich beteiligen" ("Only invited users can participate"). This issue does not occur with the original post, which can be edited without any problems.

Screenshot?
<img width="971" alt="grafik" src="https://github.com/liqd/adhocracy-plus/assets/171042469/9df23da0-be3d-4039-a224-0ebbf74c38af">

**Comment by goapunk** [comment]
should be fixed now
