### ISSUE TITLE
Sorting last discussed = newest?

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#272]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/
**user:** logged-in user
**expected behaviour:** When I click on "Last discussed", the contributions that last had a child comment are being displayed on the top
**behaviour:** Last added/newes parent comment is being shown on top of the list
**important screensize:** mobile and desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:**

**Comment by fuzzylogic2000** [comment]
Haha, and when I chose last discussed, the newest ones are on top. :rofl: Good catch!
