### ISSUE TITLE
Styling search help text

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#273]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/
**user:** logged-in user
**expected behaviour:** If I search for a word, I will be told which word I searched for
**behaviour:** the word is indicated, but it appears that I could search for many different words at the same time (styling?)
**important screensize:** desktop and mobile
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** 

![Bildschirmfoto 2020-02-03 um 18 58 27](https://user-images.githubusercontent.com/30862422/73677851-725edb00-46b7-11ea-97d5-8204c60f9cdb.png)

**Comment by phillimorland** [comment]
@hmkay this needs a design, where should design issues be listed?

**Comment by hmkay** [comment]
@phillimorland ah, I didn´t know @mcastro-lqd

**Comment by mcastro-lqd** [comment]
I think it makes more sense to put inside the box, right? Amazon also does that, but the word can still be editable which is good in case the user type wrong.


![Screenshot 2020-02-04 at 16 13 36](https://user-images.githubusercontent.com/59610786/73757520-9da20280-4769-11ea-8945-e3ea03242c49.png)

**Comment by hmkay** [comment]
Nice, let´s move this discussion to Zeplin then to discuss the designs! @mcastro-lqd @phillimorland

**Comment by phillimorland** [comment]
@mcastro-lqd @hmkay implementing the cancel within the input field as it is currently implemnted might be a little resource heavy, I will look into it but if it's a no go is there an alternative?

**Comment by mcastro-lqd** [comment]
@phillimorland Then I would leave it without the button stroke, like just the word + the x icon, is that too hard? 

Cause I think this division is making it weird to read, right? 

![Screenshot 2020-02-04 at 17 43 23](https://user-images.githubusercontent.com/59610786/73766126-df38aa80-4775-11ea-8860-c8a1992fc12c.png)

**Comment by phillimorland** [comment]
@ma perfect! :) i'll try do btn first though!
