### ISSUE TITLE
CKEditor Upload dont work on custom domains 

### ISSUE THREAD

**Issue by pascalkienast** [liqd/adhocracy-plus#2739]
**URL:** https://aplus-hafencity-stage.liqd.net or also on prod Domain like beteiligung.arnsberg.de
**user:** initiator and admin
**expected behaviour:** File and Image Upload via CKEditor should work
**behaviour:** File and Image Upload on CKEditor does not work on custom domains (see screenshots)
**important screensize:** any
**device & browser:** any
**Comment/Question:** I think the prio is high, because it is also on prod. In the console is an 404 error

<img width="1278" alt="Bildschirmfoto 2024-08-05 um 12 04 40" src="https://github.com/user-attachments/assets/a28b91b2-ee56-45b6-9409-81298627a1b8">

![image](https://github.com/user-attachments/assets/e96d5511-4d8e-49ac-b1a4-bc66fe6576e9)

**Comment by goapunk** [comment]
fixed
