### ISSUE TITLE
Search function searches only parent comments

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#274]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/
**user:** logged in user
**expected behaviour:** I can find any text / word that is within the comments (child and parent comments)
**behaviour:** results of the search only display parent comments
**important screensize:** mobile and desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** Was the search function aiming to cover als child comments? the acceptance criteria say: "the search results are shown instead of all comments" (I don´t quite understand that acceptance criteria, @rittermo )

![Bildschirmfoto 2020-02-03 um 19 06 15](https://user-images.githubusercontent.com/30862422/73678264-47c15200-46b8-11ea-9f3f-7bed29827394.png)

**Comment by fuzzylogic2000** [comment]
It's the same as in spd. Should we change it here? But then it also needs to display the child comments already opened. 
Is this still a question or already a bug?

**Comment by hmkay** [comment]
@fuzzylogic2000 Ah, ok, well actually then I think it would be a new request. I will make a story out of that! And I will close this one.
