### ISSUE TITLE
Error by "Use postgresql database for testing"

### ISSUE THREAD

**Issue by rjlanari** [liqd/adhocracy-plus#2745]
Once I enter _make postgres-create_ command I'm asked for a password. I entered my PC password, but that didn't work and got the following errors. 

Which pw should I enter?  

![Screenshot 2024-08-19 at 10 28 03](https://github.com/user-attachments/assets/5d3159e7-e00b-4de1-8b12-acb1db1bb986)

**Comment by TeaJayyy** [comment]
@goapunk?
