### ISSUE TITLE
Styling "share"-function

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#275]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/?comment=100
**user:** logged-in user
**expected behaviour:** styling is supernice
**behaviour:** styling is already nice and functional - and I know we can enhance that even further! =)
**important screensize:**
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** 

![Bildschirmfoto 2020-02-03 um 19 07 58](https://user-images.githubusercontent.com/30862422/73678430-a686cb80-46b8-11ea-919a-95b06529cd8c.png)

**Comment by mcastro-lqd** [comment]
I'll put that on Zeplin as well then (:
