### ISSUE TITLE
CKeditor "italics" selection of text reverts back to default after saving 

### ISSUE THREAD

**Issue by janeklqd** [liqd/adhocracy-plus#2766]
**user:** Initiator
**expected behaviour:** The text remains italics after I click save. 
**behaviour:** The text changes back to the default, non-cursive style. 
**device & browser:** sonoma 14.6.1 (23G93); firefox, safari
**Comment/Question:** The bug is also on meinBerlin, and there's a similar bug in the CKeditor linked here: https://github.com/liqd/adhocracy-plus/issues/2765 

Screenshot of what I save in the CKeditor
![Screenshot 2024-09-17 at 16-32-28 Edit project information — Innovationswettbewerb - Green Office — adhocracy _Musterorganisation](https://github.com/user-attachments/assets/4fa20f99-8df9-4609-9985-57c39646f254)

Screenshot of what happens after I click save:
![Screenshot 2024-09-17 at 16-32-41 Edit project information — Innovationswettbewerb - Green Office — adhocracy _Musterorganisation](https://github.com/user-attachments/assets/11acf10e-54f4-4166-aa65-9317d546b07a)

**Comment by goapunk** [comment]
@TeaJayyy the old ckeditor didn't allow italic I think, so we need to decide whether:

1. we want to allow italic now
2. remove the option for italic from ckeditor

**Comment by TeaJayyy** [comment]
@goapunk We want that as well.

**Comment by goapunk** [comment]
@TeaJayyy it's an easy  fix so can stay an issue
