### ISSUE TITLE
Link to "official" page is missing

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#277]
**URL:** https://aplus-dev.liqd.net/teststadt/
**user:** logged-in user
**expected behaviour:** Next to the headline, there is a link to the official page of the oragnisation (see designs in zeplin, https://app.zeplin.io/project/5b051f895f8bcd4920567e89/screen/5e206158862516a9f39e2122)
**behaviour:** No link found
**important screensize:** mobile desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** 
![Bildschirmfoto 2020-02-03 um 19 56 41](https://user-images.githubusercontent.com/30862422/73681754-52331a00-46bf-11ea-9d99-089632874167.png)

**Comment by fuzzylogic2000** [comment]
It's there!

**Comment by hmkay** [comment]
I am so sorry. I noticed during Review that I just didn´t include the link...

<iframe src="https://giphy.com/embed/3orieWNwitLzDsyCT6" width="480" height="366" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/season-4-the-simpsons-4x15-3orieWNwitLzDsyCT6">via GIPHY</a></p>
