### ISSUE TITLE
Wording "Urheberrecht des Kopfzeilenbildes"

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#278]
**URL:** https://aplus-dev.liqd.net/teststadt/settings/
**user:** admin
**expected behaviour:** The description refers to the header?
**behaviour:** I do not quite understand what the description wants me to do
**important screensize:** mobile and desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** Is this about indicating the Urheber of the header?

![Bildschirmfoto 2020-02-03 um 20 00 54](https://user-images.githubusercontent.com/30862422/73682205-33815300-46c0-11ea-9497-a7b8fe968abd.png)

**Comment by fuzzylogic2000** [comment]
Yes, did you change the language to check what the original is? I think it was header image copyright. And the image above is header image. Could you please give us the German translation if we are meant to change it? Or an English and a German version if both are not clear.

**Comment by fuzzylogic2000** [comment]
Do you already have an idea how to put it, so that the wording makes sense?

**Comment by hmkay** [comment]
@fuzzylogic2000 : Yes! Sorry for not giviing the translation immediately. Just use "Headerbild" instead of "Kopfzeilenbild" and change "Autor" to "Autor*in", then it should all make sense. Merci!!
