### ISSUE TITLE
Avatar picture missing

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#279]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00156/?comment=107
**user:** admin
**expected behaviour:**avatar pictures are shown next to comments if no picture uploaded
**behaviour:** no avatar pictures shown
**important screensize:** mobile and desktop
**device & browser:** macOS Mojave 10.14.6, Firefox 72.0.2 (64-Bit)
**Comment/Question:** 

![Bildschirmfoto 2020-02-03 um 20 09 03](https://user-images.githubusercontent.com/30862422/73682745-4a747500-46c1-11ea-8b82-7cdf18268b21.png)

**Comment by mcastro-lqd** [comment]
I'll put that on Zeplin as well
