### ISSUE TITLE
async comments: moderator badge goes over the image/username

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#284]
**URL:** in debate module question detail
**user:** all
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

![Screenshot from 2020-02-04 14-45-09](https://user-images.githubusercontent.com/8178179/73750241-1fd7fa00-475d-11ea-9b5b-f61f80da94d1.png)

**Comment by phillimorland** [comment]
Won't happen now we have the default image :D
