### ISSUE TITLE
#8381 [z:t] Create Module: Open Poll - user entries are not blocked consistently  for unregistered users after the poll has been answered 

### ISSUE THREAD

**Issue by sblindow** [liqd/adhocracy-plus#2840]
**URL:** 
https://aplus-dev.liqd.net/permanent-test-project/projects/open-poll-module/

**user:** 
non-registered

**expected behaviour:** 
After the poll has been answered, unregistered users can click on 'to poll', which takes them back to the original view without the results. In this view they cannot participate in the poll a second time, so entries into the poll form should be blocked.

**behaviour:** 
Interaction is blocked in the case of radio-buttons, but not for checkboxes and open questions.

**Comment by goapunk** [comment]
@TeaJayyy I've been thinking about this and now I wonder: is there any point for unregistered users to have the `to poll` button ? Going back to the poll doesn't really seem to provide any valuable info, so maybe hiding the button makes more sense (and is much easier)

**Comment by TeaJayyy** [comment]
@goapunk We asked ourselves this too. For now, I'm happy with hiding the button for unregistered users.

**Comment by goapunk** [comment]
will be closed by https://github.com/liqd/adhocracy4/pull/1691

**Comment by goapunk** [comment]
done
