### ISSUE TITLE
Editing of subjects in debate module: Internal server error

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#291]
**URL:** https://adhocracy.plus/test/dashboard/subjects/module/debate-3/
**user:** Initiator
**expected behaviour:** As an initiator i would like to edit my subjects in the debate module
**behaviour:** When i click on the edit button, there is a 500 error
**important screensize:** - 
**device & browser:** - 
**Comment/Question:** - 

Screenshot?

<img width="1072" alt="Bildschirmfoto 2020-02-06 um 09 34 11" src="https://user-images.githubusercontent.com/5470479/73919917-c094f980-48c4-11ea-9123-ff8ba2219cdf.png">

**Comment by fuzzylogic2000** [comment]
We already fixed that on dev: https://aplus-dev.liqd.net/teststadt/dashboard/subjects/module/debate-2/ It will be on prod with the next release.

**Comment by fredewe** [comment]
Thanks @fuzzylogic2000
