### ISSUE TITLE
changes in the comment section

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#295]
URL: https://aplus-dev.liqd.net/teststadt/subjects/2020-00170/

Comment/Question:
![Screenshot 2020-02-06 at 17 02 08](https://user-images.githubusercontent.com/59610786/73955204-433ca980-4903-11ea-9958-97c921134fc9.png)

1 - We can also re-think that later but what I meant was that, what do you think? 
![Screenshot 2020-02-06 at 17 19 08](https://user-images.githubusercontent.com/59610786/73956181-df1ae500-4904-11ea-8ebf-b684ad5d4b72.png)

2 – I have the feeling that the stroke should be thinner. My layout was 1 pt + #D8D8D8

3 – After deciding about this icon, I think it should be closer to the 3 dots one. 

4 – Would it be possible to leave the Moderator thing like how we talked before? From my perspective, it doesn't need to be that prominent, what do you think?
![Screenshot 2020-02-06 at 17 22 45](https://user-images.githubusercontent.com/59610786/73956494-4fc20180-4905-11ea-9cae-30e763d01688.png)

**Comment by phillimorland** [comment]
@mcastro-lqd 4: you mean light grey and italic to the right of user name right?
