### ISSUE TITLE
changes in organisation page

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#296]
URL: https://aplus-dev.liqd.net/teststadt/ 

Comment/Question:

If possible, I would increase the image height cause most of the pictures aren't that stretched. The layout had 345px height. 

I would also leave the project description text using the same paragraph style as the about text on top. 

I know I already mentioned, but just to leave it registered, the CTA is missing. :)

Also, If I send you the shadow style precisely can we change that as well? 

Thanks! 

![Screenshot 2020-02-06 at 17 32 10](https://user-images.githubusercontent.com/59610786/73958503-46866400-4908-11ea-92dc-330b18f3da83.png)

**Comment by phillimorland** [comment]
@mcastro-lqd when you say same paragraph style, do you just mean font size or is there something else I am missing? 
I can get shadow from zeplin no worries

**Comment by mcastro-lqd** [comment]
I think its just the size isn't?
