### ISSUE TITLE
Not possible to send newsletters as an initiator

### ISSUE THREAD

**Issue by Amelie-liqd** [liqd/adhocracy-plus#297]
**URL:** https://adhocracy.plus/test/dashboard/newsletters/create/
**user:** initiator
**expected behaviour:** as an initiator, I want to send newsletters to all subscribers of a problem. 
**behaviour:** I cannot send a newsletter when I am not admin, it does not show the green banner that the newsletter was sent successfully.  

![Bildschirmfoto 2020-02-07 um 11 20 23](https://user-images.githubusercontent.com/57798416/74021470-e80ac580-499b-11ea-8fcd-7ba348d53543.png)

**Comment by fuzzylogic2000** [comment]
It also never shows in the tasks or gives an error message.
