### ISSUE TITLE
refactor user image in profile

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#31]
it's here:
![Screenshot from 2019-10-18 13-34-49](https://user-images.githubusercontent.com/8178179/67091295-918b3880-f1ac-11e9-8a33-fc1222b6959c.png)

and used to be here:
![Screenshot from 2019-10-18 13-36-52](https://user-images.githubusercontent.com/8178179/67091308-96e88300-f1ac-11e9-8c12-bfcce674df90.png)

**Comment by fuzzylogic2000** [comment]
This issue is done, but now the username is broken next to the image, but should start under image. @phillimorland ideas how to get it under the image?

**Comment by phillimorland** [comment]
@fuzzylogic2000 it's a float thing, i'll remove it and test if it breaks anything else

**Comment by fuzzylogic2000** [comment]
The username also has u-word-break-all? I can't remember, why I used that?

**Comment by phillimorland** [comment]
I have implemented a quick fix but the user profile need a makeover
