### ISSUE TITLE
organisation landing page: text for emtpty list does not take into account if user is logged in

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#311]
The text is: 
Currently, there are no public participation processes. Sign in here (LINK) or read more in About (LINK).
There is a check if there is actually an about-tab and that is only displayed, when it exists. When we also check if the user is logged in, we have four versions of the text. That seems a bit over the top. Any ideas, @hmkay

**Comment by hmkay** [comment]
@fuzzylogic2000 : Thank you so much for your thoughts!
I guess this goes hand in hand with the idea of "request membership". It would be supercool if there would be a check if only private projects are shown. If so, we could say "Currently, there are no public participation processes for non-members. Request membership here to be able to participate!"

Buuuut, I know this comes with some other annoying stuff....hmm.

**Comment by phillimorland** [comment]
@hmkay do we have any resolution for this?

**Comment by hmkay** [comment]
@phillimorland : Not yet. i guess this needs more concepting which is not yet of high priority. We would leave the current text and work on it...later/as soon as it comes up again?

**Comment by fuzzylogic2000** [comment]
@hmkay Currently, when there are no projects and the user is logged in, it still tells the user to log in. Probably not perfect for IGBCE as well.

**Comment by hmkay** [comment]
Hrmpf. Nope. How can we find a solution? Can we check if the user is logged in? Or is that than he old problem of too much checking?
Anyhow, the IG BCE will always have projects I guess. So probably this is low prio, but a thing we should def keep in mind!

**Comment by fuzzylogic2000** [comment]
@fredewe I think, we should fix this! When we want to use the members, but also anyway, because it is weird to be logged in and still see a text telling me to log in.
So, currently we only check if there are projects and if there is a project info.
It doesn't matter if logged in or not, only if there is a project info. 
![Screenshot from 2021-05-12 17-06-12](https://user-images.githubusercontent.com/8178179/117998996-b3c34900-b344-11eb-8bf3-dd38388d1eab.png)
![no-projects-logged-in](https://user-images.githubusercontent.com/8178179/117999017-b7ef6680-b344-11eb-8805-25a2b40cfc5f.png)
I think, we should add another text for a logged in user. Maybe "Currently, there are no public participation processes. Please check again later."

**Comment by fredewe** [comment]
@fuzzylogic2000 You are right, this is something we should fix. So we just need a wording or do we have to add a new textfield for that in the code?

**Comment by fuzzylogic2000** [comment]
@fredewe We need a text and will need to add that into the code then. But that should be quick. Then we'll also push it to transifex and it needs to be translated. I will just add my text, so that we can push it to transifex today. :)

**Comment by fredewe** [comment]
👍
