### ISSUE TITLE
Enquete registration form 

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#323]
We need link text for bottom text
note: don't worry about top text
![Registrieren — adhocracy ](https://user-images.githubusercontent.com/5871230/74449202-860afe00-4e7c-11ea-8934-bf3d0389cf75.png)

Screenshot?

**Comment by phillimorland** [comment]
@hmkay

**Comment by fuzzylogic2000** [comment]
What about putting the first part at the bottom: "Registrieren Sie sich hier, um an der Diskussion um die Themen der "
"Enquete-Kommission „Künstliche Intelligenz – Gesellschaftliche Verantwortung "
"und wirtschaftliche, soziale und ökologische Potenziale“ teilzunehmen. Die "
"Beiträge werden für das Gutachten an die Enquete-Kommission Künstliche "
"Intelligenz verwendet. Es ist möglich, dass einzelne Beiträge direkt und "
"indirekt zitiert und veröffentlicht werden. Weitere Informationen zur "
"Verwendung entnehmen Sie den Nutzungsbedingungen und der "
"Datenschutzerklärung. "

And the second bit at the top:
"Sie haben schon ein Nutzerkonto? Dann <a href=\"%(login_url)s\">melden Sie "
"sich bitte an</a>."

?? @hmkay

**Comment by phillimorland** [comment]
@hmkay do we have a solution for this yet?

**Comment by hmkay** [comment]
Yess!! It is how @fuzzylogic2000 said, @phillimorland : 

TOP: "Sie haben schon ein Nutzerkonto? Dann melden Sie sich bitte an."
BOTTOM: "Registrieren Sie sich hier, um an der Diskussion um die Themen der Enquete-Kommission „Künstliche Intelligenz – Gesellschaftliche Verantwortung und wirtschaftliche, soziale und ökologische Potenziale“ teilzunehmen. Die Beiträge werden für das Gutachten an die Enquete-Kommission Künstliche Intelligenz verwendet. Es ist möglich, dass einzelne Beiträge direkt oder indirekt zitiert und veröffentlicht werden. Weitere Informationen zur Verwendung entnehmen Sie den Nutzungsbedingungen und der Datenschutzerklärung."

Still, we should be prepared to change it in case of emergency....

**Comment by fuzzylogic2000** [comment]
Haha, like when there's a fire? :rofl:

**Comment by hmkay** [comment]
...or WORSE!!!
