### ISSUE TITLE
Wording social media on organisation page (about tab)

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#334]
**URL:** https://aplus-dev.liqd.net/teststadt/information/
**user:** User
**expected behaviour:** Text above Social media items should say: (proposal) "More about [organisation name]"
small: "Find us on social media and share your insights of this participation."
**behaviour:** Only says "Social Media", this makes it unclear if it is from A+ or from the organisation
**important screensize:** mobile!
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by hmkay** [comment]
@fredewe : We still need to talk about this, though!

**Comment by fredewe** [comment]
Let's do that tomorrow.

**Comment by hmkay** [comment]
Mañana, mañana...

**Comment by fredewe** [comment]
Mañana Banana

**Comment by hmkay** [comment]
[https://media.giphy.com/media/cw8Nr4u28tVKw/giphy.gif](url)

**Comment by phillimorland** [comment]
@fredewe @hmkay just put hold label on untill wording is decided, once it's finalised you can remove label so we know to work on it oh and also don't forget german translations, cheers!

**Comment by fredewe** [comment]
@phillimorland thanks. We'll do that.
@hmkay today after PM?

**Comment by hmkay** [comment]
@phillimorland : It is the suggestion in the original issue. German version: 

"Mehr über [Organisation]"
"Finden Sie uns auf social media und berichten Sie über diese Beteiligung!

Question: The social media part is only shown if filled out, right?

**Comment by fredewe** [comment]
@hmkay removed "on hold" label, ok?

**Comment by phillimorland** [comment]
in answer to your question yes, it's only shown if links are added
