### ISSUE TITLE
debate module: comment field stays extended

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#337]
**URL:** https://aplus-dev.liqd.net/teststadt/subjects/2020-00170/
**user:** Admin
**expected behaviour:** field for contribution closes/becomes smaller again after I added my comment
**behaviour:** field for contribution stays extended after I added a biiiiig comment. 
**important screensize:**
**device & browser:** 
**Comment/Question:** low prio

**Comment by phillimorland** [comment]
@hmkay not sure what relevance the screen shot it? also cannot reproduce error, what browser were you on?

**Comment by hmkay** [comment]
xD Yes. As you see: All empty! But actually I wasn´t sure if I made myself clear what I meant.

I was on Firefox, 73.0 (64-Bit)

**Comment by hmkay** [comment]
@phillimorland : Low prio though, no milestone!

**Comment by hmkay** [comment]
@phillimorland I just got it! Sorry! Wrong picture!! So forget about the picture.

**Comment by phillimorland** [comment]
cannot reproduce on any browser so closing for now
