### ISSUE TITLE
How to include giphy´s in github

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#342]
How can I include gifs in github? There HAS TO BE A WAY!!!

**Comment by phillimorland** [comment]
`<iframe src="https://giphy.com/embed/5z0cCCGooBQUtejM4v" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/thedailyshow-funny-reaction-5z0cCCGooBQUtejM4v">via [GIPHY</a></p>`](url)

**Comment by phillimorland** [comment]
@hmkay save it and drag and drop it

**Comment by hmkay** [comment]
![giphy](https://user-images.githubusercontent.com/30862422/74747968-10ca6f00-5268-11ea-8c78-a6f78b38edf0.gif)
