### ISSUE TITLE
#2672 debate module

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#343]
URL: https://aplus-dev.liqd.net/teststadt/subjects/2020-00170/

![Screenshot 2020-02-18 at 11 42 16](https://user-images.githubusercontent.com/59610786/74729522-e3b89500-5244-11ea-84da-84e7344a8330.png)

**01** – I know I've already done that, but now after checking with all the avatars, I thought we might need a bit more space between the question and the avatars.

![Screenshot 2020-02-18 at 11 28 49](https://user-images.githubusercontent.com/59610786/74729684-224e4f80-5245-11ea-8ec4-2c7569d473cd.png)

**02** – The category labels should change the colour when selected. 
![Screenshot 2020-02-18 at 11 52 52](https://user-images.githubusercontent.com/59610786/74729801-545fb180-5245-11ea-82ba-4fa22053288a.png)

**03** – I think it's fine for now but at some point, the comment section should have the same behaviour as the other input fields. (eg. Grey or Black when inactive - A+ Plus Blue when active) 

![Screenshot 2020-02-18 at 11 48 01](https://user-images.githubusercontent.com/59610786/74729985-9f79c480-5245-11ea-894b-5ac68fff6a63.png)

**04** – Would it be possible to fix that? There is always a thicker stroke in between the input field and the icon. Same for number **05.** 

![Screenshot 2020-02-18 at 11 41 37](https://user-images.githubusercontent.com/59610786/74730074-c932eb80-5245-11ea-90a9-ed7520c691dd.png)

Same for number **04.** 

![Screenshot 2020-02-18 at 11 20 20](https://user-images.githubusercontent.com/59610786/74730192-fb444d80-5245-11ea-9f12-4970cdac2e3c.png)

Here is still missing the shadow

Thanks!

**Comment by mcastro-lqd** [comment]
![Screenshot 2020-02-18 at 17 04 41](https://user-images.githubusercontent.com/59610786/74753908-1f695400-5271-11ea-8328-b10e8720c723.png)

6 – Same as Desktop 

7 – Same as Desktop 

8 – I would insert some space here, otherwise, it looks too squeezed. 

![Screenshot 2020-02-18 at 17 00 21](https://user-images.githubusercontent.com/59610786/74754086-61929580-5271-11ea-8941-18c6297f0bca.png)

9 – Also, the x thingie just shows up when you go back to the input field, I think it should appear after the search is clicked. Both Mobile & Desktop

**Comment by phillimorland** [comment]
@mcastro-lqd "Here is still missing the shadow" - do you mean the darker gray background?

**Comment by mcastro-lqd** [comment]
@phillimorland I have the impression that there was always a shadow here, right? Even from before 

![Screenshot 2020-02-18 at 17 17 02](https://user-images.githubusercontent.com/59610786/74754817-80455c00-5272-11ea-8579-4c047361e975.png)

**Comment by phillimorland** [comment]
ahh on the pic, cool, right will do! :)

**Comment by mcastro-lqd** [comment]
@phillimorland I included the mobile version on Zeplin in case you have time.

**Comment by phillimorland** [comment]
@mcastro-lqd for 9, this is weird and already logged as a bug but as it's only for keyboard users its low prio so might not get fixed for a while, just heads up! :)
