### ISSUE TITLE
Cannot add new debate module in dashboard

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#346]
**URL:** https://hidden.enquetebeteiligung.de/dashboard/organisations/blueprints/debate/
**user:** admin
**expected behaviour:** I can add the debate module on enquete
**behaviour:** The form empties after clicking on "safe"
**important screensize:**
**device & browser:** Firefox
**Comment/Question:** @fuzzylogic2000 said maybe it´s ok after second deployment!

**Comment by fuzzylogic2000** [comment]
Works!

**Comment by hmkay** [comment]
@rmader @phillimorland

**Comment by hmkay** [comment]
Also: Information about organisation!

**Comment by fuzzylogic2000** [comment]
Ok, it should work again now, it was something with the redirect. Sorry! Could you check again?
