### ISSUE TITLE
Enquete shows a+ Icon on tab of browser

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#347]
**URL:** https://hidden.enquetebeteiligung.de/
**user:** admin
**expected behaviour:** Other icon in bar of tab, different to Bundestag though. Or none...?
**behaviour:** Shows A+ icon
**important screensize:** desktop and mobile
**device & browser:** Firefox
**Comment/Question:** 

![Bildschirmfoto 2020-02-18 um 17 35 14](https://user-images.githubusercontent.com/30862422/74756660-3316b980-5275-11ea-8198-8f037d091074.png)

**Comment by phillimorland** [comment]
@hmkay I will remove the favicon unless we have an alternate? @mcastro-lqd?

**Comment by phillimorland** [comment]
currently it's just a white sq

**Comment by hmkay** [comment]
I guess that´s fine! If @mcastro-lqd has a better idea, go on ;)
