### ISSUE TITLE
newsletter with picture not displayed correctly

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#351]
**URL:** 
**user:** receiver of newsletter
**expected behaviour:** I can see pictures in newsletter
**behaviour:** if adding a picture to my newsletter, the mail I mail has no content.
**important screensize:**
**device & browser:** apple mail
**Comment/Question:** 

Screenshot?
apple mail
![Bildschirmfoto 2020-02-19 um 13 54 40](https://user-images.githubusercontent.com/35491681/74836268-6150d380-531f-11ea-866e-b0120a7fe868.png)

**Comment by rmader** [comment]
Has this been fixed by now?

**Comment by Rineee** [comment]
Yes!
