### ISSUE TITLE
Think about 500 wording

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#354]
Github has a nice wording, maybe we would like to adapt it?

@mcastro-lqd @phillimorland @fredewe

**Comment by hmkay** [comment]
![Bildschirmfoto 2020-02-19 um 16 31 02](https://user-images.githubusercontent.com/30862422/74848320-d8926180-5337-11ea-8fe1-88ed3d1602da.png)

**Comment by fredewe** [comment]
I like it. Can we just use the same wording?

**Comment by fuzzylogic2000** [comment]
We should change the wording for the other error pages as well then! (403, 404). I think this should be a small story?

**Comment by fuzzylogic2000** [comment]
Yeah, not sure if it's an enahencement or a feature-request. Before we do it, we would need to have the wording and where to put it in our design, in any case, though.

**Comment by hmkay** [comment]
So this would go to @lthueer and @fredewe , right?

**Comment by lthueer** [comment]
Added to the backlog!
