### ISSUE TITLE
Enquete wording: 

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#355]
Here are the sentences that we may want to update to remove adhocracy but still maybe mention liqd or something? also we discussed changing the wording on the registration email so have included that
@hmkay @mcastro-lqd 

**footer:**
"<a>adhocracy+</a> ist eine Plattform, die von <a>Liquid Democracy e.V.</a> in Berlin bereitgestellt wird."

**base email:**
"adhocracy+ ist eine Plattform für Beteiligung, betrieben durch"

**registraion email:**
"Bitte bestätigen Sie Ihre Registrierung auf {{ current_site }}

Ihre Registrierung auf {{ current_site }}

Sie haben sich mit dieser E-Mail adresse und dem Benutzernamen "{{ user.username }}" auf der Beteiligungsplattform "{{ current_site }}" registriert. Um die Registrierung abzuschließen und Ihr Benutzerkonto zu aktivieren, bestätigen Sie bitte Ihre E-Mail Adresse. Wenn Sie diese E-Mail Adresse nicht zur Registrierung auf "{{ current_site }}" verwendet haben, können Sie diese Nachricht ignorieren. Wir werden Ihnen keine weiteren E-Mails senden.

Bestätigen Sie Ihre E-Mail Adresse

Diese E-Mail wurde an {{ user.email }} gesendet. Bei Fragen können Sie sich gerne unter {{ contact_email }} an uns wenden."

**Comment by phillimorland** [comment]
@hmkay also deadline would be tomorrow morning so we can get it deployed for testing is thats ok? (sorry!!)

**Comment by hmkay** [comment]
@phillimorland Thanks for the deadline! Puts everything in perspective. Here we go!

**footer:**
"Diese Beteiligungsplattform basiert auf der Plattform adhocracy.plus und wird bereitgestellt von Liquid Democracy e.V. in Berlin."

**base email:**
"Die Beteiligungsplattform der Online-Konsultation der Enquete-Kommission „Künstliche Intelligenz – Gesellschaftliche Verantwortung und wirtschaftliche, soziale und ökologische Potenziale“  wurde beauftragt durch den Deutschen Bundestag und wird betrieben durch den Liquid Democracy e.V. in Berlin.


**registraion email:**
"Bitte bestätigen Sie Ihre Registrierung auf {{ current_site }}

Ihre Registrierung auf {{ current_site }}

Sie haben sich mit dieser E-Mail-Adresse und dem Benutzernamen "{{ user.username }}" auf der Beteiligungsplattform "{{ current_site }}" registriert. Um die Registrierung abzuschließen und Ihr Benutzerkonto zu aktivieren, bestätigen Sie bitte Ihre E-Mail Adresse. Wenn Sie diese E-Mail-Adresse nicht zur Registrierung auf "{{ current_site }}" verwendet haben, können Sie diese Nachricht ignorieren. Wir werden Ihnen keine weiteren E-Mails senden.
Bestätigen Sie Ihre E-Mail Adresse

Diese E-Mail wurde an {{ user.email }} gesendet. Bei Fragen können Sie sich gerne unter {{ contact_email }} an uns wenden."

----
As a contact adress we should use support@enquetebeteiligung.de

**Comment by hmkay** [comment]
What about Newsletter and mailing of changes in the project, @phillimorland ?

**Comment by phillimorland** [comment]
@hmkay mailing of changes? the newsletters are written in the dashboard so we only mention a+ in the footer email base

**Comment by hmkay** [comment]
@phillimorland : Yes, like "Your comment has a comment" or "Your comment was deleted"

**Comment by phillimorland** [comment]
ok thats the base email so 
**base email:**
"Die Beteiligungsplattform der Online-Konsultation der Enquete-Kommission „Künstliche Intelligenz – Gesellschaftliche Verantwortung und wirtschaftliche, soziale und ökologische Potenziale“ wurde beauftragt durch den Deutschen Bundestag und wird betrieben durch den Liquid Democracy e.V. in Berlin.

**Comment by phillimorland** [comment]
in the footer of the email
