### ISSUE TITLE
Dashboard debate module: show whole text of subject

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#361]
**URL:** https://stage.enquetebeteiligung.de/dashboard/subjects/create/module/debatte-5/
**user:** initiator
**expected behaviour:** While typing in the subject and the short description of the debate subject, I would like to see what I´ve written.
**behaviour:** I only see what is written in the little box.
**important screensize:** desktop
**device & browser:** Firefox, Mac
**Comment/Question:** Can we simply widen the boxes?

![Bildschirmfoto 2020-02-20 um 14 01 51](https://user-images.githubusercontent.com/30862422/74936212-0afc9700-53ea-11ea-8404-7eb3a9380760.png)

**Comment by fuzzylogic2000** [comment]
We should use a textfield, I think. And maybe not just cut the chars of, that are too many, but give an error message?!
