### ISSUE TITLE
[enquete] email: moderation request still says adhocracy.plus in footer text

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#364]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** This email was sent to .... Your are receiving this email because you are moderator of the project Vertrauen und Transparenz.

adhocracy+ is a participation platform operated by
Liquid Democracy e.V., Am Sudhaus 2, D-12053 Berlin 
**important screensize:**
**device & browser:** 
**Comment/Question:**

**Comment by phillimorland** [comment]
adhocracy plus was not removed from the english version as you shouldn't ever see it

**Comment by fuzzylogic2000** [comment]
ah! Sure!
