### ISSUE TITLE
[enquete] footer does not link to a+

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#366]
I think it makes sense to put in the work (and change from the upstream) here as we want people to find a+
@hmkay

**Comment by hmkay** [comment]
You mean we should have a wording that refers to a+, @fuzzylogic2000 ?

**Comment by fuzzylogic2000** [comment]
Yes, and we do, but it does not link to a+, which I think it should also do. @hmkay

**Comment by phillimorland** [comment]
Also Liqd link doesn’t open in new tab just if we're doing footer

**Comment by phillimorland** [comment]
@hmkay will provide new wording

**Comment by hmkay** [comment]
<img width="569" alt="Bildschirmfoto 2020-02-24 um 11 15 38" src="https://user-images.githubusercontent.com/30862422/75144343-0f30f900-56f7-11ea-98d3-0eff01d1c976.png">

**Comment by hmkay** [comment]
"Die Beteiligungsplattform enquetebeteiligung.de (Link) basiert auf der Plattform adhocracy.plus (Link) und wird bereitgestellt von der Bietergemeinschaft nexus gmbH und Liquid Democracy e.V."

@fredewe : Is that alright like this?

**Comment by fredewe** [comment]
Sorry

**Comment by hmkay** [comment]
@phillimorland This also should go into the footer of all mails of enquete

**Comment by fuzzylogic2000** [comment]
@hmkay The email-footer thing does not work like that. It can't have links, and we can only change the first bit. (before Liquid and the address) and can't put anything behind. So, what about 
"Die Beteiligungsplattform enquetebeteiligung.de basiert auf der Plattform adhocracy.plus, wird bereitgestellt von der Bietergemeinschaft Liquid Democracy e.V. und nexus Institut für Kooperationsmanagement und interdisziplinäre Forschung GmbH und wird betrieben durch"
Liquid Democracy e.V., address...

**Comment by hmkay** [comment]
Ah, ok! Then it would be only: 
"Die Beteiligungsplattform enquetebeteiligung.de wird bereitgestellt von der Bietergemeinschaft Liquid Democracy e.V. und nexus Institut für Kooperationsmanagement und interdisziplinäre Forschung GmbH und basiert auf der Plattform adhocracy.plus."

Can we delete the other stuff with Liquid Democracy e.V., adress, etc?

**Comment by fuzzylogic2000** [comment]
@hmkay No, it has to end with "Liquid Democracy e.V., Am Sudhaus 2, D-12053 Berlin"

**Comment by hmkay** [comment]
Ok! Then just add it =) Should make sense, right?
