### ISSUE TITLE
a+ Debate report modal - User testing

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#369]
* success message looks weird - needs centering? redesign?
* the confirmation message when reporting a comment is very short and does not tell me who will take care of my complaint and until when.

**Comment by fuzzylogic2000** [comment]
All (or at least many, for example in registration) alerts are not centered.

**Comment by phillimorland** [comment]
have updated issue

**Comment by hmkay** [comment]
For MK: 
<img width="1033" alt="Bildschirmfoto 2020-02-24 um 11 20 47" src="https://user-images.githubusercontent.com/30862422/75144700-ca599200-56f7-11ea-8b86-76a94db6c441.png">

**Comment by phillimorland** [comment]
@hmkay do we want to change wording for this for enquete? if so need wording this morning

**Comment by hmkay** [comment]
Wording, I suggest this would be platform wide for A+, this would be easier, right?
@fredewe what do you think?

DE:
Danke für die Rückmeldung. Sie wird an die Moderation weitergeleitet und der Beitrag wird so schnell wie möglich geprüft.

ENG:
Thanks for the feedback. It will be forwarded to the moderator and the contribution will be checked as soon as possible.

**Comment by fredewe** [comment]
I am fine with it. This would be a shorter version: 
DE:
Danke für die Rückmeldung. Der Beitrag wird so schnell wie möglich von der Moderation geprüft.

ENG:
Thanks for the feedback. It will be checked by the moderators as soon as possible.
