### ISSUE TITLE
text under register button not visible before click - usertesting

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#376]
even on laptop size, I don't read the text under the register button, because I don't see it before I click the button.

**Comment by phillimorland** [comment]
move "Registrieren Sie sich hier, um an der Diskussion um die Themen der Enquete-Kommission „Künstliche Intelligenz – Gesellschaftliche Verantwortung und wirtschaftliche, soziale und ökologische Potenziale“ teilzunehmen. Die Beiträge werden für das Gutachten an die Enquete-Kommission Künstliche Intelligenz verwendet." 
to top then bottom
Es ist möglich, dass einzelne Beiträge direkt oder indirekt zitiert und veröffentlicht werden. Weitere Informationen zur Verwendung entnehmen Sie den (link)Nutzungsbedingungen.

**Comment by fuzzylogic2000** [comment]
This was meant to be more for a+. Are we meant to move it to the top there? @fredewe @hmkay

**Comment by phillimorland** [comment]
@fuzzylogic2000 this fix is for enquete this isn't an issue for a+ yet because it doesn't have the capcha yet
