### ISSUE TITLE
a+ Text in register confirmation email says "email" a lot - usertesting

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#377]
https://github.com/liqd/adhocracy-plus/blob/master/adhocracy-plus/templates/account/email/email_confirmation_signup.en.email
you have registered with this email and the username "{{ user.username }}" on "{{ current_site }}". To finish the registration and activate your account, please confirm your email. If you did not register on "{{ current_site }}" using this email address, you can ignore this email.

worse in german:
https://github.com/liqd/adhocracy-plus/blob/master/adhocracy-plus/templates/account/email/email_confirmation_signup.de.email
Sie haben sich mit dieser E-Mail adresse und dem Benutzernamen "{{ user.username }}" auf der Beteiligungsplattform "{{ current_site }}" registriert. Um die Registrierung abzuschließen und Ihr Benutzerkonto zu aktivieren, bestätigen Sie bitte Ihre E-Mail Adresse. Wenn Sie diese E-Mail Adresse nicht zur Registrierung auf...

**Comment by phillimorland** [comment]
@hmkay if you have time to find new words

**Comment by fuzzylogic2000** [comment]
Also please a+, not enquete! (and by a+ then both if in time).

**Comment by phillimorland** [comment]
if it's for both, @fredewe do you have any suggestion for wording update?

**Comment by hmkay** [comment]
Ihre Registrierung

Guten Tag,

Sie haben sich mit dem Benutzernamen "*username*" auf der Beteiligungsplattform "*PLATFORM*" registriert. Klicken Sie auf "E-Mail-Adresse bestätigen", um Ihre Registrierung abzuschließen. 

BUTTON E-Mail-Adresse bestätigen.

Sobald Sie registriert sind, können Sie sich auf "*PLATFORM*" beteiligen. Sollten Sie sich nicht registriert haben, können Sie die Nachricht ignorieren. 
---

@fredewe : OK?

**Comment by fredewe** [comment]
Fine, thanks

**Comment by phillimorland** [comment]
@hmkay transltaion? also does this mean we don't include the current sentence under the button
"This email was sent to {{ user.email }}. If you have any further questions, please contact us via {{ contact_email }}"

**Comment by hmkay** [comment]
@phillimorland (please correct, if needed ;) ): 

Your registration

Hello,

You have registered with the username "username" on the participation platform "PLATFORM". Click on "Confirm email address" to complete your registration.

BUTTON confirm e-mail address.

As soon as you are registered, you can participate in "PLATFORM". If you haven't registered, you can ignore the message.
