### ISSUE TITLE
think of styling for form input invalid

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#38]

**Comment by fuzzylogic2000** [comment]
@fredewe @lthueer Do we want the form fields that have errors to be marked? Currently errors are shown directly below, but the field is not marked.

**Comment by fredewe** [comment]
@fuzzylogic2000 it would be nice if form fields are marked. But the solution we currently have did not cause any trouble so far i would say. So i would not put too much effort it in. What do you think @lthueer ?

**Comment by lthueer** [comment]
@fuzzylogic2000 @fredewe I agree! I think its fine for the moment how it is. Shall we close the issue then?

**Comment by fuzzylogic2000** [comment]
yes, please!
