### ISSUE TITLE
enq Registration/account settings wording - User testing

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#380]
It says that Iʼll receive Newsletters in my account settings, but I never saw that option when I registered?!

**Comment by phillimorland** [comment]
organisation newsletter, is it possible?
if not, can we make all that select tick box into an email list to invite to symposium? @fuzzylogic2000 @rmader

**Comment by fuzzylogic2000** [comment]
I this issue about the wording or about sending a newsletter? What about the wording that is still there in the profile and doesn't fit the wording for the register form?

**Comment by phillimorland** [comment]
account setting wording would also be updated too hence issue title. 
@hmkay I discussed with @fuzzylogic2000 and we can get a list of email addresses that clicked the box for you to send an email to so shall I just copy the wording from the registration form to the account setting form so they both represent the same thing.

**Comment by fuzzylogic2000** [comment]
@fredewe As we need to release in the afternoon, we need wording here! Currently, the wording in the register form is different from the one in the account settings. If we could use the same in both cases, that would be the best way to do it.
![Screenshot from 2020-02-25 10-22-06](https://user-images.githubusercontent.com/8178179/75233225-d22d3b00-57b8-11ea-96b8-aed85fd72ebe.png)
![Screenshot from 2020-02-25 10-21-17](https://user-images.githubusercontent.com/8178179/75233228-d35e6800-57b8-11ea-84c7-f80f8f702d70.png)
![Screenshot from 2020-02-25 10-21-01](https://user-images.githubusercontent.com/8178179/75233230-d35e6800-57b8-11ea-8125-641b1b8a28ed.png)
![Screenshot from 2020-02-25 10-19-54](https://user-images.githubusercontent.com/8178179/75233231-d3f6fe80-57b8-11ea-86cb-bb818666809c.png)

**Comment by fredewe** [comment]
looks fine to me. 
@hmkay could you please dicide those things at the moment?

**Comment by phillimorland** [comment]
@hmkay which wording are we using? Info mails of newsletter?

**Comment by hmkay** [comment]
@phillimorland it would be Info-Mails! Though I don´t like the wording that much.

**Comment by hmkay** [comment]
Ich möchte weitere Informationen erhalten.
*Helptext* Projekte, denen Sie folgen, können Ihnen E-Mails mit Informationen schicken.

**Comment by phillimorland** [comment]
Projects you are following can send you additional information via email.'

**Comment by fuzzylogic2000** [comment]
:+1: I like that!
