### ISSUE TITLE
a+ Share wording confusing as it's not really social media share link - User testing

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#383]
wording suggestion: copy link with new link icon @fredewe @mcastro-lqd is that ok?

**Comment by phillimorland** [comment]
wording suggestion: get link

**Comment by phillimorland** [comment]
@hmkay if this requires more concepting, I can change it in the translations just for Enquete, if I do that what should german be?

**Comment by hmkay** [comment]
@phillimorland : We will leave the "Teilen". Conceptually we could think about putting "Melden" and "Teilen" into the three dots, that´s for example how Facebook does it and I guess people are used to that. Just as an idea for also cleaning up the comments part EVEN MORE (if possible, ha!)

**Comment by hmkay** [comment]
And then we could also think about to enhance the share button with stuff. But for now it tells you what to do - even though expectations might be disappointed ;)

**Comment by mcastro-lqd** [comment]
@phillimorland @hmkay I thought it shouldn't be sharable in Social Media but I can come up with something if we still have time. In case we are using it based on how it's currently there, the "Copied" wording after clicking is still missing.

**Comment by phillimorland** [comment]
@mcastro-lqd it isn't sharable on social media but during user testing people were confused by fact it says share so I think we need to rethink the icon and wording, reddit use 'get link' with a link icon hence my idea but it's not a problem for right now anymore

**Comment by hmkay** [comment]
Yes, let´s talk about this more conceptually...later =)

**Comment by fuzzylogic2000** [comment]
Are we happy with the wording as it is now @lthueer @fredewe @mcastro-lqd ?
![Screenshot from 2021-05-06 17-34-15](https://user-images.githubusercontent.com/8178179/117325858-6a30b500-ae91-11eb-9ba9-db03da6be75f.png)

It says "share" and then opens the modal to copy the link to the comment.

**Comment by fuzzylogic2000** [comment]
Oh, or is this about actually making it shareable via social media? Then it should become a story. :)

**Comment by hmkay** [comment]
Nah, this was about renaming "share" into "get link" as proposed by Phil in order for people to not confuse it with sharing it on social media

**Comment by fuzzylogic2000** [comment]
Ah, alright! Then the question is: do we do that and change the wording or do we close this issue?

**Comment by fredewe** [comment]
Wording proposal: "Link" for both languages. The three dots are only visible for initiators/moderators.

**Comment by fuzzylogic2000** [comment]
Ok, we need a decision here! We either close this issue and keep "Share" or change it to "Link". 
From all of the PMs, because the comments are in a4. @fredewe @lthueer @CarolingerSeilchenspringer @hello-kathi @hmkay @maxliqd 
Or you just let @mcastro-lqd decide about the wording!
So, I propose: let's decide via reactions directly on this comment. Add a :+1: for changing it in a4 or a :-1: for keeping it and closing this issue. Voting will close on the 12th of January.

**Comment by phillimorland** [comment]
This is linked to this discussion: https://app.zeplin.io/project/5b051eef7aaa417d2227c55c/screen/61b202609acaf34acb38d20c
If @fredewe @lthueer @CarolingerSeilchenspringer @hello-kathi @hmkay @maxliqd can agree on wording and icons for comments and consult with @mcastro-lqd so he can finalise a design that would be great. We still have an 8pt story for mB comments incld wording update so we can make adjustments when we d that story.

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland good idea to get feedback from all PMs and then I will take over consulting with @mcastro-lqd doing the mB-Story and then get back to PMs with a design-suggestion again.

**Comment by CarolingerSeilchenspringer** [comment]
then we could close the issue here.

**Comment by hmkay** [comment]
I am fine with any of the proposals, I would just like the Enquete to be not affected - but we will archive that anyhow soon!

**Comment by fuzzylogic2000** [comment]
> I am fine with any of the proposals, I would just like the Enquete to be not affected - but we will archive that anyhow soon!

@hmkay as long as we don't update enquete it will not be affected. And I think if we do update it, there might be more and different problems. :p

**Comment by fuzzylogic2000** [comment]
Alright! 4 voted for keeping it, 1 for changing it. But @CarolingerSeilchenspringer will discuss again and add it to a story, right?
