### ISSUE TITLE
Mail issues

### ISSUE THREAD

**Issue by rmader** [liqd/adhocracy-plus#39]
- [x] link broken: ` https://hidden.adhocracy.plushttps://hidden.adhocracy.plus/info/nutzungsbedingungen/` <- only on productive!
- [x] adapt support email address

**Comment by fuzzylogic2000** [comment]
Is this in the footer of the emails? Do you already know why? (was that the settings-PR?)

**Comment by MagdaN** [comment]
@rittermo @rmader we have to set the from-email-address in the contact form. What should it be? And also what email-address should the messages that come via the contact form been sent to?

**Comment by rmader** [comment]
The general from-address is `no-reply@adhocracy.plus`. The contact form should probably go to `start@adhocracy.plus` or `help@adhocracy.plus` I suppose?

**Comment by rittermo** [comment]
The contact form should go to start@

**Comment by fuzzylogic2000** [comment]
should be resolved, but let's keep it open to make supersure to remember to check again!
