### ISSUE TITLE
a+ Moderator mail improvments - user testing

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#391]
Moderation invite email wording needs re-doing
Moderator invite is sent in english as default
~~Moderator mails does not link to enquete~~ seems to work now
After clicking accept moderate link there are 2 typos @hmkay can you say what needs changing?

**Comment by hmkay** [comment]
@phillimorland : I noticed, the English version is only for Enquete! It is fine on adhocracy.plus...?

The current acceptance part says this:

<img width="686" alt="Bildschirmfoto 2020-02-24 um 19 05 54" src="https://user-images.githubusercontent.com/30862422/75178745-f812fb00-5738-11ea-9ce2-7c92c745bdb3.png">

It should say:
"....Wenn Sie akzeptieren, können Sie das Projekt moderieren."

General question to @fredewe : Probably it should say: "Einladung zur Moderation im Projekt *XXX*"as a headline?
