### ISSUE TITLE
a+ debate - wording on edited and deleted comments too long 

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#392]
suggestion for last edited just "edited"
deleted comments, make all info inline?

**Comment by lthueer** [comment]
@fuzzylogic2000 @fredewe let's go for the wording Philli suggested:
English: "Edited"....
German: "Bearbeitet" am ...

**Comment by fuzzylogic2000** [comment]
@lthueer What about the deleted comments? Could you maybe add screenshots where it would need to be?

**Comment by lthueer** [comment]
@fuzzylogic2000 
https://aplus-dev.liqd.net/teststadt-luca/subjects/2021-00309/
Let's move the "deleted by creator/moderator" up in the same line as the time and date (see screenshot below). The wording is fine I think, as it might be important to know whether the creator or moderator deleted the comment.


![Bildschirmfoto 2021-05-18 um 12 29 28](https://user-images.githubusercontent.com/36957474/118636692-3d579880-b7d5-11eb-818a-f3c1238a7ace.png)

**Comment by fuzzylogic2000** [comment]
@lthueer @fredewe The deleted thing can go before that line, but that would be for all projects, then. I think @mcastro-lqd should decide what's best here?

**Comment by fredewe** [comment]
I would also say that @mcastro-lqd should decide that.

**Comment by mcastro-lqd** [comment]
@fredewe @lthueer @fuzzylogic2000 Would that be fine? 

![deleted-comments](https://user-images.githubusercontent.com/59610786/132537905-144383b3-4a3d-4526-9df9-ddfb38622522.jpg)

**Comment by fuzzylogic2000** [comment]
I like it!

**Comment by fredewe** [comment]
Yesss! Looks nice! Thanks!

**Comment by lthueer** [comment]
Perfect!
