### ISSUE TITLE
a+ Moderation: participants not informed their comment is deleated/edited - user testing

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#394]
@fuzzylogic2000 @rmader is that expected behaviour or is that a bug?

**Comment by fuzzylogic2000** [comment]
It's expected. I think, we said, that the moderation needs to decide what to tell the person and do it. We could also add a story to make it behave differently, though. I think it would make sense for big projects to think about this and good moderation again.

**Comment by phillimorland** [comment]
@fuzzylogic2000 when I was moderating, I couldn't work out how to contact the user to inform them
