### ISSUE TITLE
Wording footer Enquete

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#407]
**URL:** https://stage.enquetebeteiligung.de/

Last sentence ("Für die redaktionellen Inhalte...") shouldn´t be there.

Note: Wait for more comments of AG ;)

![Bildschirmfoto 2020-02-25 um 19 02 45](https://user-images.githubusercontent.com/30862422/75273768-c74ac880-5801-11ea-9a81-4b8dfeb1dd00.png)

**Comment by fuzzylogic2000** [comment]
fixed directly on enquet-master
