### ISSUE TITLE
Wording registration Enquete

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#408]
**URL:** https://stage.enquetebeteiligung.de/accounts/signup/?next=/ek-ki/ 
**expected behaviour:** Helptext of "Ich möchte zur Vorstellung...": "Sie werden per Mail zu der Veranstaltung eingeladen."

![Bildschirmfoto 2020-02-25 um 19 23 08](https://user-images.githubusercontent.com/30862422/75275294-9d46d580-5804-11ea-926b-7c299c252063.png)

Note: Wait for comments of AG.

**Comment by fuzzylogic2000** [comment]
fixed directly on enquet-master
