### ISSUE TITLE
When adding a telephonenumber to a project minimum number of digits is too high

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#41]
When adding a telephone number to a project, the telephone numer has to have at least 8 digits which is too much

**Comment by fuzzylogic2000** [comment]
I also thought that there is a strange validation. But seems to be alright and I can't think of a shorter number?!

**Comment by rmader** [comment]
https://en.wikipedia.org/wiki/Seven-digit_dialing

should not be needed for us, right?
