### ISSUE TITLE
IG BCE Link in Email-notification links to hafencity

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#410]
**URL:** https://aplus-hafencity-stage.liqd.net/ig-bce/subjects/2020-00268/?comment=235
**user:** admin
**expected behaviour:** If I click on "Beitrag anzeigen" in the notification mail (Neuer Beitrag) I get to the contribution that was made.
**behaviour:** I get to https://aplus-hafencity-stage.liqd.net/ig-bce/subjects/2020-00268/?comment=235

**Comment by fuzzylogic2000** [comment]
Fixed!
