### ISSUE TITLE
Unclear: Where to put short description of module/project

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#411]
**URL:** https://aplus-igbce-stage.liqd.net/dashboard/modules/debatte-3/module_basic/ AND https://aplus-igbce-stage.liqd.net/dashboard/modules/debatte-3/phases/
**user:** As an initator I am confused because I do not understand the difference between the description of of the module and the project of the debate and I also do not understand where it will appear.

**Comment/Question:** Needs concepting?

**Comment by phillimorland** [comment]
linked https://github.com/liqd/adhocracy4/issues/497

**Comment by phillimorland** [comment]
@mcastro-lqd any idea on a concept or simplification for this?

**Comment by fuzzylogic2000** [comment]
@CarolingerSeilchenspringer Didn't we have a concept/redid the wording for mB here already? Or will it be done? I think this should somehow go over into a concept/a story. @fredewe @lthueer @hmkay

**Comment by janeklqd** [comment]
Closed as this is an own story / enhancement.
