### ISSUE TITLE
a+ Moderation concept

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#413]
Moderation needs a complete concept:
- should users be informed that their comment has been reported - we DID use report_created_email but that was inappropriate needs new idea.
- how do we inform users that their comment has been moderated

linked issue #394

@mcastro-lqd

**Comment by phillimorland** [comment]
#394

**Comment by fuzzylogic2000** [comment]
Haha! We did totally work on that with kosmo! And I will rely on that we somehow think about it there. @hmkay
