### ISSUE TITLE
a+ Account Settings and User Profile concept 

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#414]
New concept needed for both Account settings and View your profile
Things to consider:
* where do I find out what organisations/projects I have been invited to when I haven't participated yet
* where do I find out what organisations I am a member of
* how do I navigate back to my organisation page when I haven't participated yet
     - in IGBCE/redirected sites this can be done by clicking the adhocracy logo, this is not user friendly
* how to explain what is shown in profile activity list? poll activity not included, this is confusing for users
* what should we have in user account settings and in the public profile
* naming of both
* user image and info design needs work desktop and mobile 
linked  #31 #415

@mcastro-lqd

**Comment by fuzzylogic2000** [comment]
@lthueer @fredewe This woudl go together with the story for #415 ! And I think we are even already on it with kosmo, right @hmkay ?

**Comment by lthueer** [comment]
@fuzzylogic2000 I added this to the a+ backlog as well in a news story (story 217)

**Comment by hmkay** [comment]
Yes, @lthueer We already have quite a lot of it covered in KOSMO! Maybe you could make a comment there somewhere in the story in order for us not to forget it. Probably not happening, still it´s probably good to note it down)
