### ISSUE TITLE
User activity feed for participating in debate

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#415]
**behaviour:** the user activity feed does not display correct wording when adding contributions to debate and also only links to project and not to the subject

NOTE: also purposfully excludes poll activity however this seems confusing for user, maybe consider updated wording - "public activities"

**Comment by fuzzylogic2000** [comment]
@fredewe @lthueer Is there a story, where this issue and the related issues can be handled?

**Comment by lthueer** [comment]
@fuzzylogic2000 I added this issue to story #104 in the taiga a+ backlog!
