### ISSUE TITLE
If there is more than one phase only the active one is shown 

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#42]
![Bildschirmfoto 2019-11-07 um 13 59 57](https://user-images.githubusercontent.com/2905743/68391057-fe1fa480-0166-11ea-94f0-4e70bd387280.png)

**Comment by fuzzylogic2000** [comment]
Didn't we just change that @phillimorland ? Or was that in mB? Maybe I also find the time to check.

**Comment by fuzzylogic2000** [comment]
This is already fixed!
