### ISSUE TITLE
#2638 branching Bundestag UI/UX

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#423]
URL: https://stage.enquetebeteiligung.de/

Comments are for Mobile as well. 

![Screenshot_2020-02-27-adhocracy-Enquete-Kommission](https://user-images.githubusercontent.com/59610786/75434859-7bf3ff80-5952-11ea-8ad7-9a867286246e.jpg)

01 – Just to confirm, I remember there was a request to make it using their CI, like greys, etc. Are we keeping our blues and turquoises? If we use their CI, the progress bars, ctas, etc would also need to be changed. 

02 – Wasn't it a request from them to open their official website here? (open new window icon)

03 – I thought the credits were supposed to be on the bottom right. 

04 – The CTAs are different on the organization page (Regular) and debate page (Bold). I would either make them all semi-bold or regular + bold when hovering. 
  
![Screenshot 2020-02-27 at 10 57 57](https://user-images.githubusercontent.com/59610786/75435528-71863580-5953-11ea-96bc-9dbc58cc5811.png)

05 – The button still doesn't change to copied when copied.

**Comment by fuzzylogic2000** [comment]
Cool! Good points!
I will go with the numbers:
01 - @hmkay Do we need to change the colours or is it fine like that?
02 - yes, the link is there when a website is added to the organisation.
03 - This would be a+ as well: I think it was there before and guess it doesn't matter where we put it?! @phillimorland ? @mcastro-lqd just say if we should move it to the bottom and we will do that
04 - a+ as well: yes! Sould be the same! Which option would you prefer @mcastro-lqd ?
05 - a+ as well (actually a4): Maybe we put that in an extra issue? Or @phillimorland could have a look when she's doing comment-stuff in a4 anyway?

**Comment by phillimorland** [comment]
05 - i did look at it in previous sprint but couldn't make behaviour consistent and on zeplin it was deemed low prio so let it for time beng but will look at it again

**Comment by hmkay** [comment]
@fuzzylogic2000 @phillimorland They didnt say anythign about the colours, so lets leave them like that!

**Comment by phillimorland** [comment]
03 - I forgot we had talked about moving it, will do so with next a+ commit
