### ISSUE TITLE
[enquete] Avatar image upload does not work

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#425]
**URL:** https://stage.enquetebeteiligung.de/account/profile/
**user:** participant
**expected behaviour:** avatar pic should be uploaded and shown
**behaviour:** after adding an avatar image file and clicking the save button, the page reloads but no avatar image is shown. no error message is shown either.
**important screensize:** every screensize
**device & browser:** MacOS, Safari 12.1.1 
**Comment/Question:** 

Screenshot? avatar image file attached
![profilepic1](https://user-images.githubusercontent.com/15341015/75454431-b02ce780-5975-11ea-8996-79f12a899766.jpg)

**Comment by phillimorland** [comment]
@rmader is this the media server again?

**Comment by rmader** [comment]
Nope, it's commit 6964115eff4ee5b5c3d919 :/

**Comment by Rineee** [comment]
Fixed by #446
