### ISSUE TITLE
Registration process: constantly underline use of terms and data protection

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#430]
**URL:** https://stage.enquetebeteiligung.de/accounts/signup/?next=/ek-ki/
**user:** user
**expected behaviour:** The link of the ticky box regarding use of terms and data protection are always underlined in order for me to understand that I can click the link (just as in the footer)
**behaviour:** The underline only appears when I hoover above it

**Comment/Question:** How easy is that to implement until going live?

**Comment by fuzzylogic2000** [comment]
I think this was purposely added in another story. But maybe not. Changing it just in the registration is not a big thing, but I think we shouldn't just change it in one place. We need to make it the same site-wide. So, should all links be underlined @mcastro-lqd @fredewe ?

**Comment by fredewe** [comment]
I think that would be more user friendly. For the legal stuff we should definitely do it.
What would you think @mcastro-lqd ?

**Comment by mcastro-lqd** [comment]
@fredewe @fuzzylogic2000 @hmkay 

I agree that in this case it should be always underlined. It could be changed when hover as weel like we have it on the menu or "melden Sie sich bitte an."

![Screenshot 2020-03-04 at 14 55 57](https://user-images.githubusercontent.com/59610786/75886353-5e2e0b00-5e28-11ea-907e-e91b0a2d636e.png)

![Screenshot 2020-03-04 at 14 56 11](https://user-images.githubusercontent.com/59610786/75886350-5cfcde00-5e28-11ea-9bea-bfcc9ce11276.png)

**Comment by hmkay** [comment]
@fuzzylogic2000 I didn´t quite get what you mean....

**Comment by fuzzylogic2000** [comment]
@hmkay I mean that all links on the page should behave the same way. We shouldn't just change it in one place.

**Comment by hmkay** [comment]
@fuzzylogic2000 ah, yes, I got that, I meant the "hover as weel like we have it on the menu or "melden Sie sich bitte an."" 
You mean that we´ll have an underlined link always? I think this would be good and also what @fredewe suggested?
