### ISSUE TITLE
How to include link that opens in new tab in ck-editor?

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#433]
I would like to include links in the ck-editor that open in a new tab. I tried via pop-up and new window (neues Fenster) but either I did it wrong or ck doesn´t like it. Any suggestions?

**Comment by fuzzylogic2000** [comment]
I can't remember if that was possible. I think @CarolingerSeilchenspringer did investigate it in mB. Can you remember anything about that, @phillimorland ?

**Comment by phillimorland** [comment]
@hmkay this issue exists here #123 and is a ck issue that has been tagged with a wontfix as it's not our bug, i'm not sure how possible it would be to change the editor @fuzzylogic2000?

**Comment by fuzzylogic2000** [comment]
Ah, there it was. Thanks, @phillimorland ! Then I'll close because of duplicate. Changing the whole editor needs to be a story.
