### ISSUE TITLE
Make short info on org page editable

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#434]
**URL:** https://stage.enquetebeteiligung.de/

Could we make the short info on the organisation page a little bit more editable?
* bold
* add paragraph
* italic

**Comment by fuzzylogic2000** [comment]
Not really. That would give us problems with the two columns and the design and also I don't know if we can limit the length of the text then. If you need this, make a user story out of this, I would say. Oh, the add paragraph might be possible more easily, but could also very much mess with the two-column design.

**Comment by phillimorland** [comment]
CK doesn't have 2 col design so adding paragraph would cause issues

**Comment by hmkay** [comment]
I will make a story out of that! Please leave it open, until I´m done ;)
