### ISSUE TITLE
cannot add wagtail page to enquete

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#435]
**URL:** https://stage.enquetebeteiligung.de/datenschutzhinweise/
**user:** admin
**expected behaviour:** I can include Datenschutzhinweise on the page as a new wagtail page
**behaviour:** error 404

**Comment by fuzzylogic2000** [comment]
@phillimorland I meant this issue. :) I think there is the inbetween-page (info on aplus) missing to make this work. But the homepage might also need to be kind of added/could be wrong. Could you compare it to aplus if you have time?

**Comment by phillimorland** [comment]
@hmkay fixed, there needs to be an empty page between the wagtail home page and the info pages, I think to make sure there aren't url clashes, so now all the wagtail added pages will have /info/ infront of them 
https://stage.enquetebeteiligung.de/info/datenschutzhinweise/
