### ISSUE TITLE
error page enquete with A+ Logo

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#436]
**URL:** https://stage.enquetebeteiligung.de/datenschutzhinweise/
**user:** admin
**expected behaviour:** all error pages have enquete-Logo
**behaviour:** 404 has adhocracy+ Logo

**Comment/Question:** Did we check all error pages?

**Comment by fuzzylogic2000** [comment]
For me it doesn't have the aplus logo. But this is so weird. I have also seen the aplus logo before on the registration page after we exchanged it.
The error pages apart from the 500 should all have the same logo as everywhere where the organisation is not known (for example the register/login pages or the user settings).

**Comment by phillimorland** [comment]
I also have seen this, I think it is a caching issue as once I cleared mine, I stopped seeing the a+ logo on reg page
