### ISSUE TITLE
Tiles on org page sometimes show wrong date

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#437]
**URL:** https://beteiligung.zukunftsgewerkschaft.de/
**user:** admin
**behaviour:** Tile shows start date 02.03.2020 even though it is the 04.03.2020 in settings...?

**Comment/Question:** Interesting...isn´t it? Or is that just me?

**Comment by fuzzylogic2000** [comment]
Two days off? I've seen it for two hours (which is an issue somewhere), but two days?? That's superweird, because it can't be explained with timezones. Hmm. 
#331

**Comment by fuzzylogic2000** [comment]
This might be something to do with this https://github.com/liqd/adhocracy-plus/issues/1076?

**Comment by fuzzylogic2000** [comment]
Ok, this was the same as always: there was one phase starting on the 4th in the example, but another one starting on the 3rd. So, this is the usual problem: if the project starts at 0:00, it is shown as starting the day before. Pretty sure this is a timezone-problem!

**Comment by hmkay** [comment]
Sherlock!
