### ISSUE TITLE
color of placeholder for start/end date of phases

### ISSUE THREAD

**Issue by Rineee** [liqd/adhocracy-plus#445]
**URL:** 
**user:** 
**expected behaviour:** Placeholder should remain grey until a date is chosen.
**behaviour:** When filling in phases, the placeholder for start/end date turns black when the corresponding field is focused.   
**important screensize:**
**device & browser:** firefox
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/9589411/79235545-0c879000-7e6c-11ea-82c2-b4664e1df4c2.png)

**Comment by phillimorland** [comment]
@Rineee I'm either not quite getting the issue or I cannot reproduce, can you post a screen shot it?

**Comment by Rineee** [comment]
When you click into the date field, the pre-selected date turns dark grey/black, which gives the user the impression, that this date is now selected, but it is not.

**Comment by fuzzylogic2000** [comment]
It does turn darker because it's in focus. We could make the initial value lighter, which would not be good for a11y. 
Soooo, do we want to improve this or can we close @Rineee @phillimorland? :smile:

**Comment by fuzzylogic2000** [comment]
Arrr, on the other hand, for the time of the date it does work like that and the grey value is taken, when (another) date is added and saved. Maybe the date should go away, once the field is in focus. But then, it would behave differently from the other fields that have placeholder values, right? :disappointed:

**Comment by mcastro-lqd** [comment]
@phillimorland To be honest, I never understood if the field in focus should look like the date field or the time one, but from what I see in other forms, it looks like the Time one is the right one. So I would leave like it it's on Time + #666666 Place holder text + #1a1a1a selected text. 

<img width="670" alt="Screenshot 2021-05-11 at 17 47 55" src="https://user-images.githubusercontent.com/59610786/117846471-c32d8e00-b281-11eb-970f-7505dbb6c656.png">
