### ISSUE TITLE
Auto-Fill-in

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#449]
I was told that for sign in, there was filled in the birthdate and not the name or adress. As this has to do with the auto-fill-in of that persons browser: Do we have possibilities to influence what information the auto-fill-in takes from the registration?

Browser: Firefox 73.0.1 (64-Bit)

**Comment by rmader** [comment]
Yep: https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

Will try that.
