### ISSUE TITLE
Error message of form not shown on top of form

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#45]
When I edit project information in the dashboard and add a telephone number with less than 8 digits I will be redirected to the form again showing an error underneath the telephone number field. But as the error is not shown on top of the page I won't see the error and will think that I successfully updated the project information.

related to #41

**Comment by fuzzylogic2000** [comment]
I think we should fix this for all error messages to appear on top of the page and under the corresponding field in the dashboard. 
For a quicker fix here we could add an extra nav-tab for the contact?
