### ISSUE TITLE
Staying logged-in on A+ also from IG BCE page

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#453]
**Comment/Question:** If I change the page from IG BCE prod to adhocracy.plus I do not stay logged in. Is there a possibility to change that? Or is that intended? Or will that confuse user?

**Comment by rmader** [comment]
No, we don't want to change that ATM. Login works via cookies and different domains do not share cookies. So while it would be possible to create a shared login, that would need to be on a different domain altogether. We can come back to this when we have a reasonable number of users using the different sites.
