### ISSUE TITLE
Status bar diverging even though indicates same time

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#457]
**URL:** https://stage.enquetebeteiligung.de/
**user:** non-logged in
**expected behaviour:** all status bars of tiles indicate the same relation of time
**behaviour:** Even though the tiles show the same amount of time still available for participation, the status bar differs
**important screensize:** desktop, mobile
**device & browser:** firefox

**Question**: There was another thing about the tiles and the bar, right?

![Bildschirmfoto 2020-03-04 um 13 51 42](https://user-images.githubusercontent.com/30862422/75881657-cdebc800-5e1f-11ea-9db7-a3015ffa7d9f.png)

**Comment by fuzzylogic2000** [comment]
duplicate: #370
