### ISSUE TITLE
Link in mail of "Neuer Beitrag" leads to project

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#472]
**URL:** https://beteiligung.zukunftsgewerkschaft.de/ig-bce/projects/szenario-2-smartes-wachstum/?comment=545
**user:** initiator/admin
**expected behaviour:** I get directly to the link
**behaviour:** I get to the project overview
**important screensize:** desktop

**Comment/Question:** For other mails, it works. I forward a Mail to @rmader and @fuzzylogic2000 !

**Comment by fuzzylogic2000** [comment]
Yeah, and also linking to the project when we have multi modules does not make a lot of sense. :crying_cat_face:

**Comment by hmkay** [comment]
Can we link directly to the module?

**Comment by fuzzylogic2000** [comment]
No, we can't always link to the module because we might also need to link to the project (if it's a single-module one). We also need to do that for all the back-links on the ideas as we did in mB. And I hope that also works in the emails

**Comment by hmkay** [comment]
Ok. So this also needs a story, I guess! I will write one, please leave it open again until I did that ;)
