### ISSUE TITLE
Document how to set up a production system

### ISSUE THREAD

**Issue by rmader** [liqd/adhocracy-plus#475]
Currently our `README.md` only covers how to start a dev environment, not a production system. We should document that.

Stuff to keep in mind:
 - use systemd for the example (instead of supervisord that we currently use on our production systems - there's no reason to use it anymore nowadays)

**Comment by chrisSCM** [comment]
Yes, that would be nice.

Any hints? I am currently trying to do so.

**Comment by rmader** [comment]
Done in https://github.com/liqd/adhocracy-plus/pull/685. @chrisSCM: sorry that this took so long! Internally we use a quite automated deployment system, so we first had to come up with a reasonably easy solution. Hope the one we went for is easy to understand and use.
