### ISSUE TITLE
Warning in async comments

### ISSUE THREAD

**Issue by rmader** [liqd/adhocracy-plus#477]
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method`

**Comment by phillimorland** [comment]
@rmader where was this error? might be fixed with recent refactoring?

**Comment by rmader** [comment]
Hm, haven't seen this again, closing for now. The error was in the js console in the browser, but don't remember where.
