### ISSUE TITLE
Posted Link of Enquete says "Adhocracy Plus"

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#503]
**URL:** https://enquetebeteiligung.de/subjects/2020-00004/?comment=473
**user:** non-logged in user
**expected behaviour:** If I post a link (of a comment in this case) a short description is displayed about Enquete
**behaviour:** The short description of APlus is displayed
**important platforms:** facebook, Insta, Twitter, channels such as Mattermost
**device & browser:** 
**Comment/Question:** Sorry for not having thought about that before! Hope it is easy fixable...

@fuzzylogic2000 @rmader @phillimorland @Rineee 

I put a critical prio as I will be talking to Enquete today and ask them to spread and share the page and comments

<img width="519" alt="Bildschirmfoto 2020-03-26 um 11 11 00" src="https://user-images.githubusercontent.com/30862422/77635376-c321e000-6f52-11ea-9b1a-4d84cf9b9e1e.png">

**Comment by rmader** [comment]
Should be easy to fix
