### ISSUE TITLE
autofollow not transparent

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#505]
**URL:** 
**user:** registered user
**expected behaviour:** I follow a project only after clicking the follow button
**behaviour:** I automatically follow the project after submitting an idea
**important screensize:**
**device & browser:** 
**Comment/Question:** I like the idea behind the autofollow but think we need to be more transparent there, e.g. asking after submitting an idea if user wants to follow project.

Screenshot?

**Comment by fuzzylogic2000** [comment]
So, we disable it and you write a story? Or we leave it enabled until you wrote a story and we implemented it?

**Comment by fuzzylogic2000** [comment]
Oh, we are in a+! So confusing!

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 guess your logic is a bit fuzzy ;-) yes, in meinBerlin we disabled autofollow but not for a+ I guess.

**Comment by fuzzylogic2000** [comment]
Yes, in mB we disbaled it for users because it used to be broken. :) But also there it's enabled for moderators, right?
So, but here you would propose that users click a button in a modal confirming "yes, I want notifications if someone reacts on my contribution". I think that's a good idea. Wgat do you think @fredewe @hmkay ? Should it become a story that we can prioritize together then or how do we do that in a+?

**Comment by hmkay** [comment]
I like the idea to confirm that I get notifications!
Apart from that, I also like the way of writing a story and then prioritizing it together! That would be then for @fredewe =)

**Comment by fredewe** [comment]
I like that too! 
The official way for a+ is as following:
1. You can all post your feature-ideas for a+ here: https://adhocracy.plus/feedback/projects/deine-ideen-fur-a/
2. I collect them and we all prioritize them as we did here: 
https://adhocracy.plus/liqd/projects/a-feature-prio/
3. Then they are added in our a+ backlog. Comments and prio will be considered.

**Comment by phillimorland** [comment]
@fuzzylogic2000 @hmkay @fredewe has this become a story yet? can this be closed?

**Comment by fredewe** [comment]
Not yet. @CarolingerSeilchenspringer would you like to write a story here:
https://adhocracy.plus/feedback/projects/deine-ideen-fur-a/

**Comment by CarolingerSeilchenspringer** [comment]
@fredewe @phillimorland I wrote a feature-suggestion on a+ feedback so I will close this issue.
