### ISSUE TITLE
Progress circle appearance in dashboard

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#526]
**URL:** https://aplus-dev.liqd.net/teststadt/dashboard/projects/testing/information/
**user:** Initiator
**expected behaviour:** I would expect the two circles to be synchronous. 
**behaviour:** The darker blue progress circle does not appear in line with the lighter blue one.
**important screensize:**
**device & browser:** macOS Catalina (10.15.4), Safari 13.1. 

It works fine in chrome (Version 80.0.3987.163).
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2020-04-07 um 09 50 20](https://user-images.githubusercontent.com/5470479/78643869-3f061b80-78b5-11ea-897b-54ce57349bf2.png)

**Comment by phillimorland** [comment]
this is a intermittent problem that isn't easy to replicate but as the circle will be gone soon we will not fix it

**Comment by fredewe** [comment]
Cool, thanks! So i will close this issue.
