### ISSUE TITLE
Change e-mail content such that it is clear from which organisation it was sent

### ISSUE THREAD

**Issue by Rineee** [liqd/adhocracy-plus#541]
**URL:** 
**user:** 
**expected behaviour:*When sending an e-mail concerning a project (e.g. inviting participants), the text should mention the organisation the project belongs to* 
**behaviour:*text only mentions project* 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/9589411/79251330-49f61880-7e80-11ea-9fdc-3eea8085fc7c.png)

![image](https://user-images.githubusercontent.com/9589411/79250919-c0464b00-7e7f-11ea-845c-96c44202e74a.png)

**Comment by phillimorland** [comment]
@fredewe do we have wording for this?

**Comment by fredewe** [comment]
I would just change the "Verantwortlich für den Inhalt dieser E-mail:" into "Verantwortlich für das Beteiligungsprojekt:"

**Comment by fredewe** [comment]
English version would be: "Responsible for the participation project:"
