### ISSUE TITLE
 #2796 [a+] including individualised data protection, imprint, netiquette and terms of use into org dashboard

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#549]
**URL:** https://aplus-dev.liqd.net/teststadt/dashboard/settings/legal-information

<img width="444" alt="Screenshot 2020-04-16 at 17 03 40" src="https://user-images.githubusercontent.com/59610786/79473538-8e5ef100-8005-11ea-9762-bc5de4e7abd0.png">

1 - I think here we should have the Organization logo cause otherwise there is no way to link to the org page like it used to be without the A+ logo on top. Ive made an option on Zeplin. What do you think? 

![Screenshot-2020-04-16-at-17 05 37](https://user-images.githubusercontent.com/59610786/79473709-cebe6f00-8005-11ea-9330-6fab1de60355.jpg)

2 – If possible, we could also add a bit more spacing between the fields so the division is a bit clearer. I think in general our forms are too squeezed. 

Let me know once you have implemented the Template thing so I can test again, but meanwhile I'll leave this subtask closed.

Thaanks

**Comment by fuzzylogic2000** [comment]
for 1.: I like it, but we could have it the same for the project overview and here? 
Currently it is like that for both all the tabs in the dahboard:
![Screenshot from 2020-04-17 08-09-13](https://user-images.githubusercontent.com/8178179/79537619-eab42600-8082-11ea-859f-c50324c0db32.png)
https://aplus-dev.liqd.net/buro-fur-vielfalt/dashboard/organisations/projects/
![Screenshot from 2020-04-17 08-09-35](https://user-images.githubusercontent.com/8178179/79537629-f1429d80-8082-11ea-941f-089a908dbf0f.png)
https://aplus-dev.liqd.net/ig-bce/dashboard/settings/
But we could also always have the logo on top of the nav on the left. It's more prominent there!

for 2: I will try to unsqueeze the forms platfoem-wide then!

**Comment by phillimorland** [comment]
some of these might be solved with last merge

**Comment by fuzzylogic2000** [comment]
@phillimorland The form-thing or the logo-thing? I had the form-thing still on my list, but maybe I can cross it out, then?
