### ISSUE TITLE
when the project does not have an image, but the organistaion a logo, the logo goes over the tabs

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#551]
**URL:** 
**user:** 
**expected behaviour:** As it is quite common to not have an image for the projects, the styling should work without
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** I think there are some more styles not quite working, also when the organisation does not have a header image or logo.

![Screenshot from 2020-04-17 08-19-20](https://user-images.githubusercontent.com/8178179/79538261-4f23b500-8084-11ea-9a94-ed28ea833b2e.png)

**Comment by phillimorland** [comment]
@fuzzylogic2000 cannot replicate, can you add browser/screen stuff? :)

**Comment by fuzzylogic2000** [comment]
@phillimorland Hmm, the missing image is not the problem, but my chrome, which is displaying the tabs on the left side?! But I think it's the chrome that's broken, it's also not updating :(
