### ISSUE TITLE
#2797 [a+] Big a+ logo at the bottom of mail

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#554]
**URL:** -
**user:** moderator
**expected behaviour:** 
**behaviour:** there is a big a+ logo attached to the mail
**important screensize:**  desktop, not on mobile
**device & browser:** apple mail Version 13.4 (3608.80.23.2.2)
**Comment/Question:** *
If needed or helpful you can add a screenshot. Since issues are public, make sure to not display personal or secret data.
![Bildschirmfoto 2020-04-20 um 11 46 27](https://user-images.githubusercontent.com/5470479/79738104-96b47600-82fc-11ea-8892-c0803e789043.png)

**Comment by Rineee** [comment]
Oh no! Does that concern all mails?

**Comment by fredewe** [comment]
Well i tried the invite mails for moderators and participants and the follow mails. It was for all of them.
