### ISSUE TITLE
#2795 [a+] Making a clear division aplus content and organisation content on all pages

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#563]
**URL:** https://aplus-dev.liqd.net/teststadt/ , etc

Hi, there was a lot of things to check, so I'll put the screenshots here separetely:

<img width="120" alt="Screenshot 2020-04-21 at 16 35 09" src="https://user-images.githubusercontent.com/59610786/79880111-da3bdc80-83ef-11ea-8f79-15dca6a5d093.png">
1 - If possible, could you try to align them here? 

<img width="463" alt="Screenshot 2020-04-21 at 16 26 42" src="https://user-images.githubusercontent.com/59610786/79880436-4d455300-83f0-11ea-830b-01d096452d62.png">
2 – Not urgent but as posted on Zeplin, the tiles should only have shadow when hover. 

<img width="1138" alt="Screenshot 2020-04-21 at 16 25 52" src="https://user-images.githubusercontent.com/59610786/79881230-3d7a3e80-83f1-11ea-9042-f4813f879333.png">
3 – Is it possible to align the text based on the profile picture instead of the hover underline thingie? I would also try to leave some more spacing in the highlighted areas and if possible make the menu text using a slightly bigger text style.

<img width="362" alt="Screenshot 2020-04-21 at 16 21 54" src="https://user-images.githubusercontent.com/59610786/79881545-a2359900-83f1-11ea-8ebd-24e7b0911497.png">
4 – Some CTAs are looking like that. 

<img width="1143" alt="Screenshot 2020-04-21 at 16 20 43" src="https://user-images.githubusercontent.com/59610786/79881651-c6917580-83f1-11ea-9623-0cef70588816.png">
5 – Is that supposed to be this way? 

<img width="448" alt="Screenshot 2020-04-21 at 16 18 08" src="https://user-images.githubusercontent.com/59610786/79881958-2c7dfd00-83f2-11ea-891e-36b9e8566c16.png">
6 – Could we have the profile organization pic aligned to the right? Also fix the go back to be aligned to the bottom of the image + above the question/idea.

<img width="838" alt="Screenshot 2020-04-21 at 16 16 59" src="https://user-images.githubusercontent.com/59610786/79882403-d78eb680-83f2-11ea-95a6-b24eacc07cea.png">
7 – If possible I would also leave some space between all these items, cause it might be too squeezed for the size of the finger when touching on it, including making the menu dropdown wider.

<img width="442" alt="Screenshot 2020-04-21 at 16 16 37" src="https://user-images.githubusercontent.com/59610786/79882948-9f3ba800-83f3-11ea-8be2-a086f47c0514.png">
<img width="241" alt="Screenshot 2020-04-21 at 17 15 03" src="https://user-images.githubusercontent.com/59610786/79882973-a662b600-83f3-11ea-9f82-362b26f37afa.png">
8 – On Mobile, I would leave them one below each other.

<img width="1139" alt="Screenshot 2020-04-21 at 17 17 23" src="https://user-images.githubusercontent.com/59610786/79883283-0194a880-83f4-11ea-8794-41a33c8e522b.png">
9 – Is there a way of making this less prominent?  Either using a grey text style that already exists or eliminating the bold here. I'm sorry but since I had to re-create this file, I still think my text styles arent synchronized with our components properly. 

Thanks a lot! Let me know if you have any questions/need help.

**Comment by phillimorland** [comment]
@mcastro-lqd 
3 – "Is it possible to align the text based on the profile picture instead of the hover underline thingie?" - i'm not sure what you mean by that?
