### ISSUE TITLE
lower (a+) footer changes with being on an organisation page

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#576]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** The sentence "Only the respective operator of the offer is responsible for the editorial content. " is shown on organsiation pages, but not on a+ pages.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

The behaviour makes sense, but does not fit the strict division of plattform and orga footer.
@fredewe Should it stay or go?

**Comment by phillimorland** [comment]
@fuzzylogic2000 @fredewe @mcastro-lqd should we just apply the same colour to header and footer and see how it looks?

**Comment by phillimorland** [comment]
It is now same evrywhere
