### ISSUE TITLE
Colour of the header banner changes depending on org/platform site

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#577]
**URL:** 
**user:** 
**expected behaviour:** 
**behaviour:** The header ribbon and user dropdown have different colours depending if they are on a plattform site or on an organisation site.
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Does this still need to be discussed? @fredewe @mcastro-lqd @phillimorland ?

**Comment by mcastro-lqd** [comment]
Tbh, I don't think this is necessary since now the pages are already well divided and normally other social networks/platforms don't have that as well. But I still think we could re-think the color.

**Comment by fredewe** [comment]
For me this is a design question and not related to the legal requirements. I would say that we can decide what colour we like more and go for that. It is also the call for donation thing btw.

**Comment by phillimorland** [comment]
@mcastro-lqd if you have a colour scheme in mind you can just give me the hex's as and we can check it out as it's easily changeable so no need for screens

**Comment by mcastro-lqd** [comment]
I would leave them like that:
<img width="1437" alt="Screenshot 2020-05-05 at 11 56 50" src="https://user-images.githubusercontent.com/59610786/81054689-8b9a4200-8ec7-11ea-9d22-0c5de62442be.png">

What do you think? @phillimorland @fredewe @fuzzylogic2000

**Comment by phillimorland** [comment]
cool! keeps it inline with a+ branding :)

**Comment by fredewe** [comment]
Nice! Like it!
