### ISSUE TITLE
Module tiles too small for German

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy-plus#61]
![Bildschirmfoto 2019-11-11 um 15 14 53](https://user-images.githubusercontent.com/2905743/68593618-23c5ea00-0496-11ea-938a-95b8ebbef0ff.png)

**Comment by rittermo** [comment]
I would prefer the h3 to be smaller. Actually I think with the base-size increase h1, h2 and h3 should be between .5rem and 1rem smaller for large displays. Maybe we can still do that, @phillimorland ?

**Comment by rittermo** [comment]
oh and the same is true for the dashboard tiles when you create a new project
