### ISSUE TITLE
can't enlarge field for comments

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#611]
**URL:** https://adhocracy.plus/liqd/text/paragraphs/272/
**user:** registered user
**expected behaviour:** I can enlarge the field in which I am writing my comment as the little sign in the corner suggests
**behaviour:** I can't enlarge
**important screensize:**
**device & browser:**  mac catalina, chrome
**Comment/Question:** 

![image](https://user-images.githubusercontent.com/35491681/81704878-a5f79100-946e-11ea-9470-953469cdf40b.png)

**Comment by phillimorland** [comment]
Note: still using the old comments?

**Comment by phillimorland** [comment]
working on dev
