### ISSUE TITLE
#2501[a+] dashboard: adding multiple modules to projects – #2938 UX/UI testing

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#612]
**URL:** https://aplus-dev.liqd.net/teststadt/dashboard/subjects/module/debate-7/
**device & browser:**Desktop + Mobile, firefox 75.0 (64-Bit)*

**Comment/Question:** 

Here are some things I noticed on desktop and mobile: 

**01** – Like the mockup, I would suggest here a small description text explaining that you can add more than one(+accessibility). Also, the CTA should be a bit different right? In case we use this one I would leave the other option on Zeplin then. 
<img width="584" alt="Screenshot 2020-05-12 at 17 59 00" src="https://user-images.githubusercontent.com/59610786/81718738-659f0f80-947c-11ea-9ca2-55f49c2b312b.png">

**02** – Delete has a small line underneath. 
<img width="97" alt="Screenshot 2020-05-12 at 17 59 23" src="https://user-images.githubusercontent.com/59610786/81718984-badb2100-947c-11ea-81b2-f5097ed6bd25.png">

**03** – Is that the right color? I thought this section was supposed to be made using #d9eef7. 
<img width="1427" alt="Screenshot 2020-05-12 at 18 00 33" src="https://user-images.githubusercontent.com/59610786/81719018-c7f81000-947c-11ea-8666-0e9fd4f09633.png">

**04** – Is this notification right? Cause it looks a bit weird. I can't find them in Sandy`s files. 
<img width="573" alt="Screenshot 2020-05-12 at 18 02 51" src="https://user-images.githubusercontent.com/59610786/81719127-f0800a00-947c-11ea-9393-0c56acd8200d.png">

**05** – Or is this the right notification? 
<img width="305" alt="Screenshot 2020-05-12 at 18 04 51" src="https://user-images.githubusercontent.com/59610786/81719217-0f7e9c00-947d-11ea-8185-479ae36cdea3.png">

**06** – There is a white space between the notification and header.
<img width="1214" alt="Screenshot 2020-05-12 at 18 05 50" src="https://user-images.githubusercontent.com/59610786/81719253-1efde500-947d-11ea-96f9-600ebea097aa.png">

**07** – On mobile here, I would leave it like the drop down in the organization page. 
<img width="438" alt="Screenshot 2020-05-12 at 18 07 24" src="https://user-images.githubusercontent.com/59610786/81719291-2b823d80-947d-11ea-8ba4-93e8fd25301b.png">

**08** – Notifications are being cropped on mobile. 
<img width="451" alt="Screenshot 2020-05-12 at 18 08 14" src="https://user-images.githubusercontent.com/59610786/81719388-4eaced00-947d-11ea-9f9e-d47d33029f25.png">

Let me know if you need anything. Thanks a lot! :)

**Comment by phillimorland** [comment]
@mcastro-lqd I just have a few questions, some of them maybe due to holiday brain so i'm sorry if they are stupid :p
04 - that is our error message (I think these are from before Sandy's time, you can see them https://adhocracy.plus/components/)
05 - that is a default browser notification that we have no control over styling
07 - leave what like the organisation dropdown?
08 - what size mobile and browser? have trouble reproducing

**Comment by phillimorland** [comment]
@fredewe for point 01 about some help text, do you have a suggestion for the wording?

**Comment by mcastro-lqd** [comment]
@phillimorland No worries, sometimes its hard to explain them without showing them directly to you hehe :P

03 - Ok, thanks! 
04 - If that's the style, at least, I think it should be indicating just the time instead of the date+time. 
05 - I mentioned this one cause it was different from the red one. If we have no control over them then it's fine. 
07 - Sorry, I mentioned wrong. The menu on mobile could be using the dropdown as we used on the **PROJECT** pages. 
<img width="434" alt="Screenshot 2020-05-19 at 14 28 25" src="https://user-images.githubusercontent.com/59610786/82326454-23765080-99dd-11ea-8f50-8cd7f769530e.png">

08 - That was using Firefox - 375 px width - iPhone :)

**Comment by fredewe** [comment]
> @fredewe for point 01 about some help text, do you have a suggestion for the wording?

German: Bitte fügen Sie ein Modul aus der Auswahl hinzu. Sie können später weitere Module zum Projekt hinzufügen, diese bearbeiten oder wieder entfernen.

English: Please add a module from the list. You can later add more modules to the project, edit them or remove them again.

@mcastro-lqd @phillimorland Would that be ok?

**Comment by phillimorland** [comment]
@mcastro-lqd @fredewe thanks that's great!
