### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by chrisSCM** [liqd/adhocracy-plus#617]
**URL:** 
http://vps35686.alfahosting-vps.de:8000/django-admin

**user:** 
admin

**expected behaviour:** 
I can assign a user the right to be an initiator

**behaviour:** 
I don't see any possibility to assign a group or the right to create projects to a user.
The user initiator@liqd.net doesn't seem to have any special permissions, but he can create projects, whereas user@liqd.net can't.

**important screensize:**
1900x1200

**device & browser:** 
Chrome on Ubuntu 18.04

**Comment/Question:** 

Screenshot?

**Comment by fuzzylogic2000** [comment]
The initiator has to be added to the organisation to get the right to start projects for the respective organisation. If you go to the organisation in the django-admin, you should be able to add other users to the organisation.

**Comment by chrisSCM** [comment]
After installation, there is just one organisation, it's called "liqd-orga". It doesn't have ANY members, so I'm sorry but I don't get the point. The existing default user "initiator@liqd.net" is not a member of any organisation.

**Comment by chrisSCM** [comment]
![image](https://user-images.githubusercontent.com/304104/82024996-fb12ed00-9690-11ea-87df-b90740dc4c89.png)
![image](https://user-images.githubusercontent.com/304104/82025090-1a117f00-9691-11ea-8fd4-ac3ae62d76cb.png)

**Comment by fuzzylogic2000** [comment]
The members are a bit different. They can then take part in private projects of the organisations, they are a member of.
The initiators can be added at the top of the organisation:
![Screenshot from 2020-05-19 13-16-01](https://user-images.githubusercontent.com/8178179/82320118-09d00b80-99d3-11ea-8578-b089f5eba22e.png)

The liqd-orga is from the fixtures. After installation, you could also start with an empty database and add everything yourself.
