### ISSUE TITLE
empty space on aplus-dev landing page

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#618]
**URL:** https://aplus-dev.liqd.net/
**user:** visitor (non logged in)
**expected behaviour:** *the expected behaviour would be, that the header image appears on top of the page*
**behaviour:** *There is an empty space instead of the header image. After the login, it works fine.*
**important screensize:** *mobile and desktop*
**device & browser:** *iPhone and mac, Safari and Chrome*
**Comment/Question:** *Is that something i can fix myself in the CMS?* 

![Bildschirmfoto 2020-05-14 um 09 10 19](https://user-images.githubusercontent.com/5470479/81904779-077d4400-95c4-11ea-8cef-b0d61ce1077a.png)

**Comment by fuzzylogic2000** [comment]
duplicate #604 
(That means, that you can't fix it. And it's everywhere. :()
