### ISSUE TITLE
 Testing #2501: Behaviour when publishing without module

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#620]
**URL:** https://aplus-dev.liqd.net/teststadt/dashboard/projects/manual-testing-2939/basic/
**user:** *initiator*
**expected behaviour:** *It is not possible to publish a project without a module, the progress circle does not show that the project is ready to publish when there is no module*
**behaviour:** *The progress circle shows, that the project is ready to publish, but when you publish you get an error message*
**important screensize:** *mobile? desktop?*
**device & browser:** *macOS, all browsers*
**Comment/Question:** *How do we want the process to be? Not show 3 of 3 when there is no module? Writing somewhere that a minimum of one module is mandatory to publish? I know that we will have the linear progress bar in the future, but we need a solution that fits for now. What do you think?* 

![Bildschirmfoto 2020-05-14 um 09 05 34](https://user-images.githubusercontent.com/5470479/82129761-547c3880-97c5-11ea-9d5e-242f8efea977.png)

**Comment by fuzzylogic2000** [comment]
Yes! The questions here are: 
- do we want to replace it by the progress line anyway? -> Then we shouldn't put a lot of work in here now.
- do we want to/need to release and deploy before (also depends on when that will be in the sprint)? -> In that case we should maybe add another info below the progress circle saying that there was no module added so far and disable the button until one is added to the project

**Comment by fuzzylogic2000** [comment]
@fredewe And the main and most important question for us now: should we fix this before we can close the story and if yes, how?
If we are sure, that we want the progess bar, another option for now would be to just not show the circle and disable the publish-button until the project can be published. That would be fairly easy and not a lot of work put in that we will throw again later anyway.

**Comment by fredewe** [comment]
Thank you for the suggestion @fuzzylogic2000 
I would not put too much work into the circle because we decided to replace it. So it seems to be a feasible approach to disable the publish button when there is no module in the project.
