### ISSUE TITLE
Testing #2501: Hiding module when there is only one module

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#621]
**URL:** https://aplus-dev.liqd.net/teststadt/dashboard/modules/ideenwettbewerb-5/module_basic/
**user:** *initiator*
**expected behaviour:** *When you add a module to a project it is hidden by default. I would expect that i can hide it again, after adding it because it was hidden at the first place.*
**behaviour:** *When you add a single module via the slider it is not possible to hide it again.*
**important screensize:** 
**device & browser:** 
**Comment/Question:** *How do we want that to behave? I get it that we do not want to let people hide a module when there is just one. But when it is hidden by default it seems a bit random when we don't allow to hide it again. We could have the first module added by default. What do you think?* 

![Bildschirmfoto 2020-05-14 um 09 07 57](https://user-images.githubusercontent.com/5470479/82142954-85e61a00-9840-11ea-89fe-5c3bf6ce9932.png)

**Comment by fuzzylogic2000** [comment]
Hmm, I have no idea what a good flow would be here.
The only constraint we have: As soon as a project is published it shouldn't be possible to remove (or even delete) the last module. 
But how to achieve that, I don't know. Adding the first module by default might be ok, but also a bit weird that it behaves different from the other modules then?
@mcastro-lqd help!

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 @fredewe 

In my opinion, I still think one or more modules should still be added manually. 

Hiding them should still be possible even when you have one because when you try to publish the project it says "Project cannot be published. No module is added." anyway. We can still change the message for this situation like "Project cannot be published. Show at least one module in the project".

**Comment by fuzzylogic2000** [comment]
@mcastro-lqd Cool, I will do it like that! 
But there are more things, also @fredewe: 
Currently modules that are not completely filled in can be added. Also to published projects. And then they can't be removed again! What do we do about that? Should only modules that are completely filled in be addable? 
And what if you add a module to a published project by accident? The current solution would be: unpublish the project, remove the module again and then publish the project again. Maybe that's ok as a solution that's only in "emergency-situations", but we should hint at that somehow? Or is the error message "Module cannot be removed from a published project." enough of a hint?

**Comment by fuzzylogic2000** [comment]
Oh, and @fredewe @mcastro-lqd Should we change the error message for publishing modules like proposed? That's from A4, so should also work for mB (but there we could also translate it so that it doesn't change).

**Comment by fredewe** [comment]
> Currently modules that are not completely filled in can be added. Also to published projects. And then they can't be removed again! What do we do about that? Should only modules that are completely filled in be addable?
@fuzzylogic2000 yeah, that would be good, i guess!

> And what if you add a module to a published project by accident? The current solution would be: unpublish the project, remove the module again and then publish the project again. Maybe that's ok as a solution that's only in "emergency-situations", but we should hint at that somehow? Or is the error message "Module cannot be removed from a published project." enough of a hint?
@fuzzylogic2000 it is not perfect, but it works for now. Does not happen very often i would say.

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 Yes, "Module cannot be removed from a published project." sounds good. I agree that it should not happen very often.
