### ISSUE TITLE
#2400: title field cannot be translated

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#64]
For the simple page it is mandatory to give a title field and it is always shown, but it cannot be translated. 

I would prefer either to not have the title field shown or to take the title field out of the „common“ section and make it translatable.

https://hidden.adhocracy.plus/info/support/

**Comment by MagdaN** [comment]
For wagtail it is necessary to have that title field - so we can't get rid of it. We could either just not display it (and keep it in the common sections) and you can add a header via a richtext block or we could add two additional fields for english and german but there would still be the title field in common. What do you prefer?

**Comment by rittermo** [comment]
Thank you, @MagdaN. I would prefer to add the heading via a richtext block, as it gives the most flexibility.
