### ISSUE TITLE
#2400: two column view of comuns images cta block doesn’t work

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#66]
The two-column view of the comuns images cta block still shows the content in one column.

https://hidden.adhocracy.plus/info/support/

**Comment by phillimorland** [comment]
@rittermo I think this is a naming problem, the 'column image cta block' is in fact the 'list column and image column cta block' from the landing page which is also used in the simple page design as the last element so it doesn't not work with an image in the first col, I need to rethink the name.
If you want to have a 2 col image cta, you can use the col block and add an image with streamfields, does that make it clearer?
