### ISSUE TITLE
Slipped Elements

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#664]
**URL:** https://live.browserstack.com/dashboard#os=iOS&os_version=7.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Faplus-stage.liqd.net%2Fliqd%2Fprojects%2Ffwesd%2F&speed=1
**user:** all
**expected behaviour:** subtitles and logos are displayed fully and correctly
**behaviour:** search bar, project overview button and the Organisation's logo are not shifted
**important screensize:** 7.9 in - 4.7 x 6.3 in
**device & browser:** iPad Mini 2 (iOS v7), safari browser
**Comment/Question:** Problem does only occur with Ipad mini 2, other Ipads and Iphones work properly

![Bildschirmfoto 2020-06-23 um 15 49 05](https://user-images.githubusercontent.com/36957474/85412866-59719c00-b56a-11ea-9113-24f93452db71.png)
![Bildschirmfoto 2020-06-23 um 15 49 25](https://user-images.githubusercontent.com/36957474/85412869-5a0a3280-b56a-11ea-8c3f-defab2047e69.png)

**Comment by rmader** [comment]
Closing as wontfix as we do not support browsers that are unsupported by their vendors :/
