### ISSUE TITLE
Email for moderators: Logo overlaps header

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#672]
**URL:** -
**user:** moderator
**expected behaviour:** the logo is above the header
**behaviour:** the logo overlaps the header
**important screensize:** Computer Screensize
**device & browser:** macOS/Apple Mail, on iOS it worked well
**Comment/Question:** 

Screenshot?
![Bildschirmfoto 2020-06-29 um 18 30 14](https://user-images.githubusercontent.com/5470479/86031934-d7381a80-ba36-11ea-91a3-d2df7a9be315.png)

**Comment by phillimorland** [comment]
@fredewe is this still an issue, I can't replicate and I think we have adjusted the logo recently so maybe it's solved

**Comment by fredewe** [comment]
@phillimorland i think it was fixed by Rine. :)
