### ISSUE TITLE
Mail for moderators: Language mix or missing german wording

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#673]
**URL:** -
**user:** moderators
**expected behaviour:** As a moderator i would expect a consistant language in the mailing
**behaviour:** There seems to be a mix of english and german in the mailing or a missing german wording for "responsible for the participation project"
**important screensize:**-
**device & browser:** -
**Comment/Question:** 
Is the german wording missing for this one? 
Screenshot?
![IMG_1055](https://user-images.githubusercontent.com/5470479/86033732-b32a0880-ba39-11ea-8096-900396a937e0.PNG)

**Comment by fuzzylogic2000** [comment]
@fredewe This was fixed with moving the email translations to transifex, right?

**Comment by fredewe** [comment]
@fuzzylogic2000 yes, i think it works fine. Thanks
