### ISSUE TITLE
pictures in newsletter wider than background

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#682]
**URL:** newsletter mail
**user:** follower
**expected behaviour:** if a picture is added it should not be larger than the mail background
**behaviour:** picture and with it the text is wider than background for all pictures larger than 600 px
**important screensize:**
**device & browser:** apple mail
**Comment/Question:** we had the same problem at meinBerlin and couldn't solve it. We decided to add a helptext there into the newsletter form. In meinBerlin the restrictions are a bit wider (650) but I tested for a+ and here it should be 600 px.

Screenshot?
![image](https://user-images.githubusercontent.com/35491681/86807827-80f05a80-c07a-11ea-97d1-bf02e11d4cf8.png)

**Comment by Rineee** [comment]
@lthueer As Caro already mentioned above, we had the same problem in mB and decided to add a helptext saying that the image should be larger than 600px, see conversation here: https://github.com/liqd/a4-meinberlin/issues/2933
Would you be ok with that solution?

**Comment by lthueer** [comment]
@Rineee Alright, sounds good to me. Then we do it the same way!

**Comment by Rineee** [comment]
Strangely for wider pictures (eg width 1300) it looks good again.. hm. But I will add the helptext now!
