### ISSUE TITLE
map does not load

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#686]
**URL:** https://adhocracy.plus/musterorganisation/projects/module/brainstorming-mit-karte-4/
**user:** any
**expected behaviour:** i can see map
**behaviour:** map does not load at least in citizens budget and brainstorming with map
**important screensize:**
**device & browser:** mac, chrome
**Comment/Question:** 

Screenshot?
<img width="572" alt="Bildschirmfoto 2020-07-13 um 11 05 54" src="https://user-images.githubusercontent.com/35491681/87286414-21ba9c00-c4f9-11ea-8b29-0615a637ec86.png">

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer what version of Chrome are you using? have tested on 2 machines and maps are loading fine

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland Version 83.0.4103.116. Could it be any other setting?

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer that's same version as mine, can you clear your cache and let me know? that's all i can think of, it's working on my mobile and 2 laptops so I would normally close this

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland no, clearing my cache did not help nor did a restart of my mac.

**Comment by phillimorland** [comment]
cannot reproduce on multiple devices so will close

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer i've added a reminder to myself to keep an eye on maps, will reopen if there is a case on another device

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I deinstalled my ghostery plug in, that helped. Reinstalling it, map is still working.
