### ISSUE TITLE
Line break doesn't work

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#688]
**URL:** https://adhocracy.plus/
**user:** all
**expected behaviour:** line break
**behaviour:** no line break, thus, title and description are not separated
**important screensize:** desktop (only on big monitor, break point from 652.75 px)
**device & browser:** all
**Comment/Question:** homepage; only for "Individualisieren Sie Ihre Organisationsseite" box

![Bildschirmfoto 2020-07-14 um 09 03 21](https://user-images.githubusercontent.com/36957474/87395974-7a9a3b00-c5b2-11ea-98ab-09a517a68ba3.png)

![Bildschirmfoto 2020-07-14 um 09 17 18](https://user-images.githubusercontent.com/36957474/87396329-f5fbec80-c5b2-11ea-805e-99dd11cbeb03.png)

**Comment by phillimorland** [comment]
@lthueer this is an oddity with wagtail, the best way I have found of solving it is to copy and past text where the formatting is working and then replace the text but do it inline, don't delete copied text all at once, it's a pain but it seems to be something to do with the editor in wagtail. I'll leave this open as a reminder

**Comment by fuzzylogic2000** [comment]
@lthueer @phillimorland Maybe we can put this info into the wiki? Or where would be a good place?

**Comment by lthueer** [comment]
@fuzzylogic2000 I think there is no real place in the wiki. I'll add a comment in the a+ wiki project page

**Comment by fuzzylogic2000** [comment]
@lthueer Thank you!
