### ISSUE TITLE
#2400: italics for image caption

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#70]
Since the caption text looks very similar to the normal paragraphs, we should set it always in italics, so it has a bit of a visual differentiation. Sorry, this was not part of the original design.

**Comment by fuzzylogic2000** [comment]
But everywhere, not only on the simple pages, right?

**Comment by rittermo** [comment]
Yes everywhere would be ideal.

**Comment by fuzzylogic2000** [comment]
Oh, and they should always be in the right lower corner? Not like here?
![Screenshot from 2019-11-12 10-25-01](https://user-images.githubusercontent.com/8178179/68658970-b918bb00-0536-11ea-8ecb-ccf37c5872c1.png)

(And whoever does it, maybe also check the dashboyrd project list and make the copyright overflow/cut off.)

**Comment by fuzzylogic2000** [comment]
@rittermo The caption on the simple pages is underneath the images, but everywhere else the copyright is displayed on the image. I confused that, so we will only make the caption on the simple pages cursive?!

**Comment by rittermo** [comment]
@fuzzylogic2000 Yes, please only change the ones on simple pages then.

**Comment by MagdaN** [comment]
@fuzzylogic2000 @rittermo I changed all captions on cms pages. Copyright things on the rest of the platform stay the same, like here: https://aplus-dev.liqd.net/components/#cl-copyright

**Comment by rittermo** [comment]
@MagdaN Even better! Thank you!
