### ISSUE TITLE
Language switch should probably show languages in their own language

### ISSUE THREAD

**Issue by rmader** [liqd/adhocracy-plus#717]
Otherwise people might have problems choosing their right language :/

![image](https://user-images.githubusercontent.com/6313774/88800251-242f1e00-d1a8-11ea-828c-d0c3b74ee53c.png)

**Comment by rmader** [comment]
Closed by https://github.com/liqd/adhocracy-plus/pull/941

**Comment by Rineee** [comment]
This is an issue again with the new languages:

![image](https://user-images.githubusercontent.com/9589411/111286601-a76f8800-8642-11eb-9784-0adef4861396.png)

**Comment by fuzzylogic2000** [comment]
Yes, I also saw that. And thought that we could make the strings not translateable to keep the languages. But that might not work, because it's likely from some tuple in the settings?! Maybe worth to have a look, though. @Rineee
