### ISSUE TITLE
Landing page / CMS: layout becomes smaller on/after widest breakpoint

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#73]
There is a small oddity I noticed for viewports wider than 2000px. Rather than stop expanding, the layout reverts back to a more narrow layout. Ideally we should either choose a more narrow max-width for the breakpoint or make the max-with after the largest breakpoint smaller.
![Bildschirmfoto 2019-11-12 um 10 23 17](https://user-images.githubusercontent.com/15341015/68658973-ba49e800-0536-11ea-8daf-9448d0be0e88.png)

**Comment by phillimorland** [comment]
kind of linked to #21
