### ISSUE TITLE
DIID: choose module blueprints: colours don't match

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#739]
**URL:** https://teilhabe.diid.hhu.de/testorganisation/dashboard/projects/caros-testprojekt/blueprints/
**user:** initiator
**expected behaviour:** identical colours
**behaviour:** the blue colour of the module-images and the backgroundcolour don't match
**important screensize:**
**device & browser:** mac, chrome
**Comment/Question:** 

Screenshot?
![image](https://user-images.githubusercontent.com/35491681/90011670-49d91e80-dca2-11ea-87fb-3d1d04debd9d.png)

**Comment by fuzzylogic2000** [comment]
Haha, good catch! Looks like we shouldn't use primary there. :)
