### ISSUE TITLE
#3102 [DIID] change platform styling

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#740]
**URL:** https://diid-dev.liqd.net/

**Comment/Question:** 

01 – Random question: Do we need to add languages here or is DIID going to be only in German?
<img width="112" alt="Screenshot 2020-08-11 at 18 04 25" src="https://user-images.githubusercontent.com/59610786/90033776-21601d00-dcc0-11ea-8971-c521426fe7e0.png">

02 – Is it going to appear the logo here after uploading an image? 
<img width="210" alt="Screenshot 2020-08-11 at 18 03 52" src="https://user-images.githubusercontent.com/59610786/90033860-389f0a80-dcc0-11ea-8164-09e9b5077a28.png">

03 – Is it possible to center this text? Also the Fail color is E9AAB3
<img width="580" alt="Screenshot 2020-08-11 at 18 02 36" src="https://user-images.githubusercontent.com/59610786/90033941-510f2500-dcc0-11ea-9fc9-a8807acb2fd9.png">
https://app.zeplin.io/project/5f05dd0342a6025af2786627/screen/5f05e6e74417237955d9b36a/

04 – Regarding the idea tiles + Submit Idea Button, I did the whole screen cause it was easier to explain: 
https://app.zeplin.io/project/5f05dd0342a6025af2786627/screen/5f3408482228711c4b444cff/

05 – Test Organization here looks a bit off:
![Screenshot 2020-08-12 at 17 24 28](https://user-images.githubusercontent.com/59610786/90034266-afd49e80-dcc0-11ea-9d5c-7cd48f1ba4a7.png)

I didn't manage to see the Attention Color one but the rest seems correct! 

Thanks!!!

**Comment by phillimorland** [comment]
@mcastro-lqd 
01 - that will be their decision weather or not they keep as they now have a complete copy of it running. I think they have international students so they may want to?!
02 - yes the logo will appear there once they have one set
03 - this is a a+ issue so will add another there and once we do a rebase it will be added to the DIID master. Colour, will check why it's not working

**Comment by phillimorland** [comment]
03 - error message centering #743

**Comment by phillimorland** [comment]
04 - tile issue #749
