### ISSUE TITLE
DIID/a+: colour of green check-dot not well visible on background

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#747]
**URL:** project in dashboard
**user:** initiator
**expected behaviour:** 
**behaviour:** the green check-dot in the left navigation indicating that project/module info is completed is not well visible. I noticed while testing DIID but this is also true for a+. I would say this is not barrier free.
**important screensize:**
**device & browser:** chrome, mac
**Comment/Question:** 

Screenshot?

![image](https://user-images.githubusercontent.com/35491681/90231317-487f3180-de1b-11ea-92c5-e89c8d938e2a.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer the we need a different success colour, @mcastro-lqd can we change it?
