### ISSUE TITLE
DIID: dashboard: colour of info-thing

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#748]
**URL:** dashboard, Grundeinstellung in project
**user:** initiator
**expected behaviour:** 
**behaviour:** 
**important screensize:**
**device & browser:** 
**Comment/Question:** is the blue colour behind "ihr Bild wird hochgeladen..." part of the right colour spectrum? It does not seem to be among the colours I found in Zeplin. @mcastro-lqd did you already check the colours in dashboard?

Screenshot?

![image](https://user-images.githubusercontent.com/35491681/90232000-4c5f8380-de1c-11ea-819c-6a7d12340408.png)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer @mcastro-lqd there is no info colour on zeplin so this reverts to the default, which blue should the info colour be?

**Comment by mcastro-lqd** [comment]
@CarolingerSeilchenspringer @phillimorland I suggest using the Neutral #D9E9F4

**Comment by fuzzylogic2000** [comment]
I am confused. Is this fixed or not. Can you remember @phillimorland ?

**Comment by fuzzylogic2000** [comment]
Sorry, that was not too hard to check... https://github.com/liqd/adhocracy-plus/blob/diid-master/adhocracy-plus/assets/scss/_variables.scss It is fixed @phillimorland !
