### ISSUE TITLE
Idea tiles and submit idea button

### ISSUE THREAD

**Issue by phillimorland** [liqd/adhocracy-plus#749]
Carry over issue from DIID but should be for whole platform 
04 – Regarding the idea tiles + Submit Idea Button, I did the whole screen cause it was easier to explain:
https://app.zeplin.io/project/5f05dd0342a6025af2786627/screen/5f3408482228711c4b444cff/
Screenshot?

**Comment by phillimorland** [comment]
@mcastro-lqd ok looking into this, the list of ideas are not tiles, they are just list items. do we want list items and project/subject tiles to all look the same?

**Comment by phillimorland** [comment]
@mcastro-lqd Here is what these lists cureently look like in the different modules:
https://aplus-dev.liqd.net/teststadt/projects/idea-challenge-with-map/?mode=list

**Comment by mcastro-lqd** [comment]
> @mcastro-lqd Here is what these lists currently look like at moment in couple different modules, adding the shadow from design looks a bit weird with the background colour, should I remove the background colour from our list elements? I just want to check before doing it as it effects all modules with lists.
> https://aplus-dev.liqd.net/teststadt/projects/idea-challenge-with-map/?mode=list
> https://aplus-dev.liqd.net/teststadt/projects/lorem-ipsum/

Yes, I'm actually already making new designs using white background instead cause since we had to make aplus legal and separate the organisation content from our content using the grey background, I wouldn't use it inside the organisation content.

**Comment by fuzzylogic2000** [comment]
@phillimorland @mcastro-lqd What's the status? Is it done? Should it be part of a story/redesign? Or what exactly is still missing?

**Comment by mcastro-lqd** [comment]
@fuzzylogic2000 I think its kind of done, from what I got we are changing little by little each time we work on improving a  module

**Comment by fuzzylogic2000** [comment]
Nice! As we already remember to improve in small steps, I will close this issue!
