### ISSUE TITLE
shorten questions url from debate module

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/adhocracy-plus#774]
**URL:** 
**user:** 
**expected behaviour:** The url should be short to be easy to type into your smartphone at an event.
**behaviour:** To make it work with our other modules and the redirects we regularly set up, we use our usual url pattern which also includes the organisation. This can get quite long.
**important screensize:**
**device & browser:** 
**Comment/Question:** Any ideas? Can we have two urls? The proper one for the redirect and a somehow shortened one for the event?

**Comment by rmader** [comment]
We should indeed be able to have some kind of short-url and it should be possible to have that additionally to the verbose one - I wonder if we could even have that generalized i.e. for all kinds of things. IIUC, it would just need a unique id of an object, which somehow needs to allow us to retrieve the organization/project/module...

**Comment by fuzzylogic2000** [comment]
Or we just use the pks. Either only in this case or we always make them also work?

**Comment by fuzzylogic2000** [comment]
@fredewe @lthueer Do we need that? Then you should add a story! Maybe we also need it in mB @CarolingerSeilchenspringer ?

**Comment by lthueer** [comment]
I've added a story to the a+ backlog.

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 I also added a story to mB backlog, thanks!
