### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by mitar** [liqd/adhocracy-plus#783]
Is there a Docker image available somewhere? Is there any interest for making it?

**Comment by rmader** [comment]
Hey @mitar, not right now. The setup process is still quite involving and needs some manual work. So for the moment you can follow the instructions on https://github.com/liqd/adhocracy-plus/blob/master/docs/installation_prod.md, which should work just fine within a docker image. We might reconsider once we're closer to a one-click solution.
