### ISSUE TITLE
interactive event - wording of filter 'select category' should be 'select characteristic'

### ISSUE THREAD

**Issue by Rineee** [liqd/adhocracy-plus#799]
**URL:** 
**user:** 
**expected behaviour:*wording of filter to select characteristic is 'select characteristic'* 
**behaviour:*it is 'select category' * 
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?
![grafik](https://user-images.githubusercontent.com/9589411/93436251-d347c600-f8ca-11ea-81d7-c067aaad9f0e.png)

**Comment by phillimorland** [comment]
Characteristic doesn't really work in English; I would say we could just write 'Selection' with dropdown arrow

**Comment by Rineee** [comment]
@lthueer @phillimorland @fuzzylogic2000 So I think we need a new wording here.. do you have any ideas what we could name it? I think 'Merkmal' in german works ok, right? But in english, I am not sure.. possible translations for it are feature, characteristic, property, attribute

**Comment by fuzzylogic2000** [comment]
Yes, we need a different wording! I am not even sure about Merkmal, but it seems the best bet? Maybe @CarolingerSeilchenspringer , @hmkay or @fredewe also have an idea?

**Comment by lthueer** [comment]
@Rineee @Rineee maybe using "label" and "Merkmal" would work out. At least that's the way we use it for the brainstorming module. What do the others think?

**Comment by CarolingerSeilchenspringer** [comment]
I have been thinking about this quite a bit and it is difficult. I think it would be best to not use merkmale (labels) nor Kategorien (categories) as they are used for different things in other modules. Characteristics is difficult in German (Charakteristika?). Would "Gruppe/group" work? I mean you could also use this feature for e.g. types of questions but of course our intention of the module is to have equal participation among different groups of people.

**Comment by CarolingerSeilchenspringer** [comment]
ok, we already do use group in our software, but only django, not in frontend.

**Comment by Rineee** [comment]
Hm, I would suggest to leave this issue out of the milestone until we decide on a better wording?

**Comment by fuzzylogic2000** [comment]
@lthueer @fredewe We can't do this issue until we actually get a wording, so we will take it out of the milestone.
@lthueer In the interactive event, the categories are there for the people to label themselves, like in male, female, diverse or beginner, intermediate, expert, while in the brainstorming module they are for ideas, like question, suggestion or important, nth.
So, for people categories seems a bit strange?

**Comment by fredewe** [comment]
What about "Criteria"/ "Eigenschaft"?

**Comment by fredewe** [comment]
Or "attribute"/"Attribut"?

**Comment by CarolingerSeilchenspringer** [comment]
@fredewe @lthueer and I discussed wording and I wrote an issue for meinBerlin: https://github.com/liqd/a4-meinberlin/issues/3290. Please copy the wording from there.

**Comment by fuzzylogic2000** [comment]
@Rineee I guess, we need to still port this over from mB? Maybe now that we work on the liveQuestions dashboard is a good time to do it? I will just add it to the milestone and we see if we get there!

**Comment by lthueer** [comment]
@fuzzylogic2000 @Rineee @fredewe I think we solved this problem already. We changed the wording to affiliations (Zugehörigkeiten) with the last release. Please close the issue if you agree

![Bildschirmfoto 2021-05-06 um 15 54 28](https://user-images.githubusercontent.com/36957474/117310224-5c743300-ae83-11eb-9986-2dab9003624d.png)

**Comment by fuzzylogic2000** [comment]
Nice! Then we only forgot to close it!
