### ISSUE TITLE
DIID: a+ still mentioned in registration form

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#800]
**URL:** https://teilhabe.diid.hhu.de/accounts/signup/?next=%2Fdiid%2F
**user:** unregistered user
**expected behaviour:** 
**behaviour:**
**important screensize:**
**device & browser:** 
**Comment/Question:** please replace with teilhabe.diid.hhu.de

Screenshot?

![image](https://user-images.githubusercontent.com/35491681/93740909-b291b000-fbeb-11ea-926c-7b70d707930e.png)

**Comment by CarolingerSeilchenspringer** [comment]
I set the prio on high because we have to release it soon but not necessarily within 7 days. Maybe wait for @rmader with a release as there are other questions regarding DIID? But I don't know if they are up to them to solve or to us. Just to avoid two releases.

**Comment by fuzzylogic2000** [comment]
I guess this will be solved in the registration form story?! 
There might be other places that still say a+, but we never had a story about it as I can remember? So, it would be for them to be changed if there is more?

**Comment by CarolingerSeilchenspringer** [comment]
@fuzzylogic2000 i didn't write it in the story so do what is best for you to remember to change it :-)

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer shall we just replace adhocracy with DIID?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland please replace with teilhabe.diid.hhu.de, they don't have a real name for their platform.
