### ISSUE TITLE
DIID: Fotoupload via CK editor does not work

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#801]
DIID wrote: Bei einigen Texteditoren im Dashboard gibt es ja die Verlinkungsoption. Dort lassen sich offenbar auch einige Bilder/Dateien hochladen. Allerdings kommt dann die Fehlermeldung: ‚Während des Hochladens der Datei ist ein HTTP-Fehler aufgetreten (403: Verboten).‘

Is that up to us to solve or something their admin needs to change?
@rmader do you know ?? 

see my comment on release and prio in story #800

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer 
This might be something to do with how we handle images but the comment isn't very clear, do you still have access so we can test or is your login also dead? if so can you ask following questions
What files types are they trying to upload?
Are all ck editors in the dashboard behaving this way or just some? if so which ones?
Are they trying to upload an image via the Image info, Link or Upload tab of the image uploader pop-up?
Maybe a screen shot would help?

**Comment by CarolingerSeilchenspringer** [comment]
@phillimorland I just tried again and also got the error message. I tried to upload a jpg of 418 kb.

<img width="514" alt="Bildschirmfoto 2020-10-01 um 12 18 41" src="https://user-images.githubusercontent.com/35491681/94797567-9a3a4600-03e0-11eb-91d3-f0aa567b3a3b.png">

**Comment by fuzzylogic2000** [comment]
@rmader That must be something wrong with their settings?!

**Comment by rmader** [comment]
That could well be indeed - will look into it, maybe I forgot to add something to the example config :/

**Comment by fuzzylogic2000** [comment]
@rmader You already wrote an email (at least) about this, right? Can it be closed?
