### ISSUE TITLE
DIID can't get Netiquette in Metanaviagtion

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#802]
**URL:** https://teilhabe.diid.hhu.de/info/netiquette/
**user:** 
**expected behaviour:** I can see netiquette
**behaviour:** I see 404 error
**important screensize:**
**device & browser:** 
**Comment/Question:** I didn't manage to link the existing netiquette page to the metanavigation. It did work with the other pages there. Can somebody help?

Screenshot?

**Comment by CarolingerSeilchenspringer** [comment]
regarding the prio see my comment in story #800

**Comment by phillimorland** [comment]
@CarolingerSeilchenspringer they are miss-spelling the slug in wagtail, should be 'netiquettes' then should show up
