### ISSUE TITLE
django admin: Having to add a topic for the project (meinBerlin leftover?)

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#809]
**URL:** https://enquetebeteiligung.de/django-admin/a4projects/project/12/change/
**user:** admin
**expected behaviour:** I can add moderators in the django admin
**behaviour:** I can only add moderators in the django admin if I add a topic of the project

**Comment/Question:** Is this an relict of meinBerlin? And does it have any impact in a+ if I just add a category?

![Bildschirmfoto 2020-09-23 um 09 16 54](https://user-images.githubusercontent.com/30862422/93979781-0b914d80-fd7e-11ea-9253-7b6d24d76acb.png)

@fredewe I dunno how important this is - probably not as important.

**Comment by fredewe** [comment]
@hmkay it is not that important. But i was also confused first. :)
