### ISSUE TITLE
Organization name should link back to the org

### ISSUE THREAD

**Issue by combinatorist** [liqd/adhocracy-plus#811]
**URL:**
https://adhocracy.plus/model-organization/projects/pose-your-questions-to-the-representative-from-mod/
**user:** 
**expected behaviour:** 
Under "Responsible for the content on this page", I expect "Model Organization" to be a link back the organization's page (on adhocracy - i.e. https://adhocracy.plus/model-organization/).
**behaviour:** 
When I clicked on the org name, nothing happened.
**important screensize:**
**device & browser:** 
**Comment/Question:** 
I was afraid for a moment that there was no way to navigate back up out of the project to the organization until I tried the a+ logo near the top of the page. This appears to be the only link "back" to the org. And, obviously, with a real org, it would be their logo which would be a better clue than this ahocracy logo. But, I still think it would be helpful if the org name at the bottom of the page was linked.

**Comment by combinatorist** [comment]
I can provide additional details, but I didn't think they were necessary for this issue.

**Comment by fuzzylogic2000** [comment]
Yes, you're right, a link would be nice here! Do you want to fix it?

**Comment by rmader** [comment]
This apparently got fixed somewhere on the way.

**Comment by combinatorist** [comment]
Thanks to whoever fixed it! :)
