### ISSUE TITLE
testing #2929: Fields in organization form in different languages: missing german wording

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy-plus#820]
**URL:** https://aplus-dev.liqd.net/frede-test/dashboard/settings/
**user:** initiator
**expected behaviour:** there is a german wording when language is set to german
**behaviour:** there is an english wording instead
**important screensize:** 
**device & browser:** 
**Comment/Question:** 

The german wording would be: 

**Verfügbarkeit von Sprachen für Ihre Organisation**
Bearbeiten Sie hier die Inhalte Ihrer Seite in den verfügbaren Sprachen. Sie können Sprachen hinzufügen oder entfernen.

**Comment by fuzzylogic2000** [comment]
All the strings are on transifex now! But, I guess, I will still add this translation, then. :)
