### ISSUE TITLE
# 2929 testing deleting languages (language availability)

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#827]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/dashboard/settings/
**user:** initiator
**expected behaviour:** deleting languages in the organization's settings
**behaviour:** sometimes the language buttom does not disappear when trying to delete a language. Other times an error 500 occurs when trying to delete a language. 
**important screensize:** all
**device & browser:** all
**Comment/Question:** I could not identify a pattern when that happens, but it appears to be related to the selection of the default language for E-mails.

**Comment by fuzzylogic2000** [comment]
This seems to be a problem with the saving? When a language is removed and that is then saved, the language is either not gone or @lthueer gets a 500.

**Comment by Rineee** [comment]
@lthueer I think this should be fixed now, but can you please test again, just to be sure? Thank you!

**Comment by lthueer** [comment]
@Rineee it works perfectly!

**Comment by Rineee** [comment]
Wohoooo!
