### ISSUE TITLE
#3328: default language in organization settings

### ISSUE THREAD

**Issue by lthueer** [liqd/adhocracy-plus#828]
**URL:** https://aplus-dev.liqd.net/teststadt-luca/dashboard/settings/
**user:** all
**expected behaviour:** E-mails are written in the selected default language is 
**behaviour:** 

**If the default language is dutch**
invitation registered user: not working (German)
invitation non-registered user: not working (English)
invitation moderator: not working (German)
new project notification: not working (German)
newsletter: not arriving at all (following project+as participant)
comment reaction: not working (German)

**if the default language is english**
invitation registered user: not working (German)
new project notification: not working (German)
newsletter: not arriving at all (following project+as participant)
comment reaction: not working (German)
(the invitation for non-registered users and moderators works, if default language is english)

**important screensize:** 
**device & browser:** 
**Comment/Question:**

**Comment by fuzzylogic2000** [comment]
If a user is registered, the email is sent in the language the user has set. I guess that's also true for the moderator? Or did that also go to an unregistered address?
As most translations are not there yet, you need to check the footer for the language of the email. Is that English or Dutch for "invitation non-registered user: not working (English)"?
Could you please add a separate issue for the newsletter?

**Comment by fuzzylogic2000** [comment]
Oh, or can it be, that you're following the project and sending the newsletter as the same user?

**Comment by lthueer** [comment]
This issue is closed after Luca talked to Katharina
