### ISSUE TITLE
#3433 Organisation page styling including semi public projects

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#911]
**URL:** https://aplus-dev.liqd.net/teststadt/
**URL:** https://diid-dev.liqd.net/food/
**important screensize:** *Mobile and Desktop?*
**device & browser:** *Version 14.0 (15610.1.28.1.9, 15610)*
**Comment/Question:** *Hey guys, I was looking through the semi private thing and there are some styling issues in both DIID and a+. I also added the original design in case you can't find the link*

**a+** 
m - [201105-m-aplus-semi-private-project.pdf](https://github.com/liqd/adhocracy-plus/files/5495656/201105-m-aplus-semi-private-project.pdf)

**DIID**
d - [201105-d-diid-semi-private-project.pdf](https://github.com/liqd/adhocracy-plus/files/5495661/201105-d-diid-semi-private-project.pdf)

m - [201105-m-diid-semi-private-project.pdf](https://github.com/liqd/adhocracy-plus/files/5495665/201105-m-diid-semi-private-project.pdf)

m - [201105-m-diid-semi-private-project-detail.pdf](https://github.com/liqd/adhocracy-plus/files/5495670/201105-m-diid-semi-private-project-detail.pdf)

**Here is the link for the original design:** 
https://app.zeplin.io/project/5b051f895f8bcd4920567e89/dashboard?seid=5e86056fa298bb48fd2b9044

**Comment by phillimorland** [comment]
1 done
2 nav stacking
3 logo pic
4 done
5 sm screen same as below
6 lg screen bottom margin hero
7 sm footer
8 sm project page margins
