### ISSUE TITLE
DIID - don't allow users to participate who have not completed registration via shibbloeth

### ISSUE THREAD

**Issue by CarolingerSeilchenspringer** [liqd/adhocracy-plus#928]
**URL:** ???
**user:** user registered via shibboleth
**expected behaviour:** I can't do anything if I have not completed registration via shibboleth by hitting the registration button on adhocracy-form
**behaviour:** Account is already there and I can participate without ever completing registration
**important screensize:**
**device & browser:** 
**Comment/Question:** 

Screenshot?

**Comment by rmader** [comment]
Fixed by https://github.com/liqd/adhocracy-plus/commit/cd1d9ff735065eaba51c30264070ad9d001b8b0b
