### ISSUE TITLE
Initiators Dashboard: drop down of modules opens again after reload

### ISSUE THREAD

**Issue by hmkay** [liqd/adhocracy-plus#955]
**URL:** https://adhocracy.plus/liqd/dashboard/modules/brainstorming-119/phases/
**user:** admin
**expected behaviour:** If I minimise one module and reload (eg by saving) it stays minimised
**behaviour:** If I minimise one module and reload (eg by saving) it opens up again
**important screensize:** Desktop
**device & browser:** macOS Mojawave 10.14.6, Firefox 82.0.3 (64-Bit)

<img width="587" alt="Bildschirmfoto 2020-11-17 um 13 35 57" src="https://user-images.githubusercontent.com/30862422/99391072-e7637000-28d9-11eb-964f-147d22e73980.png">

**Comment by fuzzylogic2000** [comment]
We already have that in mB! So, it's not too hard to port over, but still an enhancement! If you want it, please add a story and close this issue @fredewe @lthueer or @hmkay (for kosmo).

**Comment by lthueer** [comment]
Added a story to the a+ backlog. Thank you!

**Comment by hmkay** [comment]
Not needed for KOSMO
