### ISSUE TITLE
popover for map ideas does not show

### ISSUE THREAD

**Issue by rittermo** [liqd/adhocracy-plus#987]
**URL:** 
https://adhocracy.plus/werder-havel/projects/zukunftshaushalt/

**user:** 
admin

**expected behaviour:** 
The popover should open when I click on an idea on the interactive map area

**behaviour:** 
The popover does not show.

**important screensize:**
all screen sizes

**device & browser:** 
macOS Big Sur, Safari 14.0.1

**Comment/Question:** 

Screenshot?

**Comment by phillimorland** [comment]
NOTE: safari issue possible link to error with safari content security policy?!
