### ISSUE TITLE
#3505 [a+] interactive event: livestream embed for interactive event

### ISSUE THREAD

**Issue by mcastro-lqd** [liqd/adhocracy-plus#989]
**URL:** https://aplus-dev.liqd.net/teststadt/interactiveevents/interaktive-veranstaltung-11/
**device & browser:** Both
**Comment/Question:** 

**I'm not taking the styling here in consideration** because from what I just saw I guess we will leave that for later, right? 

**Otherwise, the A+ styled SpeakUp is here:** 
https://zpl.io/aNrGZon

Livestream works well, but I noticed some small errors in the dashboard + interactive event:

**Here its a bit off:** 
<img width="322" alt="Screenshot 2020-12-01 at 17 42 37" src="https://user-images.githubusercontent.com/59610786/100770542-abfa9280-33fd-11eb-8543-28efa9cf8721.png">

**And I tried to add a question but it doesn't work:** 
<img width="492" alt="Screenshot 2020-12-01 at 17 47 48" src="https://user-images.githubusercontent.com/59610786/100770549-ad2bbf80-33fd-11eb-981f-28bd8de72bdb.png">

**Comment by phillimorland** [comment]
@mcastro-lqd the 500 error is fixed but if you can add to you list a simple design for 500 error on a+ that would be awesome! :) 
The tick being off is an old issue and is intermittent, as we will remove it in the near future we have decided that it is not something we will try to fix
